export type LoopStep = "listen" | "repeat" | "understand" | "recall";

export type Shloka = {
  id: string;
  chapter: number;
  verse: number;
  reference: string;
  sanskrit: string;
  tamil: string;
  transliteration: string;
  english: string;
  translationAuthor: string;
  reflectionPrompt: string;
  audioSrc?: string;
};

export const SHLOKA_SOURCE = "https://prabhupadagita.com/2012/10/17/108-imporant-slokas-from-the-1972-bhagavad-gita-as-it-is/";

export const SHLOKAS: Shloka[] = [
  {
    "id": "GS-001",
    "chapter": 1,
    "verse": 1,
    "reference": "1.1",
    "audioSrc": "/audio/1.1.mp3",
    "sanskrit": "धृतराष्ट्र उवाच\n\nधर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः।\n\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय।।1.1।।",
    "tamil": "திருதராஷ்ட்ர உவாச\n\nதர்மக்ஷேத்ரே குருக்ஷேத்ரே ஸமவேதா யுயுத்ஸவஃ।\n\nமாமகாஃ பாண்டவாஶ்சைவ கிமகுர்வத ஸஞ்ஜய।।1.1।।",
    "transliteration": "dhṛtarāṣṭra uvāca\ndharma-kṣetre kuru-kṣetre\nsamavetā yuyutsavaḥ\nmāmakāḥ pāṇḍavāś caiva\nkim akurvata sañjaya",
    "english": "1.1 Dhṛtarāṣṭra said: O Sañjaya, after assembling in the place of pilgrimage at Kurukṣetra, what did my sons and the sons of Pāṇḍu do, being desirous to fight?",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-002",
    "chapter": 2,
    "verse": 7,
    "reference": "2.7",
    "audioSrc": "/audio/2.7.mp3",
    "sanskrit": "कार्पण्यदोषोपहतस्वभावः\n\nपृच्छामि त्वां धर्मसंमूढचेताः।\n\nयच्छ्रेयः स्यान्निश्िचतं ब्रूहि तन्मे\n\nशिष्यस्तेऽहं शाधि मां त्वां प्रपन्नम्।।2.7।।",
    "tamil": "கார்பண்யதோஷோபஹதஸ்வபாவஃ\n\nபிருச்சாமி த்வாம் தர்மஸம்மூடசேதாஃ।\n\nயச்ச்ரேயஃ ஸ்யாந்நிஶ்ிசதம் ப்ரூஹி தந்மே\n\nஶிஷ்யஸ்தே'ஹம் ஶாதி மாம் த்வாம் ப்ரபந்நம்।।2.7।।",
    "transliteration": "kārpaṇya-doṣopahata-svabhāvaḥ\npṛcchāmi tvāṁ dharma-sammūḍha-cetāḥ\nyac chreyaḥ syān niścitaṁ brūhi tan me\nśiṣyas te ’haṁ śādhi māṁ tvāṁ prapannam",
    "english": "2.7 Now I am confused about my duty and have lost all composure because of weakness. In this condition I am asking You to tell me clearly what is best for me. Now I am Your disciple, and a soul surrendered unto You. Please instruct me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-003",
    "chapter": 2,
    "verse": 11,
    "reference": "2.11",
    "audioSrc": "/audio/2.11.mp3",
    "sanskrit": "श्री भगवानुवाच\n\nअशोच्यानन्वशोचस्त्वं प्रज्ञावादांश्च भाषसे।\n\nगतासूनगतासूंश्च नानुशोचन्ति पण्डिताः।।2.11।।",
    "tamil": "ஶ்ரீ பகவாநுவாச\n\nஅஶோச்யாநந்வஶோசஸ்த்வம் ப்ரஜ்ஞாவாதாம்ஶ்ச பாஷஸே।\n\nகதாஸூநகதாஸூம்ஶ்ச நாநுஶோசந்தி பண்டிதாஃ।।2.11।।",
    "transliteration": "śrī-bhagavān uvāca\naśocyān anvaśocas tvaṁ\nprajñā-vādāṁś ca bhāṣase\ngatāsūn agatāsūṁś ca\nnānuśocanti paṇḍitāḥ",
    "english": "2.11 The Supreme Personality of Godhead said: While speaking learned words, you are mourning for what is not worthy of grief. Those who are wise lament neither for the living nor for the dead.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-004",
    "chapter": 2,
    "verse": 12,
    "reference": "2.12",
    "audioSrc": "/audio/2.12.mp3",
    "sanskrit": "न त्वेवाहं जातु नासं न त्वं नेमे जनाधिपाः।\n\nन चैव न भविष्यामः सर्वे वयमतः परम्।।2.12।।",
    "tamil": "ந த்வேவாஹம் ஜாது நாஸம் ந த்வம் நேமே ஜநாதிபாஃ।\n\nந சைவ ந பவிஷ்யாமஃ ஸர்வே வயமதஃ பரம்।।2.12।।",
    "transliteration": "na tv evāhaṁ jātu nāsaṁ\nna tvaṁ neme janādhipāḥ\nna caiva na bhaviṣyāmaḥ\nsarve vayam ataḥ param",
    "english": "2.12 Never was there a time when I did not exist, nor you, nor all these kings; nor in the future shall any of us cease to be.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-005",
    "chapter": 2,
    "verse": 13,
    "reference": "2.13",
    "audioSrc": "/audio/2.13.mp3",
    "sanskrit": "देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा।\n\nतथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति।।2.13।।",
    "tamil": "தேஹிநோ'ஸ்மிந்யதா தேஹே கௌமாரம் யௌவநம் ஜரா।\n\nததா தேஹாந்தரப்ராப்திர்தீரஸ்தத்ர ந முஹ்யதி।।2.13।।",
    "transliteration": "dehino ’smin yathā dehe\nkaumāraṁ yauvanaṁ jarā\ntathā dehāntara-prāptir\ndhīras tatra na muhyati",
    "english": "2.13 As the embodied soul continually passes, in this body, from boyhood to youth to old age, the soul similarly passes into another body at death. The self-realized soul is not bewildered by such a change.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-006",
    "chapter": 2,
    "verse": 14,
    "reference": "2.14",
    "audioSrc": "/audio/2.14.mp3",
    "sanskrit": "मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः।\n\nआगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत।।2.14।।",
    "tamil": "மாத்ராஸ்பர்ஶாஸ்து கௌந்தேய ஶீதோஷ்ணஸுகதுஃகதாஃ।\n\nஆகமாபாயிநோ'நித்யாஸ்தாம்ஸ்திதிக்ஷஸ்வ பாரத।।2.14।।",
    "transliteration": "mātrā-sparśās tu kaunteya\nśītoṣṇa-sukha-duḥkha-dāḥ\nāgamāpāyino ’nityās\ntāṁs titikṣasva bhārata",
    "english": "2.14 O son of Kuntī, the nonpermanent appearance of happiness and distress, and their disappearance in due course, are like the appearance and disappearance of winter and summer seasons. They arise from sense perception, O scion of Bharata, and one must learn to tolerate them without being disturbed.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-007",
    "chapter": 2,
    "verse": 20,
    "reference": "2.20",
    "audioSrc": "/audio/2.20.mp3",
    "sanskrit": "न जायते म्रियते वा कदाचि\n\nन्नायं भूत्वा भविता वा न भूयः।\n\nअजो नित्यः शाश्वतोऽयं पुराणो\n\nन हन्यते हन्यमाने शरीरे।।2.20।।",
    "tamil": "ந ஜாயதே ம்ரியதே வா கதாசி\n\nந்நாயம் பூத்வா பவிதா வா ந பூயஃ।\n\nஅஜோ நித்யஃ ஶாஶ்வதோ'யம் புராணோ\n\nந ஹந்யதே ஹந்யமாநே ஶரீரே।।2.20।।",
    "transliteration": "na jāyate mriyate vā kadācin\nnāyaṁ bhūtvā bhavitā vā na bhūyaḥ\najo nityaḥ śāśvato ’yaṁ purāṇo\nna hanyate hanyamāne śarīre",
    "english": "2.20 For the soul there is never birth nor death. Nor, having once been, does he ever cease to be. He is unborn, eternal, ever-existing, undying and primeval. He is not slain when the body is slain.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-008",
    "chapter": 2,
    "verse": 22,
    "reference": "2.22",
    "audioSrc": "/audio/2.22.mp3",
    "sanskrit": "वासांसि जीर्णानि यथा विहाय\n\nनवानि गृह्णाति नरोऽपराणि।\n\nतथा शरीराणि विहाय जीर्णा\n\nन्यन्यानि संयाति नवानि देही।।2.22।।",
    "tamil": "வாஸாம்ஸி ஜீர்ணாநி யதா விஹாய\n\nநவாநி கிருஹ்ணாதி நரோ'பராணி।\n\nததா ஶரீராணி விஹாய ஜீர்ணா\n\nந்யந்யாநி ஸம்யாதி நவாநி தேஹீ।।2.22।।",
    "transliteration": "vāsāṁsi jīrṇāni yathā vihāya\nnavāni gṛhṇāti naro ’parāṇi\ntathā śarīrāṇi vihāya jīrṇāny\nanyāni saṁyāti navāni dehī",
    "english": "2.22 As a person puts on new garments, giving up old ones, similarly, the soul accepts new material bodies, giving up the old and useless ones.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-009",
    "chapter": 2,
    "verse": 23,
    "reference": "2.23",
    "audioSrc": "/audio/2.23.mp3",
    "sanskrit": "नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः।\n\nन चैनं क्लेदयन्त्यापो न शोषयति मारुतः।।2.23।।",
    "tamil": "நைநம் சிந்தந்தி ஶஸ்த்ராணி நைநம் தஹதி பாவகஃ।\n\nந சைநம் க்லேதயந்த்யாபோ ந ஶோஷயதி மாருதஃ।।2.23।।",
    "transliteration": "nainaṁ chindanti śastrāṇi\nnainaṁ dahati pāvakaḥ\nna cainaṁ kledayanty āpo\nna śoṣayati mārutaḥ",
    "english": "2.23 The soul can never be cut into pieces by any weapon, nor can he be burned by fire, nor moistened by water, nor withered by the wind.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-010",
    "chapter": 2,
    "verse": 27,
    "reference": "2.27",
    "audioSrc": "/audio/2.27.mp3",
    "sanskrit": "जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च।\n\nतस्मादपरिहार्येऽर्थे न त्वं शोचितुमर्हसि।।2.27।।",
    "tamil": "ஜாதஸ்ய ஹி த்ருவோ மிருத்யுர்த்ருவம் ஜந்ம மிருதஸ்ய ச।\n\nதஸ்மாதபரிஹார்யே'ர்தே ந த்வம் ஶோசிதுமர்ஹஸி।।2.27।।",
    "transliteration": "jātasya hi dhruvo mṛtyur\ndhruvaṁ janma mṛtasya ca\ntasmād aparihārye ’rthe\nna tvaṁ śocitum arhasi",
    "english": "2.27 For one who has taken his birth, death is certain; and for one who is dead, birth is certain. Therefore, in the unavoidable discharge of your duty, you should not lament.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-011",
    "chapter": 2,
    "verse": 30,
    "reference": "2.30",
    "audioSrc": "/audio/2.30.mp3",
    "sanskrit": "देही नित्यमवध्योऽयं देहे सर्वस्य भारत।\n\nतस्मात्सर्वाणि भूतानि न त्वं शोचितुमर्हसि।।2.30।।",
    "tamil": "தேஹீ நித்யமவத்யோ'யம் தேஹே ஸர்வஸ்ய பாரத।\n\nதஸ்மாத்ஸர்வாணி பூதாநி ந த்வம் ஶோசிதுமர்ஹஸி।।2.30।।",
    "transliteration": "dehī nityam avadhyo ’yaṁ\ndehe sarvasya bhārata\ntasmāt sarvāṇi bhūtāni\nna tvaṁ śocitum arhasi",
    "english": "2.30 O descendant of Bharata, he who dwells in the body is eternal and can never be slain. Therefore you need not grieve for any creature.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-012",
    "chapter": 2,
    "verse": 40,
    "reference": "2.40",
    "audioSrc": "/audio/2.40.mp3",
    "sanskrit": "नेहाभिक्रमनाशोऽस्ति प्रत्यवायो न विद्यते।\n\nस्वल्पमप्यस्य धर्मस्य त्रायते महतो भयात्।।2.40।।",
    "tamil": "நேஹாபிக்ரமநாஶோ'ஸ்தி ப்ரத்யவாயோ ந வித்யதே।\n\nஸ்வல்பமப்யஸ்ய தர்மஸ்ய த்ராயதே மஹதோ பயாத்।।2.40।।",
    "transliteration": "nehābhikrama-nāśo ’sti\npratyavāyo na vidyate\nsv-alpam apy asya dharmasya\ntrāyate mahato bhayāt",
    "english": "2.40 In this endeavor there is no loss or diminution, and a little advancement on this path can protect one from the most dangerous type of fear.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-013",
    "chapter": 2,
    "verse": 41,
    "reference": "2.41",
    "audioSrc": "/audio/2.41.mp3",
    "sanskrit": "व्यवसायात्मिका बुद्धिरेकेह कुरुनन्दन।\n\nबहुशाखा ह्यनन्ताश्च बुद्धयोऽव्यवसायिनाम्।।2.41।।",
    "tamil": "வ்யவஸாயாத்மிகா புத்திரேகேஹ குருநந்தந।\n\nபஹுஶாகா ஹ்யநந்தாஶ்ச புத்தயோ'வ்யவஸாயிநாம்।।2.41।।",
    "transliteration": "vyavasāyātmikā buddhir\nekeha kuru-nandana\nbahu-śākhā hy anantāś ca\nbuddhayo ’vyavasāyinām",
    "english": "2.41 Those who are on this path are resolute in purpose, and their aim is one. O beloved child of the Kurus, the intelligence of those who are irresolute is many-branched.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-014",
    "chapter": 2,
    "verse": 44,
    "reference": "2.44",
    "audioSrc": "/audio/2.44.mp3",
    "sanskrit": "भोगैश्वर्यप्रसक्तानां तयापहृतचेतसाम्।\n\nव्यवसायात्मिका बुद्धिः समाधौ न विधीयते।।2.44।।",
    "tamil": "போகைஶ்வர்யப்ரஸக்தாநாம் தயாபஹிருதசேதஸாம்।\n\nவ்யவஸாயாத்மிகா புத்திஃ ஸமாதௌ ந விதீயதே।।2.44।।",
    "transliteration": "bhogaiśvarya-prasaktānāṁ\ntayāpahṛta-cetasām\nvyavasāyātmikā buddhiḥ\nsamādhau na vidhīyate",
    "english": "2.44 In the minds of those who are too attached to sense enjoyment and material opulence, and who are bewildered by such things, the resolute determination of devotional service to the Supreme Lord does not take place.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-015",
    "chapter": 2,
    "verse": 45,
    "reference": "2.45",
    "audioSrc": "/audio/2.45.mp3",
    "sanskrit": "त्रैगुण्यविषया वेदा निस्त्रैगुण्यो भवार्जुन।\n\nनिर्द्वन्द्वो नित्यसत्त्वस्थो निर्योगक्षेम आत्मवान्।।2.45।।",
    "tamil": "த்ரைகுண்யவிஷயா வேதா நிஸ்த்ரைகுண்யோ பவார்ஜுந।\n\nநிர்த்வந்த்வோ நித்யஸத்த்வஸ்தோ நிர்யோகக்ஷேம ஆத்மவாந்।।2.45।।",
    "transliteration": "trai-guṇya-viṣayā vedā\nnistrai-guṇyo bhavārjuna\nnirdvandvo nitya-sattva-stho\nniryoga-kṣema ātmavān",
    "english": "2.45 The Vedas mainly deal with the subject of the three modes of material nature. Rise above these modes, O Arjuna. Be transcendental to all of them. Be free from all dualities and from all anxieties for gain and safety, and be established in the Self.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-016",
    "chapter": 2,
    "verse": 46,
    "reference": "2.46",
    "audioSrc": "/audio/2.46.mp3",
    "sanskrit": "यावानर्थ उदपाने सर्वतः संप्लुतोदके।\n\nतावान्सर्वेषु वेदेषु ब्राह्मणस्य विजानतः।।2.46।।",
    "tamil": "யாவாநர்த உதபாநே ஸர்வதஃ ஸம்ப்லுதோதகே।\n\nதாவாந்ஸர்வேஷு வேதேஷு ப்ராஹ்மணஸ்ய விஜாநதஃ।।2.46।।",
    "transliteration": "yāvān artha uda-pāne\nsarvataḥ samplutodake\ntāvān sarveṣu vedeṣu\nbrāhmaṇasya vijānataḥ",
    "english": "2.46 All purposes served by a small well can at once be served by a great reservoir of water. Similarly, all the purposes of the Vedas can be served to one who knows the purpose behind them.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-108",
    "chapter": 2,
    "verse": 47,
    "reference": "2.47",
    "audioSrc": "/audio/2.47.mp3",
    "sanskrit": "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\n\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि।।2.47।।",
    "tamil": "கர்மண்யேவாதிகாரஸ்தே மா பலேஷு கதாசந।\n\nமா கர்மபலஹேதுர்பூர்மா தே ஸங்கோ'ஸ்த்வகர்மணி।।2.47।।",
    "transliteration": "karmaṇy evādhikāras te\nmā phaleṣu kadācana\nmā karma-phala-hetur bhūr\nmā te saṅgo ’stv akarmaṇi",
    "english": "2.47 You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Never consider yourself to be the cause of the results of your activities, and never be attached to not doing your duty.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-017",
    "chapter": 2,
    "verse": 59,
    "reference": "2.59",
    "audioSrc": "/audio/2.59.mp3",
    "sanskrit": "विषया विनिवर्तन्ते निराहारस्य देहिनः।\n\nरसवर्जं रसोऽप्यस्य परं दृष्ट्वा निवर्तते।।2.59।।",
    "tamil": "விஷயா விநிவர்தந்தே நிராஹாரஸ்ய தேஹிநஃ।\n\nரஸவர்ஜம் ரஸோ'ப்யஸ்ய பரம் திருஷ்ட்வா நிவர்ததே।।2.59।।",
    "transliteration": "viṣayā vinivartante\nnirāhārasya dehinaḥ\nrasa-varjaṁ raso ’py asya\nparaṁ dṛṣṭvā nivartate",
    "english": "2.59 The embodied soul may be restricted from sense enjoyment, though the taste for sense objects remains. But, ceasing such engagements by experiencing a higher taste, he is fixed in consciousness.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-018",
    "chapter": 2,
    "verse": 62,
    "reference": "2.62",
    "audioSrc": "/audio/2.62.mp3",
    "sanskrit": "ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते।\n\nसङ्गात् संजायते कामः कामात्क्रोधोऽभिजायते।।2.62।।",
    "tamil": "த்யாயதோ விஷயாந்பும்ஸஃ ஸங்கஸ்தேஷூபஜாயதே।\n\nஸங்காத் ஸம்ஜாயதே காமஃ காமாத்க்ரோதோ'பிஜாயதே।।2.62।।",
    "transliteration": "dhyāyato viṣayān puṁsaḥ\nsaṅgas teṣūpajāyate\nsaṅgāt sañjāyate kāmaḥ\nkāmāt krodho ’bhijāyate",
    "english": "2.62 While contemplating the objects of the senses, a person develops attachment for them, and from such attachment lust develops, and from lust anger arises.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-019",
    "chapter": 2,
    "verse": 63,
    "reference": "2.63",
    "audioSrc": "/audio/2.63.mp3",
    "sanskrit": "क्रोधाद्भवति संमोहः संमोहात्स्मृतिविभ्रमः।\n\nस्मृतिभ्रंशाद् बुद्धिनाशो बुद्धिनाशात्प्रणश्यति।।2.63।।",
    "tamil": "க்ரோதாத்பவதி ஸம்மோஹஃ ஸம்மோஹாத்ஸ்மிருதிவிப்ரமஃ।\n\nஸ்மிருதிப்ரம்ஶாத் புத்திநாஶோ புத்திநாஶாத்ப்ரணஶ்யதி।।2.63।।",
    "transliteration": "krodhād bhavati sammohaḥ\nsammohāt smṛti-vibhramaḥ\nsmṛti-bhraṁśād buddhi-nāśo\nbuddhi-nāśāt praṇaśyati",
    "english": "2.63 From anger, delusion arises, and from delusion bewilderment of memory. When memory is bewildered, intelligence is lost, and when intelligence is lost, one falls down again into the material pool.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-020",
    "chapter": 2,
    "verse": 64,
    "reference": "2.64",
    "audioSrc": "/audio/2.64.mp3",
    "sanskrit": "रागद्वेषवियुक्तैस्तु विषयानिन्द्रियैश्चरन्।\n\nआत्मवश्यैर्विधेयात्मा प्रसादमधिगच्छति।।2.64।।",
    "tamil": "ராகத்வேஷவியுக்தைஸ்து விஷயாநிந்த்ரியைஶ்சரந்।\n\nஆத்மவஶ்யைர்விதேயாத்மா ப்ரஸாதமதிகச்சதி।।2.64।।",
    "transliteration": "rāga-dveṣa-vimuktais tu\nviṣayān indriyaiś caran\nātma-vaśyair vidheyātmā\nprasādam adhigacchati",
    "english": "2.64 One who can control his senses by practicing the regulated principles of freedom can obtain the complete mercy of the Lord and thus become free from all attachment and aversion.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-021",
    "chapter": 2,
    "verse": 69,
    "reference": "2.69",
    "audioSrc": "/audio/2.69.mp3",
    "sanskrit": "या निशा सर्वभूतानां तस्यां जागर्ति संयमी।\n\nयस्यां जाग्रति भूतानि सा निशा पश्यतो मुनेः।।2.69।।",
    "tamil": "யா நிஶா ஸர்வபூதாநாம் தஸ்யாம் ஜாகர்தி ஸம்யமீ।\n\nயஸ்யாம் ஜாக்ரதி பூதாநி ஸா நிஶா பஶ்யதோ முநேஃ।।2.69।।",
    "transliteration": "yā niśā sarva-bhūtānāṁ\ntasyāṁ jāgarti saṁyamī\nyasyāṁ jāgrati bhūtāni\nsā niśā paśyato muneḥ",
    "english": "2.69 What is night for all beings is the time of awakening for the self-controlled; and the time of awakening for all beings is night for the introspective sage.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-022",
    "chapter": 3,
    "verse": 9,
    "reference": "3.9",
    "audioSrc": "/audio/3.9.mp3",
    "sanskrit": "यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः।\n\nतदर्थं कर्म कौन्तेय मुक्तसंगः समाचर।।3.9।।",
    "tamil": "யஜ்ஞார்தாத்கர்மணோ'ந்யத்ர லோகோ'யம் கர்மபந்தநஃ।\n\nததர்தம் கர்ம கௌந்தேய முக்தஸம்கஃ ஸமாசர।।3.9।।",
    "transliteration": "yajñārthāt karmaṇo ’nyatra\nloko ’yaṁ karma-bandhanaḥ\ntad-arthaṁ karma kaunteya\nmukta-saṅgaḥ samācara",
    "english": "3.9 Work done as a sacrifice for Viṣṇu has to be performed, otherwise work binds one to this material world. Therefore, O son of Kuntī, perform your prescribed duties for His satisfaction, and in that way you will always remain unattached and free from bondage.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-023",
    "chapter": 3,
    "verse": 14,
    "reference": "3.14",
    "audioSrc": "/audio/3.14.mp3",
    "sanskrit": "अन्नाद्भवन्ति भूतानि पर्जन्यादन्नसम्भवः।\n\nयज्ञाद्भवति पर्जन्यो यज्ञः कर्मसमुद्भवः।।3.14।।",
    "tamil": "அந்நாத்பவந்தி பூதாநி பர்ஜந்யாதந்நஸம்பவஃ।\n\nயஜ்ஞாத்பவதி பர்ஜந்யோ யஜ்ஞஃ கர்மஸமுத்பவஃ।।3.14।।",
    "transliteration": "annād bhavanti bhūtāni\nparjanyād anna-sambhavaḥ\nyajñād bhavati parjanyo\nyajñaḥ karma-samudbhavaḥ",
    "english": "3.14 All living bodies subsist on food grains, which are produced from rain. Rains are produced by performance of yajña \\[sacrifice\\], and yajña is born of prescribed duties.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-024",
    "chapter": 3,
    "verse": 21,
    "reference": "3.21",
    "audioSrc": "/audio/3.21.mp3",
    "sanskrit": "यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः।\n\nस यत्प्रमाणं कुरुते लोकस्तदनुवर्तते।।3.21।।",
    "tamil": "யத்யதாசரதி ஶ்ரேஷ்டஸ்தத்ததேவேதரோ ஜநஃ।\n\nஸ யத்ப்ரமாணம் குருதே லோகஸ்ததநுவர்ததே।।3.21।।",
    "transliteration": "yad yad ācarati śreṣṭhas\ntat tad evetaro janaḥ\nsa yat pramāṇaṁ kurute\nlokas tad anuvartate",
    "english": "3.21 Whatever action is performed by a great man, common men follow in his footsteps. And whatever standards he sets by exemplary acts, all the world pursues.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-025",
    "chapter": 3,
    "verse": 27,
    "reference": "3.27",
    "audioSrc": "/audio/3.27.mp3",
    "sanskrit": "प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः।\n\nअहङ्कारविमूढात्मा कर्ताऽहमिति मन्यते।।3.27।।",
    "tamil": "ப்ரகிருதேஃ க்ரியமாணாநி குணைஃ கர்மாணி ஸர்வஶஃ।\n\nஅஹங்காரவிமூடாத்மா கர்தா'ஹமிதி மந்யதே।।3.27।।",
    "transliteration": "prakṛteḥ kriyamāṇāni\nguṇaiḥ karmāṇi sarvaśaḥ\nahaṅkāra-vimūḍhātmā\nkartāham iti manyate",
    "english": "3.27 The bewildered spirit soul, under the influence of the three modes of material nature, thinks himself to be the doer of activities, which are in actuality carried out by nature.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-026",
    "chapter": 3,
    "verse": 37,
    "reference": "3.37",
    "audioSrc": "/audio/3.37.mp3",
    "sanskrit": "श्री भगवानुवाच\n\nकाम एष क्रोध एष रजोगुणसमुद्भवः।\n\nमहाशनो महापाप्मा विद्ध्येनमिह वैरिणम्।।3.37।।",
    "tamil": "ஶ்ரீ பகவாநுவாச\n\nகாம ஏஷ க்ரோத ஏஷ ரஜோகுணஸமுத்பவஃ।\n\nமஹாஶநோ மஹாபாப்மா வித்த்யேநமிஹ வைரிணம்।।3.37।।",
    "transliteration": "śrī-bhagavān uvāca\nkāma eṣa krodha eṣa\nrajo-guṇa-samudbhavaḥ\nmahāśano mahā-pāpmā\nviddhy enam iha vairiṇam",
    "english": "3.37 The Supreme Personality of Godhead said: It is lust only, Arjuna, which is born of contact with the material mode of passion and later transformed into wrath, and which is the all-devouring sinful enemy of this world.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-027",
    "chapter": 4,
    "verse": 1,
    "reference": "4.1",
    "audioSrc": "/audio/4.1.mp3",
    "sanskrit": "श्री भगवानुवाच\n\nइमं विवस्वते योगं प्रोक्तवानहमव्ययम्।\n\nविवस्वान् मनवे प्राह मनुरिक्ष्वाकवेऽब्रवीत्।।4.1।।",
    "tamil": "ஶ்ரீ பகவாநுவாச\n\nஇமம் விவஸ்வதே யோகம் ப்ரோக்தவாநஹமவ்யயம்।\n\nவிவஸ்வாந் மநவே ப்ராஹ மநுரிக்ஷ்வாகவே'ப்ரவீத்।।4.1।।",
    "transliteration": "śrī-bhagavān uvāca\nimaṁ vivasvate yogaṁ\nproktavān aham avyayam\nvivasvān manave prāha\nmanur ikṣvākave ’bravīt",
    "english": "4.1 The Personality of Godhead, Lord Sri Krishna, said: I instructed this imperishable science of yoga to the sun-god, Vivasvan, and Vivasvan instructed it to Manu, the father of mankind, and Manu in turn instructed it to Iksvaku.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-028",
    "chapter": 4,
    "verse": 2,
    "reference": "4.2",
    "audioSrc": "/audio/4.2.mp3",
    "sanskrit": "एवं परम्पराप्राप्तमिमं राजर्षयो विदुः।\n\nस कालेनेह महता योगो नष्टः परन्तप।।4.2।।",
    "tamil": "ஏவம் பரம்பராப்ராப்தமிமம் ராஜர்ஷயோ விதுஃ।\n\nஸ காலேநேஹ மஹதா யோகோ நஷ்டஃ பரந்தப।।4.2।।",
    "transliteration": "evaṁ paramparā-prāptam\nimaṁ rājarṣayo viduḥ\nsa kāleneha mahatā\nyogo naṣṭaḥ parantapa",
    "english": "4.2 This supreme science was thus received through the chain of disciplic succession, and the saintly kings understood it in that way. But in course of time the succession was broken, and therefore the science as it is appears to be lost.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-029",
    "chapter": 4,
    "verse": 3,
    "reference": "4.3",
    "audioSrc": "/audio/4.3.mp3",
    "sanskrit": "स एवायं मया तेऽद्य योगः प्रोक्तः पुरातनः।\n\nभक्तोऽसि मे सखा चेति रहस्यं ह्येतदुत्तमम्।।4.3।।",
    "tamil": "ஸ ஏவாயம் மயா தே'த்ய யோகஃ ப்ரோக்தஃ புராதநஃ।\n\nபக்தோ'ஸி மே ஸகா சேதி ரஹஸ்யம் ஹ்யேததுத்தமம்।।4.3।।",
    "transliteration": "sa evāyaṁ mayā te ’dya\nyogaḥ proktaḥ purātanaḥ\nbhakto ’si me sakhā ceti\nrahasyaṁ hy etad uttamam",
    "english": "4.3 That very ancient science of the relationship with the Supreme is today told by Me to you because you are My devotee as well as My friend; therefore you can understand the transcendental mystery of this science.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-030",
    "chapter": 4,
    "verse": 6,
    "reference": "4.6",
    "audioSrc": "/audio/4.6.mp3",
    "sanskrit": "अजोऽपि सन्नव्ययात्मा भूतानामीश्वरोऽपि सन्।\n\nप्रकृतिं स्वामधिष्ठाय संभवाम्यात्ममायया।।4.6।।",
    "tamil": "அஜோ'பி ஸந்நவ்யயாத்மா பூதாநாமீஶ்வரோ'பி ஸந்।\n\nப்ரகிருதிம் ஸ்வாமதிஷ்டாய ஸம்பவாம்யாத்மமாயயா।।4.6।।",
    "transliteration": "ajo ’pi sann avyayātmā\nbhūtānām īśvaro ’pi san\nprakṛtiṁ svām adhiṣṭhāya\nsambhavāmy ātma-māyayā",
    "english": "4.6 Although I am unborn and My transcendental body never deteriorates, and although I am the Lord of all sentient beings, I still appear in every millennium in My original transcendental form.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-031",
    "chapter": 4,
    "verse": 7,
    "reference": "4.7",
    "audioSrc": "/audio/4.7.mp3",
    "sanskrit": "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत।\n\nअभ्युत्थानमधर्मस्य तदाऽऽत्मानं सृजाम्यहम्।।4.7।।",
    "tamil": "யதா யதா ஹி தர்மஸ்ய க்லாநிர்பவதி பாரத।\n\nஅப்யுத்தாநமதர்மஸ்ய ததா''த்மாநம் ஸிருஜாம்யஹம்।।4.7।।",
    "transliteration": "yadā yadā hi dharmasya\nglānir bhavati bhārata\nabhyutthānam adharmasya\ntadātmānaṁ sṛjāmy aham",
    "english": "4.7 Whenever and wherever there is a decline in religious practice, O descendant of Bharata, and a predominant rise of irreligion—at that time I descend Myself.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-032",
    "chapter": 4,
    "verse": 8,
    "reference": "4.8",
    "audioSrc": "/audio/4.8.mp3",
    "sanskrit": "परित्राणाय साधूनां विनाशाय च दुष्कृताम्।\n\nधर्मसंस्थापनार्थाय संभवामि युगे युगे।।4.8।।",
    "tamil": "பரித்ராணாய ஸாதூநாம் விநாஶாய ச துஷ்கிருதாம்।\n\nதர்மஸம்ஸ்தாபநார்தாய ஸம்பவாமி யுகே யுகே।।4.8।।",
    "transliteration": "paritrāṇāya sādhūnāṁ\nvināśāya ca duṣkṛtām\ndharma-saṁsthāpanārthāya\nsambhavāmi yuge yuge",
    "english": "4.8 In order to deliver the pious and to annihilate the miscreants, as well as to reestablish the principles of religion, I advent Myself millennium after millennium.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-033",
    "chapter": 4,
    "verse": 9,
    "reference": "4.9",
    "audioSrc": "/audio/4.9.mp3",
    "sanskrit": "जन्म कर्म च मे दिव्यमेवं यो वेत्ति तत्त्वतः।\n\nत्यक्त्वा देहं पुनर्जन्म नैति मामेति सोऽर्जुन।।4.9।।",
    "tamil": "ஜந்ம கர்ம ச மே திவ்யமேவம் யோ வேத்தி தத்த்வதஃ।\n\nத்யக்த்வா தேஹம் புநர்ஜந்ம நைதி மாமேதி ஸோ'ர்ஜுந।।4.9।।",
    "transliteration": "janma karma ca me divyam\nevaṁ yo vetti tattvataḥ\ntyaktvā dehaṁ punar janma\nnaiti mām eti so ’rjuna",
    "english": "4.9 One who knows the transcendental nature of My appearance and activities does not, upon leaving the body, take his birth again in this material world, but attains My eternal abode, O Arjuna.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-034",
    "chapter": 4,
    "verse": 10,
    "reference": "4.10",
    "audioSrc": "/audio/4.10.mp3",
    "sanskrit": "वीतरागभयक्रोधा मन्मया मामुपाश्रिताः।\n\nबहवो ज्ञानतपसा पूता मद्भावमागताः।।4.10।।",
    "tamil": "வீதராகபயக்ரோதா மந்மயா மாமுபாஶ்ரிதாஃ।\n\nபஹவோ ஜ்ஞாநதபஸா பூதா மத்பாவமாகதாஃ।।4.10।।",
    "transliteration": "vīta-rāga-bhaya-krodhā\nman-mayā mām upāśritāḥ\nbahavo jñāna-tapasā\npūtā mad-bhāvam āgatāḥ",
    "english": "4.10 Being freed from attachment, fear and anger, being fully absorbed in Me and taking refuge in Me, many, many persons in the past became purifled by knowledge of Me—and thus they all attained transcendental love for Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-035",
    "chapter": 4,
    "verse": 11,
    "reference": "4.11",
    "audioSrc": "/audio/4.11.mp3",
    "sanskrit": "ये यथा मां प्रपद्यन्ते तांस्तथैव भजाम्यहम्।\n\nमम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः।।4.11।।",
    "tamil": "யே யதா மாம் ப்ரபத்யந்தே தாம்ஸ்ததைவ பஜாம்யஹம்।\n\nமம வர்த்மாநுவர்தந்தே மநுஷ்யாஃ பார்த ஸர்வஶஃ।।4.11।।",
    "transliteration": "ye yathā māṁ prapadyante\ntāṁs tathaiva bhajāmy aham\nmama vartmānuvartante\nmanuṣyāḥ pārtha sarvaśaḥ",
    "english": "4.11 All of them—as they surrender unto Me—I reward accordingly. Everyone follows My path in all respects, O son of Pṛthā.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-036",
    "chapter": 4,
    "verse": 13,
    "reference": "4.13",
    "audioSrc": "/audio/4.13.mp3",
    "sanskrit": "चातुर्वर्ण्यं मया सृष्टं गुणकर्मविभागशः।\n\nतस्य कर्तारमपि मां विद्ध्यकर्तारमव्ययम्।।4.13।।",
    "tamil": "சாதுர்வர்ண்யம் மயா ஸிருஷ்டம் குணகர்மவிபாகஶஃ।\n\nதஸ்ய கர்தாரமபி மாம் வித்த்யகர்தாரமவ்யயம்।।4.13।।",
    "transliteration": "cātur-varṇyaṁ mayā sṛṣṭaṁ\nguṇa-karma-vibhāgaśaḥ\ntasya kartāram api māṁ\nviddhy akartāram avyayam",
    "english": "4.13 According to the three modes of material nature and the work ascribed to them, the four divisions of human society were created by Me. And, although I am the creator of this system, you should know that I am yet the non-doer, being unchangeable.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-037",
    "chapter": 4,
    "verse": 34,
    "reference": "4.34",
    "audioSrc": "/audio/4.34.mp3",
    "sanskrit": "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया।\n\nउपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः।।4.34।।",
    "tamil": "தத்வித்தி ப்ரணிபாதேந பரிப்ரஶ்நேந ஸேவயா।\n\nஉபதேக்ஷ்யந்தி தே ஜ்ஞாநம் ஜ்ஞாநிநஸ்தத்த்வதர்ஶிநஃ।।4.34।।",
    "transliteration": "tad viddhi praṇipātena\nparipraśnena sevayā\nupadekṣyanti te jñānaṁ\njñāninas tattva-darśinaḥ",
    "english": "4.34 Just try to learn the truth by approaching a spiritual master. Inquire from him submissively and render service unto him. The self-realized soul can impart knowledge unto you because he has seen the truth.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-038",
    "chapter": 5,
    "verse": 18,
    "reference": "5.18",
    "audioSrc": "/audio/5.18.mp3",
    "sanskrit": "विद्याविनयसंपन्ने ब्राह्मणे गवि हस्तिनि।\n\nशुनि चैव श्वपाके च पण्डिताः समदर्शिनः।।5.18।।",
    "tamil": "வித்யாவிநயஸம்பந்நே ப்ராஹ்மணே கவி ஹஸ்திநி।\n\nஶுநி சைவ ஶ்வபாகே ச பண்டிதாஃ ஸமதர்ஶிநஃ।।5.18।।",
    "transliteration": "vidyā-vinaya-sampanne\nbrāhmaṇe gavi hastini\nśuni caiva śva-pāke ca\npaṇḍitāḥ sama-darśinaḥ",
    "english": "5.18 The humble sage, by virtue of true knowledge, sees with equal vision a learned and gentle brāhmaṇa, a cow, an elephant, a dog and a dog-eater \\[outcaste\\] .",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-039",
    "chapter": 5,
    "verse": 22,
    "reference": "5.22",
    "audioSrc": "/audio/5.22.mp3",
    "sanskrit": "ये हि संस्पर्शजा भोगा दुःखयोनय एव ते।\n\nआद्यन्तवन्तः कौन्तेय न तेषु रमते बुधः।।5.22।।",
    "tamil": "யே ஹி ஸம்ஸ்பர்ஶஜா போகா துஃகயோநய ஏவ தே।\n\nஆத்யந்தவந்தஃ கௌந்தேய ந தேஷு ரமதே புதஃ।।5.22।।",
    "transliteration": "ye hi saṁsparśa-jā bhogā\nduḥkha-yonaya eva te\nādy-antavantaḥ kaunteya\nna teṣu ramate budhaḥ",
    "english": "5.22 An intelligent person does not take part in the sources of misery, which are due to contact with the material senses. O son of Kuntī, such pleasures have a beginning and an end, and so the wise man does not delight in them.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-040",
    "chapter": 5,
    "verse": 29,
    "reference": "5.29",
    "audioSrc": "/audio/5.29.mp3",
    "sanskrit": "भोक्तारं यज्ञतपसां सर्वलोकमहेश्वरम्।\n\nसुहृदं सर्वभूतानां ज्ञात्वा मां शान्तिमृच्छति।।5.29।।",
    "tamil": "போக்தாரம் யஜ்ஞதபஸாம் ஸர்வலோகமஹேஶ்வரம்।\n\nஸுஹிருதம் ஸர்வபூதாநாம் ஜ்ஞாத்வா மாம் ஶாந்திமிருச்சதி।।5.29।।",
    "transliteration": "bhoktāraṁ yajña-tapasāṁ\nsarva-loka-maheśvaram\nsuhṛdaṁ sarva-bhūtānāṁ\njñātvā māṁ śāntim ṛcchati",
    "english": "5.29 The sages, knowing Me as the ultimate purpose of all sacrifices and austerities, the Supreme Lord of all planets and demigods and the benefactor and well-wisher of all living entities, attain peace from the pangs of material miseries.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-041",
    "chapter": 6,
    "verse": 17,
    "reference": "6.17",
    "audioSrc": "/audio/6.17.mp3",
    "sanskrit": "युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु।\n\nयुक्तस्वप्नावबोधस्य योगो भवति दुःखहा।।6.17।।",
    "tamil": "யுக்தாஹாரவிஹாரஸ்ய யுக்தசேஷ்டஸ்ய கர்மஸு।\n\nயுக்தஸ்வப்நாவபோதஸ்ய யோகோ பவதி துஃகஹா।।6.17।।",
    "transliteration": "yuktāhāra-vihārasya\nyukta-ceṣṭasya karmasu\nyukta-svapnāvabodhasya\nyogo bhavati duḥkha-hā",
    "english": "6.17 He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-042",
    "chapter": 6,
    "verse": 41,
    "reference": "6.41",
    "audioSrc": "/audio/6.41.mp3",
    "sanskrit": "प्राप्य पुण्यकृतां लोकानुषित्वा शाश्वतीः समाः।\n\nशुचीनां श्रीमतां गेहे योगभ्रष्टोऽभिजायते।।6.41।।",
    "tamil": "ப்ராப்ய புண்யகிருதாம் லோகாநுஷித்வா ஶாஶ்வதீஃ ஸமாஃ।\n\nஶுசீநாம் ஶ்ரீமதாம் கேஹே யோகப்ரஷ்டோ'பிஜாயதே।।6.41।।",
    "transliteration": "prāpya puṇya-kṛtāṁ lokān\nuṣitvā śāśvatīḥ samāḥ\nśucīnāṁ śrīmatāṁ gehe\nyoga-bhraṣṭo ’bhijāyate",
    "english": "6.41 The unsuccessful yogī, after many, many years of enjoyment on the planets of the pious living entities, is born into a family of righteous people, or into a family of rich aristocracy.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-043",
    "chapter": 6,
    "verse": 47,
    "reference": "6.47",
    "audioSrc": "/audio/6.47.mp3",
    "sanskrit": "योगिनामपि सर्वेषां मद्गतेनान्तरात्मना।\n\nश्रद्धावान्भजते यो मां स मे युक्ततमो मतः।।6.47।।",
    "tamil": "யோகிநாமபி ஸர்வேஷாம் மத்கதேநாந்தராத்மநா।\n\nஶ்ரத்தாவாந்பஜதே யோ மாம் ஸ மே யுக்ததமோ மதஃ।।6.47।।",
    "transliteration": "yoginām api sarveṣāṁ\nmad-gatenāntar-ātmanā\nśraddhāvān bhajate yo māṁ\nsa me yuktatamo mataḥ",
    "english": "6.47 And of all yogīs, he who always abides in Me with great faith, worshiping Me in transcendental loving service, is most intimately united with Me in yoga and is the highest of all.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-044",
    "chapter": 7,
    "verse": 3,
    "reference": "7.3",
    "audioSrc": "/audio/7.3.mp3",
    "sanskrit": "मनुष्याणां सहस्रेषु कश्िचद्यतति सिद्धये।\n\nयततामपि सिद्धानां कश्िचन्मां वेत्ति तत्त्वतः।।7.3।।",
    "tamil": "மநுஷ்யாணாம் ஸஹஸ்ரேஷு கஶ்ிசத்யததி ஸித்தயே।\n\nயததாமபி ஸித்தாநாம் கஶ்ிசந்மாம் வேத்தி தத்த்வதஃ।।7.3।।",
    "transliteration": "manuṣyāṇāṁ sahasreṣu\nkaścid yatati siddhaye\nyatatām api siddhānāṁ\nkaścin māṁ vetti tattvataḥ",
    "english": "7.3 Out of many thousands among men, one may endeavor for perfection, and of those who have achieved perfection, hardly one knows Me in truth.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-045",
    "chapter": 7,
    "verse": 4,
    "reference": "7.4",
    "audioSrc": "/audio/7.4.mp3",
    "sanskrit": "भूमिरापोऽनलो वायुः खं मनो बुद्धिरेव च।\n\nअहङ्कार इतीयं मे भिन्ना प्रकृतिरष्टधा।।7.4।।",
    "tamil": "பூமிராபோ'நலோ வாயுஃ கம் மநோ புத்திரேவ ச।\n\nஅஹங்கார இதீயம் மே பிந்நா ப்ரகிருதிரஷ்டதா।।7.4।।",
    "transliteration": "bhūmir āpo ’nalo vāyuḥ\nkhaṁ mano buddhir eva ca\nahaṅkāra itīyaṁ me\nbhinnā prakṛtir aṣṭadhā",
    "english": "7.4 Earth, water, fire, air, ether, mind, intelligence and false ego—altogether these eight comprise My separated material energies.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-046",
    "chapter": 7,
    "verse": 5,
    "reference": "7.5",
    "audioSrc": "/audio/7.5.mp3",
    "sanskrit": "अपरेयमितस्त्वन्यां प्रकृतिं विद्धि मे पराम्।\n\nजीवभूतां महाबाहो ययेदं धार्यते जगत्।।7.5।।",
    "tamil": "அபரேயமிதஸ்த்வந்யாம் ப்ரகிருதிம் வித்தி மே பராம்।\n\nஜீவபூதாம் மஹாபாஹோ யயேதம் தார்யதே ஜகத்।।7.5।।",
    "transliteration": "apareyam itas tv anyāṁ\nprakṛtiṁ viddhi me parām\njīva-bhūtāṁ mahā-bāho\nyayedaṁ dhāryate jagat",
    "english": "7.5 Besides this inferior nature, O mighty-armed Arjuna, there is a superior energy of Mine, which are all living entities who are struggling with material nature and are sustaining the universe.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-047",
    "chapter": 7,
    "verse": 7,
    "reference": "7.7",
    "audioSrc": "/audio/7.7.mp3",
    "sanskrit": "मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय।\n\nमयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव।।7.7।।",
    "tamil": "மத்தஃ பரதரம் நாந்யத்கிஞ்சிதஸ்தி தநஞ்ஜய।\n\nமயி ஸர்வமிதம் ப்ரோதம் ஸூத்ரே மணிகணா இவ।।7.7।।",
    "transliteration": "mattaḥ parataraṁ nānyat\nkiñcid asti dhanañjaya\nmayi sarvam idaṁ protaṁ\nsūtre maṇi-gaṇā iva",
    "english": "7.7 O conquerer of wealth \\[Arjuna\\], there is no Truth superior to Me. Everything rests upon Me, as pearls are strung on a thread.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-048",
    "chapter": 7,
    "verse": 14,
    "reference": "7.14",
    "audioSrc": "/audio/7.14.mp3",
    "sanskrit": "दैवी ह्येषा गुणमयी मम माया दुरत्यया।\n\nमामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते।।7.14।।",
    "tamil": "தைவீ ஹ்யேஷா குணமயீ மம மாயா துரத்யயா।\n\nமாமேவ யே ப்ரபத்யந்தே மாயாமேதாம் தரந்தி தே।।7.14।।",
    "transliteration": "daivī hy eṣā guṇa-mayī\nmama māyā duratyayā\nmām eva ye prapadyante\nmāyām etāṁ taranti te",
    "english": "7.14 This divine energy of Mine, consisting of the three modes of material nature, is difficult to overcome. But those who have surrendered unto Me can easily cross beyond it.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-049",
    "chapter": 7,
    "verse": 15,
    "reference": "7.15",
    "audioSrc": "/audio/7.15.mp3",
    "sanskrit": "न मां दुष्कृतिनो मूढाः प्रपद्यन्ते नराधमाः।\n\nमाययापहृतज्ञाना आसुरं भावमाश्रिताः।।7.15।।",
    "tamil": "ந மாம் துஷ்கிருதிநோ மூடாஃ ப்ரபத்யந்தே நராதமாஃ।\n\nமாயயாபஹிருதஜ்ஞாநா ஆஸுரம் பாவமாஶ்ரிதாஃ।।7.15।।",
    "transliteration": "na māṁ duṣkṛtino mūḍhāḥ\nprapadyante narādhamāḥ\nmāyayāpahṛta-jñānā\nāsuraṁ bhāvam āśritāḥ",
    "english": "7.15 Those miscreants who are grossly foolish, lowest among mankind, whose knowledge is stolen by illusion, and who partake of the atheistic nature of demons, do not surrender unto Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-050",
    "chapter": 7,
    "verse": 16,
    "reference": "7.16",
    "audioSrc": "/audio/7.16.mp3",
    "sanskrit": "चतुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन।\n\nआर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ।।7.16।।",
    "tamil": "சதுர்விதா பஜந்தே மாம் ஜநாஃ ஸுகிருதிநோ'ர்ஜுந।\n\nஆர்தோ ஜிஜ்ஞாஸுரர்தார்தீ ஜ்ஞாநீ ச பரதர்ஷப।।7.16।।",
    "transliteration": "catur-vidhā bhajante māṁ\njanāḥ sukṛtino ’rjuna\nārto jijñāsur arthārthī\njñānī ca bharatarṣabha",
    "english": "7.16 O best among the Bhāratas \\[Arjuna\\], four kinds of pious men render devotional service unto Me—the distressed, the desirer of wealth, the inquisitive, and he who is searching for knowledge of the Absolute.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-051",
    "chapter": 7,
    "verse": 19,
    "reference": "7.19",
    "audioSrc": "/audio/7.19.mp3",
    "sanskrit": "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते।\n\nवासुदेवः सर्वमिति स महात्मा सुदुर्लभः।।7.19।।",
    "tamil": "பஹூநாம் ஜந்மநாமந்தே ஜ்ஞாநவாந்மாம் ப்ரபத்யதே।\n\nவாஸுதேவஃ ஸர்வமிதி ஸ மஹாத்மா ஸுதுர்லபஃ।।7.19।।",
    "transliteration": "bahūnāṁ janmanām ante\njñānavān māṁ prapadyate\nvāsudevaḥ sarvam iti\nsa mahātmā su-durlabhaḥ",
    "english": "7.19 After many births and deaths, he who is actually in knowledge surrenders unto Me, knowing Me to be the cause of all causes and all that is. Such a great soul is very rare.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-052",
    "chapter": 7,
    "verse": 25,
    "reference": "7.25",
    "audioSrc": "/audio/7.25.mp3",
    "sanskrit": "नाहं प्रकाशः सर्वस्य योगमायासमावृतः।\n\nमूढोऽयं नाभिजानाति लोको मामजमव्ययम्।।7.25।।",
    "tamil": "நாஹம் ப்ரகாஶஃ ஸர்வஸ்ய யோகமாயாஸமாவிருதஃ।\n\nமூடோ'யம் நாபிஜாநாதி லோகோ மாமஜமவ்யயம்।।7.25।।",
    "transliteration": "nāhaṁ prakāśaḥ sarvasya\nyoga-māyā-samāvṛtaḥ\nmūḍho ’yaṁ nābhijānāti\nloko mām ajam avyayam",
    "english": "7.25 I am never manifest to the foolish and unintelligent. For them I am covered by My eternal creative potency \\[yoga-māyā\\]; and so the deluded world knows Me not, who am unborn and infallible.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-053",
    "chapter": 7,
    "verse": 26,
    "reference": "7.26",
    "audioSrc": "/audio/7.26.mp3",
    "sanskrit": "वेदाहं समतीतानि वर्तमानानि चार्जुन।\n\nभविष्याणि च भूतानि मां तु वेद न कश्चन।।7.26।।",
    "tamil": "வேதாஹம் ஸமதீதாநி வர்தமாநாநி சார்ஜுந।\n\nபவிஷ்யாணி ச பூதாநி மாம் து வேத ந கஶ்சந।।7.26।।",
    "transliteration": "vedāhaṁ samatītāni\nvartamānāni cārjuna\nbhaviṣyāṇi ca bhūtāni\nmāṁ tu veda na kaścana",
    "english": "7.26 O Arjuna, as the Supreme Personality of Godhead, I know everything that has happened in the past, all that is happening in the present, and all things that are yet to come. I also know all living entities; but Me no one knows.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-054",
    "chapter": 7,
    "verse": 27,
    "reference": "7.27",
    "audioSrc": "/audio/7.27.mp3",
    "sanskrit": "इच्छाद्वेषसमुत्थेन द्वन्द्वमोहेन भारत।\n\nसर्वभूतानि संमोहं सर्गे यान्ति परन्तप।।7.27।।",
    "tamil": "இச்சாத்வேஷஸமுத்தேந த்வந்த்வமோஹேந பாரத।\n\nஸர்வபூதாநி ஸம்மோஹம் ஸர்கே யாந்தி பரந்தப।।7.27।।",
    "transliteration": "icchā-dveṣa-samutthena\ndvandva-mohena bhārata\nsarva-bhūtāni sammohaṁ\nsarge yānti parantapa",
    "english": "7.27 O scion of Bharata \\[Arjuna\\], O conquerer of the foe, all living entities are born into delusion, overcome by the dualities of desire and hate.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-055",
    "chapter": 7,
    "verse": 28,
    "reference": "7.28",
    "audioSrc": "/audio/7.28.mp3",
    "sanskrit": "येषां त्वन्तगतं पापं जनानां पुण्यकर्मणाम्।\n\nते द्वन्द्वमोहनिर्मुक्ता भजन्ते मां दृढव्रताः।।7.28।।",
    "tamil": "யேஷாம் த்வந்தகதம் பாபம் ஜநாநாம் புண்யகர்மணாம்।\n\nதே த்வந்த்வமோஹநிர்முக்தா பஜந்தே மாம் திருடவ்ரதாஃ।।7.28।।",
    "transliteration": "yeṣāṁ tv anta-gataṁ pāpaṁ\njanānāṁ puṇya-karmaṇām\nte dvandva-moha-nirmuktā\nbhajante māṁ dṛḍha-vratāḥ",
    "english": "7.28 Persons who have acted piously in previous lives and in this life, whose sinful actions are completely eradicated and who are freed from the duality of delusion, engage themselves in My service with determination.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-056",
    "chapter": 8,
    "verse": 5,
    "reference": "8.5",
    "audioSrc": "/audio/8.5.mp3",
    "sanskrit": "अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम्।\n\nयः प्रयाति स मद्भावं याति नास्त्यत्र संशयः।।8.5।।",
    "tamil": "அந்தகாலே ச மாமேவ ஸ்மரந்முக்த்வா கலேவரம்।\n\nயஃ ப்ரயாதி ஸ மத்பாவம் யாதி நாஸ்த்யத்ர ஸம்ஶயஃ।।8.5।।",
    "transliteration": "anta-kāle ca mām eva\nsmaran muktvā kalevaram\nyaḥ prayāti sa mad-bhāvaṁ\nyāti nāsty atra saṁśayaḥ",
    "english": "8.5 And whoever, at the time of death, quits his body, remembering Me alone, at once attains My nature. Of this there is no doubt.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-057",
    "chapter": 8,
    "verse": 6,
    "reference": "8.6",
    "audioSrc": "/audio/8.6.mp3",
    "sanskrit": "यं यं वापि स्मरन्भावं त्यजत्यन्ते कलेवरम्।\n\nतं तमेवैति कौन्तेय सदा तद्भावभावितः।।8.6।।",
    "tamil": "யம் யம் வாபி ஸ்மரந்பாவம் த்யஜத்யந்தே கலேவரம்।\n\nதம் தமேவைதி கௌந்தேய ஸதா தத்பாவபாவிதஃ।।8.6।।",
    "transliteration": "yaṁ yaṁ vāpi smaran bhāvaṁ\ntyajaty ante kalevaram\ntaṁ tam evaiti kaunteya\nsadā tad-bhāva-bhāvitaḥ",
    "english": "8.6 Whatever state of being one remembers when he quits his body, that state he will attain without fail.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-058",
    "chapter": 8,
    "verse": 7,
    "reference": "8.7",
    "audioSrc": "/audio/8.7.mp3",
    "sanskrit": "तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च।\n\nमय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयम्।।8.7।।",
    "tamil": "தஸ்மாத்ஸர்வேஷு காலேஷு மாமநுஸ்மர யுத்ய ச।\n\nமய்யர்பிதமநோபுத்திர்மாமேவைஷ்யஸ்யஸம்ஶயம்।।8.7।।",
    "transliteration": "tasmāt sarveṣu kāleṣu\nmām anusmara yudhya ca\nmayy arpita-mano-buddhir\nmām evaiṣyasy asaṁśayaḥ",
    "english": "8.7 Therefore, Arjuna, you should always think of Me in the form of Kṛṣṇa and at the same time carry out your prescribed duty of fighting. With your activities dedicated to Me and your mind and intelligence fixed on Me, you will attain Me without doubt.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-059",
    "chapter": 8,
    "verse": 14,
    "reference": "8.14",
    "audioSrc": "/audio/8.14.mp3",
    "sanskrit": "अनन्यचेताः सततं यो मां स्मरति नित्यशः।\n\nतस्याहं सुलभः पार्थ नित्ययुक्तस्य योगिनः।।8.14।।",
    "tamil": "அநந்யசேதாஃ ஸததம் யோ மாம் ஸ்மரதி நித்யஶஃ।\n\nதஸ்யாஹம் ஸுலபஃ பார்த நித்யயுக்தஸ்ய யோகிநஃ।।8.14।।",
    "transliteration": "ananya-cetāḥ satataṁ\nyo māṁ smarati nityaśaḥ\ntasyāhaṁ sulabhaḥ pārtha\nnitya-yuktasya yoginaḥ",
    "english": "8.14 For one who remembers Me without deviation, I am easy to obtain, O son of Pṛthā, because of his constant engagement in devotional service.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-060",
    "chapter": 8,
    "verse": 15,
    "reference": "8.15",
    "audioSrc": "/audio/8.15.mp3",
    "sanskrit": "मामुपेत्य पुनर्जन्म दुःखालयमशाश्वतम्।\n\nनाप्नुवन्ति महात्मानः संसिद्धिं परमां गताः।।8.15।।",
    "tamil": "மாமுபேத்ய புநர்ஜந்ம துஃகாலயமஶாஶ்வதம்।\n\nநாப்நுவந்தி மஹாத்மாநஃ ஸம்ஸித்திம் பரமாம் கதாஃ।।8.15।।",
    "transliteration": "mām upetya punar janma\nduḥkhālayam aśāśvatam\nnāpnuvanti mahātmānaḥ\nsaṁsiddhiṁ paramāṁ gatāḥ",
    "english": "8.15 After attaining Me, the great souls, who are yogīs in devotion, never return to this temporary world, which is full of miseries, because they have attained the highest perfection.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-061",
    "chapter": 8,
    "verse": 16,
    "reference": "8.16",
    "audioSrc": "/audio/8.16.mp3",
    "sanskrit": "आब्रह्मभुवनाल्लोकाः पुनरावर्तिनोऽर्जुन।\n\nमामुपेत्य तु कौन्तेय पुनर्जन्म न विद्यते।।8.16।।",
    "tamil": "ஆப்ரஹ்மபுவநால்லோகாஃ புநராவர்திநோ'ர்ஜுந।\n\nமாமுபேத்ய து கௌந்தேய புநர்ஜந்ம ந வித்யதே।।8.16।।",
    "transliteration": "ā-brahma-bhuvanāl lokāḥ\npunar āvartino ’rjuna\nmām upetya tu kaunteya\npunar janma na vidyate",
    "english": "8.16 From the highest planet in the material world down to the lowest, all are places of misery wherein repeated birth and death take place. But one who attains to My abode, O son of Kuntī, never takes birth again.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-062",
    "chapter": 8,
    "verse": 28,
    "reference": "8.28",
    "audioSrc": "/audio/8.28.mp3",
    "sanskrit": "वेदेषु यज्ञेषु तपःसु चैव\n\nदानेषु यत्पुण्यफलं प्रदिष्टम्।\n\nअत्येति तत्सर्वमिदं विदित्वा\n\nयोगी परं स्थानमुपैति चाद्यम्।।8.28।।",
    "tamil": "வேதேஷு யஜ்ஞேஷு தபஃஸு சைவ\n\nதாநேஷு யத்புண்யபலம் ப்ரதிஷ்டம்।\n\nஅத்யேதி தத்ஸர்வமிதம் விதித்வா\n\nயோகீ பரம் ஸ்தாநமுபைதி சாத்யம்।।8.28।।",
    "transliteration": "vedeṣu yajñeṣu tapaḥsu caiva\ndāneṣu yat puṇya-phalaṁ pradiṣṭam\natyeti tat sarvam idaṁ viditvā\nyogī paraṁ sthānam upaiti cādyam",
    "english": "8.28 A person who accepts the path of devotional service is not bereft of the results derived from studying the Vedas, performing austere sacrifices, giving charity or pursuing philosophical and fruitive activities. At the end he reaches the supreme abode.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-063",
    "chapter": 9,
    "verse": 2,
    "reference": "9.2",
    "audioSrc": "/audio/9.2.mp3",
    "sanskrit": "राजविद्या राजगुह्यं पवित्रमिदमुत्तमम्।\n\nप्रत्यक्षावगमं धर्म्यं सुसुखं कर्तुमव्ययम्।।9.2।।",
    "tamil": "ராஜவித்யா ராஜகுஹ்யம் பவித்ரமிதமுத்தமம்।\n\nப்ரத்யக்ஷாவகமம் தர்ம்யம் ஸுஸுகம் கர்துமவ்யயம்।।9.2।।",
    "transliteration": "rāja-vidyā rāja-guhyaṁ\npavitram idam uttamam\npratyakṣāvagamaṁ dharmyaṁ\nsu-sukhaṁ kartum avyayam",
    "english": "9.2 This knowledge is the king of education, the most secret of all secrets. It is the purest knowledge, and because it gives direct perception of the self by realization, it is the perfection of religion. It is everlasting, and it is joyfully performed.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-064",
    "chapter": 9,
    "verse": 4,
    "reference": "9.4",
    "audioSrc": "/audio/9.4.mp3",
    "sanskrit": "मया ततमिदं सर्वं जगदव्यक्तमूर्तिना।\n\nमत्स्थानि सर्वभूतानि न चाहं तेष्ववस्थितः।।9.4।।",
    "tamil": "மயா ததமிதம் ஸர்வம் ஜகதவ்யக்தமூர்திநா।\n\nமத்ஸ்தாநி ஸர்வபூதாநி ந சாஹம் தேஷ்வவஸ்திதஃ।।9.4।।",
    "transliteration": "mayā tatam idaṁ sarvaṁ\njagad avyakta-mūrtinā\nmat-sthāni sarva-bhūtāni\nna cāhaṁ teṣv avasthitaḥ",
    "english": "9.4 By Me, in My unmanifested form, this entire universe is pervaded. All beings are in Me, but I am not in them.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-065",
    "chapter": 9,
    "verse": 10,
    "reference": "9.10",
    "audioSrc": "/audio/9.10.mp3",
    "sanskrit": "मयाऽध्यक्षेण प्रकृतिः सूयते सचराचरम्।\n\nहेतुनाऽनेन कौन्तेय जगद्विपरिवर्तते।।9.10।।",
    "tamil": "மயா'த்யக்ஷேண ப்ரகிருதிஃ ஸூயதே ஸசராசரம்।\n\nஹேதுநா'நேந கௌந்தேய ஜகத்விபரிவர்ததே।।9.10।।",
    "transliteration": "mayādhyakṣeṇa prakṛtiḥ\nsūyate sa-carācaram\nhetunānena kaunteya\njagad viparivartate",
    "english": "9.10 This material nature is working under My direction, O son of Kuntī, and it is producing all moving and unmoving beings. By its rule this manifestation is created and annihilated again and again.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-066",
    "chapter": 9,
    "verse": 11,
    "reference": "9.11",
    "audioSrc": "/audio/9.11.mp3",
    "sanskrit": "अवजानन्ति मां मूढा मानुषीं तनुमाश्रितम्।\n\nपरं भावमजानन्तो मम भूतमहेश्वरम्।।9.11।।",
    "tamil": "அவஜாநந்தி மாம் மூடா மாநுஷீம் தநுமாஶ்ரிதம்।\n\nபரம் பாவமஜாநந்தோ மம பூதமஹேஶ்வரம்।।9.11।।",
    "transliteration": "avajānanti māṁ mūḍhā\nmānuṣīṁ tanum āśritam\nparaṁ bhāvam ajānanto\nmama bhūta-maheśvaram",
    "english": "9.11 Fools deride Me when I descend in the human form. They do not know My transcendental nature and My supreme dominion over all that be.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-067",
    "chapter": 9,
    "verse": 12,
    "reference": "9.12",
    "audioSrc": "/audio/9.12.mp3",
    "sanskrit": "मोघाशा मोघकर्माणो मोघज्ञाना विचेतसः।\n\nराक्षसीमासुरीं चैव प्रकृतिं मोहिनीं श्रिताः।।9.12।।",
    "tamil": "மோகாஶா மோககர்மாணோ மோகஜ்ஞாநா விசேதஸஃ।\n\nராக்ஷஸீமாஸுரீம் சைவ ப்ரகிருதிம் மோஹிநீம் ஶ்ரிதாஃ।।9.12।।",
    "transliteration": "moghāśā mogha-karmāṇo\nmogha-jñānā vicetasaḥ\nrākṣasīm āsurīṁ caiva\nprakṛtiṁ mohinīṁ śritāḥ",
    "english": "9.12 Those who are thus bewildered are attracted by demonic and atheistic views. In that deluded condition, their hopes for liberation, their fruitive activities, and their culture of knowledge are all defeated.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-068",
    "chapter": 9,
    "verse": 13,
    "reference": "9.13",
    "audioSrc": "/audio/9.13.mp3",
    "sanskrit": "महात्मानस्तु मां पार्थ दैवीं प्रकृतिमाश्रिताः।\n\nभजन्त्यनन्यमनसो ज्ञात्वा भूतादिमव्ययम्।।9.13।।",
    "tamil": "மஹாத்மாநஸ்து மாம் பார்த தைவீம் ப்ரகிருதிமாஶ்ரிதாஃ।\n\nபஜந்த்யநந்யமநஸோ ஜ்ஞாத்வா பூதாதிமவ்யயம்।।9.13।।",
    "transliteration": "mahātmānas tu māṁ pārtha\ndaivīṁ prakṛtim āśritāḥ\nbhajanty ananya-manaso\njñātvā bhūtādim avyayam",
    "english": "9.13 O son of Pṛthā, those who are not deluded, the great souls, are under the protection of the divine nature. They are fully engaged in devotional service because they know Me as the Supreme Personality of Godhead, original and inexhaustible.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-069",
    "chapter": 9,
    "verse": 14,
    "reference": "9.14",
    "audioSrc": "/audio/9.14.mp3",
    "sanskrit": "सततं कीर्तयन्तो मां यतन्तश्च दृढव्रताः।\n\nनमस्यन्तश्च मां भक्त्या नित्ययुक्ता उपासते।।9.14।।",
    "tamil": "ஸததம் கீர்தயந்தோ மாம் யதந்தஶ்ச திருடவ்ரதாஃ।\n\nநமஸ்யந்தஶ்ச மாம் பக்த்யா நித்யயுக்தா உபாஸதே।।9.14।।",
    "transliteration": "satataṁ kīrtayanto māṁ\nyatantaś ca dṛḍha-vratāḥ\nnamasyantaś ca māṁ bhaktyā\nnitya-yuktā upāsate",
    "english": "9.14 Always chanting My glories, endeavoring with great determination, bowing down before Me, these great souls perpetually worship Me with devotion.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-070",
    "chapter": 9,
    "verse": 22,
    "reference": "9.22",
    "audioSrc": "/audio/9.22.mp3",
    "sanskrit": "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते।\n\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्।।9.22।।",
    "tamil": "அநந்யாஶ்சிந்தயந்தோ மாம் யே ஜநாஃ பர்யுபாஸதே।\n\nதேஷாம் நித்யாபியுக்தாநாம் யோகக்ஷேமம் வஹாம்யஹம்।।9.22।।",
    "transliteration": "ananyāś cintayanto māṁ\nye janāḥ paryupāsate\nteṣāṁ nityābhiyuktānāṁ\nyoga-kṣemaṁ vahāmy aham",
    "english": "9.22 But those who worship Me with devotion, meditating on My transcendental form—to them I carry what they lack and preserve what they have.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-071",
    "chapter": 9,
    "verse": 25,
    "reference": "9.25",
    "audioSrc": "/audio/9.25.mp3",
    "sanskrit": "यान्ति देवव्रता देवान् पितृ़न्यान्ति पितृव्रताः।\n\nभूतानि यान्ति भूतेज्या यान्ति मद्याजिनोऽपि माम्।।9.25।।",
    "tamil": "யாந்தி தேவவ்ரதா தேவாந் பிதிரு़ந்யாந்தி பிதிருவ்ரதாஃ।\n\nபூதாநி யாந்தி பூதேஜ்யா யாந்தி மத்யாஜிநோ'பி மாம்।।9.25।।",
    "transliteration": "yānti deva-vratā devān\npitṝn yānti pitṛ-vratāḥ\nbhūtāni yānti bhūtejyā\nyānti mad-yājino ’pi mām",
    "english": "9.25 Those who worship the demigods will take birth among the demigods; those who worship ghosts and spirits will take birth among such beings; those who worship ancestors go to the ancestors; and those who worship Me will live with Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-072",
    "chapter": 9,
    "verse": 26,
    "reference": "9.26",
    "audioSrc": "/audio/9.26.mp3",
    "sanskrit": "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति।\n\nतदहं भक्त्युपहृतमश्नामि प्रयतात्मनः।।9.26।।",
    "tamil": "பத்ரம் புஷ்பம் பலம் தோயம் யோ மே பக்த்யா ப்ரயச்சதி।\n\nததஹம் பக்த்யுபஹிருதமஶ்நாமி ப்ரயதாத்மநஃ।।9.26।।",
    "transliteration": "patraṁ puṣpaṁ phalaṁ toyaṁ\nyo me bhaktyā prayacchati\ntad ahaṁ bhakty-upahṛtam\naśnāmi prayatātmanaḥ",
    "english": "9.26 If one offers Me with love and devotion a leaf, a flower, fruit or water, I will accept it.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-073",
    "chapter": 9,
    "verse": 27,
    "reference": "9.27",
    "audioSrc": "/audio/9.27.mp3",
    "sanskrit": "यत्करोषि यदश्नासि यज्जुहोषि ददासि यत्।\n\nयत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम्।।9.27।।",
    "tamil": "யத்கரோஷி யதஶ்நாஸி யஜ்ஜுஹோஷி ததாஸி யத்।\n\nயத்தபஸ்யஸி கௌந்தேய தத்குருஷ்வ மதர்பணம்।।9.27।।",
    "transliteration": "yat karoṣi yad aśnāsi\nyaj juhoṣi dadāsi yat\nyat tapasyasi kaunteya\ntat kuruṣva mad-arpaṇam",
    "english": "9.27 O son of Kuntī, all that you do, all that you eat, all that you offer and give away, as well as all austerities that you may perform, should be done as an offering unto Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-074",
    "chapter": 9,
    "verse": 29,
    "reference": "9.29",
    "audioSrc": "/audio/9.29.mp3",
    "sanskrit": "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः।\n\nये भजन्ति तु मां भक्त्या मयि ते तेषु चाप्यहम्।।9.29।।",
    "tamil": "ஸமோ'ஹம் ஸர்வபூதேஷு ந மே த்வேஷ்யோ'ஸ்தி ந ப்ரியஃ।\n\nயே பஜந்தி து மாம் பக்த்யா மயி தே தேஷு சாப்யஹம்।।9.29।।",
    "transliteration": "samo ’haṁ sarva-bhūteṣu\nna me dveṣyo ’sti na priyaḥ\nye bhajanti tu māṁ bhaktyā\nmayi te teṣu cāpy aham",
    "english": "9.29 I envy no one, nor am I partial to anyone. I am equal to all. But whoever renders service unto Me in devotion is a friend, is in Me, and I am also a friend to him.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-075",
    "chapter": 9,
    "verse": 30,
    "reference": "9.30",
    "audioSrc": "/audio/9.30.mp3",
    "sanskrit": "अपि चेत्सुदुराचारो भजते मामनन्यभाक्।\n\nसाधुरेव स मन्तव्यः सम्यग्व्यवसितो हि सः।।9.30।।",
    "tamil": "அபி சேத்ஸுதுராசாரோ பஜதே மாமநந்யபாக்।\n\nஸாதுரேவ ஸ மந்தவ்யஃ ஸம்யக்வ்யவஸிதோ ஹி ஸஃ।।9.30।।",
    "transliteration": "api cet su-durācāro\nbhajate mām ananya-bhāk\nsādhur eva sa mantavyaḥ\nsamyag vyavasito hi saḥ",
    "english": "9.30 Even if one commits the most abominable actions, if he is engaged in devotional service, he is to be considered saintly because he is properly situated.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-076",
    "chapter": 9,
    "verse": 32,
    "reference": "9.32",
    "audioSrc": "/audio/9.32.mp3",
    "sanskrit": "मां हि पार्थ व्यपाश्रित्य येऽपि स्युः पापयोनयः।\n\nस्त्रियो वैश्यास्तथा शूद्रास्तेऽपि यान्ति परां गतिम्।।9.32।।",
    "tamil": "மாம் ஹி பார்த வ்யபாஶ்ரித்ய யே'பி ஸ்யுஃ பாபயோநயஃ।\n\nஸ்த்ரியோ வைஶ்யாஸ்ததா ஶூத்ராஸ்தே'பி யாந்தி பராம் கதிம்।।9.32।।",
    "transliteration": "māṁ hi pārtha vyapāśritya\nye ’pi syuḥ pāpa-yonayaḥ\nstriyo vaiśyās tathā śūdrās\nte ’pi yānti parāṁ gatim",
    "english": "9.32 O son of Pṛthā, those who take shelter in Me, though they be of lower birth—women, vaiśyas \\[merchants\\], as well as śūdras \\[workers\\]—can approach the supreme destination.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-077",
    "chapter": 9,
    "verse": 34,
    "reference": "9.34",
    "audioSrc": "/audio/9.34.mp3",
    "sanskrit": "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु।\n\nमामेवैष्यसि युक्त्वैवमात्मानं मत्परायणः।।9.34।।",
    "tamil": "மந்மநா பவ மத்பக்தோ மத்யாஜீ மாம் நமஸ்குரு।\n\nமாமேவைஷ்யஸி யுக்த்வைவமாத்மாநம் மத்பராயணஃ।।9.34।।",
    "transliteration": "man-manā bhava mad-bhakto\nmad-yājī māṁ namaskuru\nmām evaiṣyasi yuktvaivam\nātmānaṁ mat-parāyaṇaḥ",
    "english": "9.34 Engage your mind always in thinking of Me, offer obeisances and worship Me. Being completely absorbed in Me, surely you will come to Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-078",
    "chapter": 10,
    "verse": 8,
    "reference": "10.8",
    "audioSrc": "/audio/10.8.mp3",
    "sanskrit": "अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते।\n\nइति मत्वा भजन्ते मां बुधा भावसमन्विताः।।10.8।।",
    "tamil": "அஹம் ஸர்வஸ்ய ப்ரபவோ மத்தஃ ஸர்வம் ப்ரவர்ததே।\n\nஇதி மத்வா பஜந்தே மாம் புதா பாவஸமந்விதாஃ।।10.8।।",
    "transliteration": "ahaṁ sarvasya prabhavo\nmattaḥ sarvaṁ pravartate\niti matvā bhajante māṁ\nbudhā bhāva-samanvitāḥ",
    "english": "10.8 I am the source of all spiritual and material worlds. Everything emanates from Me. The wise who know this perfectly engage in My devotional service and worship Me with all their hearts.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-079",
    "chapter": 10,
    "verse": 9,
    "reference": "10.9",
    "audioSrc": "/audio/10.9.mp3",
    "sanskrit": "मच्चित्ता मद्गतप्राणा बोधयन्तः परस्परम्।\n\nकथयन्तश्च मां नित्यं तुष्यन्ति च रमन्ति च।।10.9।।",
    "tamil": "மச்சித்தா மத்கதப்ராணா போதயந்தஃ பரஸ்பரம்।\n\nகதயந்தஶ்ச மாம் நித்யம் துஷ்யந்தி ச ரமந்தி ச।।10.9।।",
    "transliteration": "mac-cittā mad-gata-prāṇā\nbodhayantaḥ parasparam\nkathayantaś ca māṁ nityaṁ\ntuṣyanti ca ramanti ca",
    "english": "10.9 The thoughts of My pure devotees dwell in Me, their lives are surrendered to Me, and they derive great satisfaction and bliss enlightening one another and conversing about Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-080",
    "chapter": 10,
    "verse": 10,
    "reference": "10.10",
    "audioSrc": "/audio/10.10.mp3",
    "sanskrit": "तेषां सततयुक्तानां भजतां प्रीतिपूर्वकम्।\n\nददामि बुद्धियोगं तं येन मामुपयान्ति ते।।10.10।।",
    "tamil": "தேஷாம் ஸததயுக்தாநாம் பஜதாம் ப்ரீதிபூர்வகம்।\n\nததாமி புத்தியோகம் தம் யேந மாமுபயாந்தி தே।।10.10।।",
    "transliteration": "teṣāṁ satata-yuktānāṁ\nbhajatāṁ prīti-pūrvakam\ndadāmi buddhi-yogaṁ taṁ\nyena mām upayānti te",
    "english": "10.10 To those who are constantly devoted and worship Me with love, I give the understanding by which they can come to Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-081",
    "chapter": 10,
    "verse": 11,
    "reference": "10.11",
    "audioSrc": "/audio/10.11.mp3",
    "sanskrit": "तेषामेवानुकम्पार्थमहमज्ञानजं तमः।\n\nनाशयाम्यात्मभावस्थो ज्ञानदीपेन भास्वता।।10.11।।",
    "tamil": "தேஷாமேவாநுகம்பார்தமஹமஜ்ஞாநஜம் தமஃ।\n\nநாஶயாம்யாத்மபாவஸ்தோ ஜ்ஞாநதீபேந பாஸ்வதா।।10.11।।",
    "transliteration": "teṣām evānukampārtham\naham ajñāna-jaṁ tamaḥ\nnāśayāmy ātma-bhāva-stho\njñāna-dīpena bhāsvatā",
    "english": "10.11 Out of compassion for them, I, dwelling in their hearts, destroy with the shining lamp of knowledge the darkness born of ignorance.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-082",
    "chapter": 10,
    "verse": 12,
    "reference": "10.12-13",
    "audioSrc": "/audio/10.12.mp3",
    "sanskrit": "अर्जुन उवाच\n\nपरं ब्रह्म परं धाम पवित्रं परमं भवान्।\n\nपुरुषं शाश्वतं दिव्यमादिदेवमजं विभुम्।।10.12।।\n\nआहुस्त्वामृषयः सर्वे देवर्षिर्नारदस्तथा।\n\nअसितो देवलो व्यासः स्वयं चैव ब्रवीषि मे।।10.13।।",
    "tamil": "அர்ஜுந உவாச\n\nபரம் ப்ரஹ்ம பரம் தாம பவித்ரம் பரமம் பவாந்।\n\nபுருஷம் ஶாஶ்வதம் திவ்யமாதிதேவமஜம் விபும்।।10.12।।\n\nஆஹுஸ்த்வாமிருஷயஃ ஸர்வே தேவர்ஷிர்நாரதஸ்ததா।\n\nஅஸிதோ தேவலோ வ்யாஸஃ ஸ்வயம் சைவ ப்ரவீஷி மே।।10.13।।",
    "transliteration": "arjuna uvāca\nparaṁ brahma paraṁ dhāma\npavitraṁ paramaṁ bhavān\npuruṣaṁ śāśvataṁ divyam\nādi-devam ajaṁ vibhum\n\nāhus tvām ṛṣayaḥ sarve\ndevarṣir nāradas tathā\nasito devalo vyāsaḥ\nsvayaṁ caiva bravīṣi me",
    "english": "10.12-13 Arjuna said: You are the Supreme Personality of Godhead, the ultimate abode, the purest, the Absolute Truth. You are the eternal, transcendental, original person, the unborn, the greatest. All the great sages such as Narada, Asita, Devala and Vyasa confirm this truth about You, and now You Yourself are declaring it to me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-083",
    "chapter": 10,
    "verse": 41,
    "reference": "10.41",
    "audioSrc": "/audio/10.41.mp3",
    "sanskrit": "यद्यद्विभूतिमत्सत्त्वं श्रीमदूर्जितमेव वा।\n\nतत्तदेवावगच्छ त्वं मम तेजोंऽशसंभवम्।।10.41।।",
    "tamil": "யத்யத்விபூதிமத்ஸத்த்வம் ஶ்ரீமதூர்ஜிதமேவ வா।\n\nதத்ததேவாவகச்ச த்வம் மம தேஜோம்'ஶஸம்பவம்।।10.41।।",
    "transliteration": "yad yad vibhūtimat sattvaṁ\nśrīmad ūrjitam eva vā\ntat tad evāvagaccha tvaṁ\nmama tejo-’ṁśa-sambhavam",
    "english": "10.41 Know that all beautiful, glorious, and mighty creations spring from but a spark of My splendor.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-084",
    "chapter": 11,
    "verse": 54,
    "reference": "11.54",
    "audioSrc": "/audio/11.54.mp3",
    "sanskrit": "भक्त्या त्वनन्यया शक्यमहमेवंविधोऽर्जुन।\n\nज्ञातुं दृष्टुं च तत्त्वेन प्रवेष्टुं च परंतप।।11.54।।",
    "tamil": "பக்த்யா த்வநந்யயா ஶக்யமஹமேவம்விதோ'ர்ஜுந।\n\nஜ்ஞாதும் திருஷ்டும் ச தத்த்வேந ப்ரவேஷ்டும் ச பரம்தப।।11.54।।",
    "transliteration": "bhaktyā tv ananyayā śakya\naham evaṁ-vidho ’rjuna\njñātuṁ draṣṭuṁ ca tattvena\npraveṣṭuṁ ca parantapa",
    "english": "11.54 My dear Arjuna, only by undivided devotional service can I be understood as I am, standing before you, and can thus be seen directly. Only in this way can you enter into the mysteries of My understanding.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-085",
    "chapter": 11,
    "verse": 55,
    "reference": "11.55",
    "audioSrc": "/audio/11.55.mp3",
    "sanskrit": "मत्कर्मकृन्मत्परमो मद्भक्तः सङ्गवर्जितः।\n\nनिर्वैरः सर्वभूतेषु यः स मामेति पाण्डव।।11.55।।",
    "tamil": "மத்கர்மகிருந்மத்பரமோ மத்பக்தஃ ஸங்கவர்ஜிதஃ।\n\nநிர்வைரஃ ஸர்வபூதேஷு யஃ ஸ மாமேதி பாண்டவ।।11.55।।",
    "transliteration": "mat-karma-kṛn mat-paramo\nmad-bhaktaḥ saṅga-varjitaḥ\nnirvairaḥ sarva-bhūteṣu\nyaḥ sa mām eti pāṇḍava",
    "english": "11.55 My dear Arjuna, one who is engaged in My pure devotional service, free from the contaminations of previous activities and from mental speculation, who is friendly to every living entity, certainly comes to Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-086",
    "chapter": 12,
    "verse": 5,
    "reference": "12.5",
    "audioSrc": "/audio/12.5.mp3",
    "sanskrit": "क्लेशोऽधिकतरस्तेषामव्यक्तासक्तचेतसाम्।\n\nअव्यक्ता हि गतिर्दुःखं देहवद्भिरवाप्यते।।12.5।।",
    "tamil": "க்லேஶோ'திகதரஸ்தேஷாமவ்யக்தாஸக்தசேதஸாம்।\n\nஅவ்யக்தா ஹி கதிர்துஃகம் தேஹவத்பிரவாப்யதே।।12.5।।",
    "transliteration": "kleśo ’dhikataras teṣām\navyaktāsakta-cetasām\navyaktā hi gatir duḥkhaṁ\ndehavadbhir avāpyate",
    "english": "12.5 For those whose minds are attached to the unmanifested, impersonal feature of the Supreme, advancement is very troublesome. To make progrese in that discipline is always difficult for those who are embodied.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-087",
    "chapter": 12,
    "verse": 8,
    "reference": "12.8",
    "audioSrc": "/audio/12.8.mp3",
    "sanskrit": "मय्येव मन आधत्स्व मयि बुद्धिं निवेशय।निवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः।।12.8।।",
    "tamil": "மய்யேவ மந ஆதத்ஸ்வ மயி புத்திம் நிவேஶய।நிவஸிஷ்யஸி மய்யேவ அத ஊர்த்வம் ந ஸம்ஶயஃ।।12.8।।",
    "transliteration": "mayy eva mana ādhatsva\nmayi buddhiṁ niveśaya\nnivasiṣyasi mayy eva\nata ūrdhvaṁ na saṁśayaḥ",
    "english": "12.8 Just fix your mind upon Me, the Supreme Personality of Godhead, and engage all your intelligence in Me. Thus you will live in Me always, without a doubt.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-088",
    "chapter": 12,
    "verse": 9,
    "reference": "12.9",
    "audioSrc": "/audio/12.9.mp3",
    "sanskrit": "अथ चित्तं समाधातुं न शक्नोषि मयि स्थिरम्।अभ्यासयोगेन ततो मामिच्छाप्तुं धनञ्जय।।12.9।।",
    "tamil": "அத சித்தம் ஸமாதாதும் ந ஶக்நோஷி மயி ஸ்திரம்।அப்யாஸயோகேந ததோ மாமிச்சாப்தும் தநஞ்ஜய।।12.9।।",
    "transliteration": "atha cittaṁ samādhātuṁ\nna śaknoṣi mayi sthiram\nabhyāsa-yogena tato\nmām icchāptuṁ dhanañjaya",
    "english": "12.9 My dear Arjuna, O winner of wealth, if you cannot fix your mind upon Me without deviation, then follow the regulated principles of bhakti-yoga In this way you will develop a desire to attain to Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-089",
    "chapter": 12,
    "verse": 10,
    "reference": "12.10",
    "sanskrit": "अभ्यासेऽप्यसमर्थोऽसि मत्कर्मपरमो भव।मदर्थमपि कर्माणि कुर्वन् सिद्धिमवाप्स्यसि।।12.10।।",
    "tamil": "அப்யாஸே'ப்யஸமர்தோ'ஸி மத்கர்மபரமோ பவ।மதர்தமபி கர்மாணி குர்வந் ஸித்திமவாப்ஸ்யஸி।।12.10।।",
    "transliteration": "abhyāse ’py asamartho ’si\nmat-karma-paramo bhava\nmad-artham api karmāṇi\nkurvan siddhim avāpsyasi",
    "english": "12.10 If you cannot practice the regulations of bhakti-yoga, then just try to work for Me, because by working for Me you will come to the perfect stage.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-090",
    "chapter": 14,
    "verse": 4,
    "reference": "14.4",
    "audioSrc": "/audio/14.4.mp3",
    "sanskrit": "सर्वयोनिषु कौन्तेय मूर्तयः सम्भवन्ति याः।तासां ब्रह्म महद्योनिरहं बीजप्रदः पिता।।14.4।।",
    "tamil": "ஸர்வயோநிஷு கௌந்தேய மூர்தயஃ ஸம்பவந்தி யாஃ।தாஸாம் ப்ரஹ்ம மஹத்யோநிரஹம் பீஜப்ரதஃ பிதா।।14.4।।",
    "transliteration": "sarva-yoniṣu kaunteya\nmūrtayaḥ sambhavanti yāḥ\ntāsāṁ brahma mahad yonir\nahaṁ bīja-pradaḥ pitā",
    "english": "14.4 It should be understood that all species of life, O son of Kuntī, are made possible by birth in this material nature, and that I am the seed-giving father.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-091",
    "chapter": 14,
    "verse": 26,
    "reference": "14.26",
    "audioSrc": "/audio/14.26.mp3",
    "sanskrit": "मां च योऽव्यभिचारेण भक्ितयोगेन सेवते।स गुणान्समतीत्यैतान् ब्रह्मभूयाय कल्पते।।14.26।।",
    "tamil": "மாம் ச யோ'வ்யபிசாரேண பக்ிதயோகேந ஸேவதே।ஸ குணாந்ஸமதீத்யைதாந் ப்ரஹ்மபூயாய கல்பதே।।14.26।।",
    "transliteration": "māṁ ca yo ’vyabhicāreṇa\nbhakti-yogena sevate\nsa guṇān samatītyaitān\nbrahma-bhūyāya kalpate",
    "english": "14.26 One who engages in full devotional service, who does not fall down in any circumstance, at once transcends the modes of material nature and thus comes to the level of Brahman.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-092",
    "chapter": 14,
    "verse": 27,
    "reference": "14.27",
    "audioSrc": "/audio/14.27.mp3",
    "sanskrit": "ब्रह्मणो हि प्रतिष्ठाऽहममृतस्याव्ययस्य च।शाश्वतस्य च धर्मस्य सुखस्यैकान्तिकस्य च।।14.27।।",
    "tamil": "ப்ரஹ்மணோ ஹி ப்ரதிஷ்டா'ஹமமிருதஸ்யாவ்யயஸ்ய ச।ஶாஶ்வதஸ்ய ச தர்மஸ்ய ஸுகஸ்யைகாந்திகஸ்ய ச।।14.27।।",
    "transliteration": "brahmaṇo hi pratiṣṭhāham\namṛtasyāvyayasya ca\nśāśvatasya ca dharmasya\nsukhasyaikāntikasya ca",
    "english": "14.27 And I am the basis of the impersonal Brahman, which is the constitutional position of ultimate happiness, and which is immortal, imperishable and eternal.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-093",
    "chapter": 15,
    "verse": 5,
    "reference": "15.5",
    "audioSrc": "/audio/15.5.mp3",
    "sanskrit": "निर्मानमोहा जितसङ्गदोषा    अध्यात्मनित्या विनिवृत्तकामाः।द्वन्द्वैर्विमुक्ताः सुखदुःखसंज्ञै    र्गच्छन्त्यमूढाः पदमव्ययं तत्।।15.5।।",
    "tamil": "நிர்மாநமோஹா ஜிதஸங்கதோஷா    அத்யாத்மநித்யா விநிவிருத்தகாமாஃ।த்வந்த்வைர்விமுக்தாஃ ஸுகதுஃகஸம்ஜ்ஞை    ர்கச்சந்த்யமூடாஃ பதமவ்யயம் தத்।।15.5।।",
    "transliteration": "nirmāna-mohā jita-saṅga-doṣā\nadhyātma-nityā vinivṛtta-kāmāḥ\ndvandvair vimuktāḥ sukha-duḥkha-saṁjñair\ngacchanty amūḍhāḥ padam avyayaṁ tat",
    "english": "15.5 One who is free from illusion, false prestige, and false association, who understands the eternal, who is done with material lust and is freed from the duality of happiness and distress, and who knows how to surrender unto the Supreme Person, attains to that eternal kingdom.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-094",
    "chapter": 15,
    "verse": 6,
    "reference": "15.6",
    "audioSrc": "/audio/15.6.mp3",
    "sanskrit": "न तद्भासयते सूर्यो न शशाङ्को न पावकः।यद्गत्वा न निवर्तन्ते तद्धाम परमं मम।।15.6।।",
    "tamil": "ந தத்பாஸயதே ஸூர்யோ ந ஶஶாங்கோ ந பாவகஃ।யத்கத்வா ந நிவர்தந்தே தத்தாம பரமம் மம।।15.6।।",
    "transliteration": "na tad bhāsayate sūryo\nna śaśāṅko na pāvakaḥ\nyad gatvā na nivartante\ntad dhāma paramaṁ mama",
    "english": "15.6 That abode of Mine is not illumined by the sun or moon, nor by electricity. One who reaches it never returns to this material world.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-095",
    "chapter": 15,
    "verse": 7,
    "reference": "15.7",
    "audioSrc": "/audio/15.7.mp3",
    "sanskrit": "ममैवांशो जीवलोके जीवभूतः सनातनः।मनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति।।15.7।।",
    "tamil": "மமைவாம்ஶோ ஜீவலோகே ஜீவபூதஃ ஸநாதநஃ।மநஃஷஷ்டாநீந்த்ரியாணி ப்ரகிருதிஸ்தாநி கர்ஷதி।।15.7।।",
    "transliteration": "mamaivāṁśo jīva-loke\njīva-bhūtaḥ sanātanaḥ\nmanaḥ-ṣaṣṭhānīndriyāṇi\nprakṛti-sthāni karṣati",
    "english": "15.7 The living entities in this conditioned world are My eternal, fragmental parts. Due to conditioned life, they are struggling very hard with the six senses, which include the mind.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-096",
    "chapter": 15,
    "verse": 15,
    "reference": "15.15",
    "audioSrc": "/audio/15.15.mp3",
    "sanskrit": "सर्वस्य चाहं हृदि सन्निविष्टो    मत्तः स्मृतिर्ज्ञानमपोहनं च।वेदैश्च सर्वैरहमेव वेद्यो    वेदान्तकृद्वेदविदेव चाहम्।।15.15।।",
    "tamil": "ஸர்வஸ்ய சாஹம் ஹிருதி ஸந்நிவிஷ்டோ    மத்தஃ ஸ்மிருதிர்ஜ்ஞாநமபோஹநம் ச।வேதைஶ்ச ஸர்வைரஹமேவ வேத்யோ    வேதாந்தகிருத்வேதவிதேவ சாஹம்।।15.15।।",
    "transliteration": "sarvasya cāhaṁ hṛdi sanniviṣṭo\nmattaḥ smṛtir jñānam apohanaṁ ca\nvedaiś ca sarvair aham eva vedyo\nvedānta-kṛd veda-vid eva cāham",
    "english": "15.15 I am seated in everyone’s heart, and from Me come remembrance, knowledge and forgetfulness. By all the Vedas am I to be known; indeed I am the compiler of Vedānta, and I am the knower of the Vedas.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-097",
    "chapter": 15,
    "verse": 19,
    "reference": "15.19",
    "audioSrc": "/audio/15.19.mp3",
    "sanskrit": "यो मामेवमसम्मूढो जानाति पुरुषोत्तमम्।स सर्वविद्भजति मां सर्वभावेन भारत।।15.19।।",
    "tamil": "யோ மாமேவமஸம்மூடோ ஜாநாதி புருஷோத்தமம்।ஸ ஸர்வவித்பஜதி மாம் ஸர்வபாவேந பாரத।।15.19।।",
    "transliteration": "yo mām evam asammūḍho\njānāti puruṣottamam\nsa sarva-vid bhajati māṁ\nsarva-bhāvena bhārata",
    "english": "15.19 Whoever knows Me as the Supreme Personality of Godhead, without doubting, is to be understood as the knower of everything, and he therefore engages himself in full devotional service, O son of Bharata",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-098",
    "chapter": 18,
    "verse": 42,
    "reference": "18.42",
    "audioSrc": "/audio/18.42.mp3",
    "sanskrit": "शमो दमस्तपः शौचं क्षान्तिरार्जवमेव च।ज्ञानं विज्ञानमास्तिक्यं ब्रह्मकर्म स्वभावजम्।।18.42।।",
    "tamil": "ஶமோ தமஸ்தபஃ ஶௌசம் க்ஷாந்திரார்ஜவமேவ ச।ஜ்ஞாநம் விஜ்ஞாநமாஸ்திக்யம் ப்ரஹ்மகர்ம ஸ்வபாவஜம்।।18.42।।",
    "transliteration": "śamo damas tapaḥ śaucaṁ\nkṣāntir ārjavam eva ca\njñānaṁ vijñānam āstikyaṁ\nbrahma-karma svabhāva-jam",
    "english": "18.42 Peacefulness, self-control, austerity, purity, tolerance, honesty, wisdom, knowledge, and religiousness—these are the qualities by which the brāhmaṇas work.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-099",
    "chapter": 18,
    "verse": 54,
    "reference": "18.54",
    "audioSrc": "/audio/18.54.mp3",
    "sanskrit": "ब्रह्मभूतः प्रसन्नात्मा न शोचति न काङ्क्षति।समः सर्वेषु भूतेषु मद्भक्तिं लभते पराम्।।18.54।।",
    "tamil": "ப்ரஹ்மபூதஃ ப்ரஸந்நாத்மா ந ஶோசதி ந காங்க்ஷதி।ஸமஃ ஸர்வேஷு பூதேஷு மத்பக்திம் லபதே பராம்।।18.54।।",
    "transliteration": "brahma-bhūtaḥ prasannātmā\nna śocati na kāṅkṣati\nsamaḥ sarveṣu bhūteṣu\nmad-bhaktiṁ labhate parām",
    "english": "18.54 One who is thus transcendentally situated at once realizes the Supreme Brahman. He never laments nor desires to have anything; he is equally disposed to every living entity. In that state he attains pure devotional service unto Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-100",
    "chapter": 18,
    "verse": 55,
    "reference": "18.55",
    "audioSrc": "/audio/18.55.mp3",
    "sanskrit": "भक्त्या मामभिजानाति यावान्यश्चास्मि तत्त्वतः।ततो मां तत्त्वतो ज्ञात्वा विशते तदनन्तरम्।।18.55।।",
    "tamil": "பக்த்யா மாமபிஜாநாதி யாவாந்யஶ்சாஸ்மி தத்த்வதஃ।ததோ மாம் தத்த்வதோ ஜ்ஞாத்வா விஶதே ததநந்தரம்।।18.55।।",
    "transliteration": "bhaktyā mām abhijānāti\nyāvān yaś cāsmi tattvataḥ\ntato māṁ tattvato jñātvā\nviśate tad-anantaram",
    "english": "18.55 One can understand the Supreme Personality as He is only by devotional service. And when one is in full consciousness of the Supreme Lord by such devotion, he can enter into the kingdom of God.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-101",
    "chapter": 18,
    "verse": 58,
    "reference": "18.58",
    "audioSrc": "/audio/18.58.mp3",
    "sanskrit": "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि।अथ चेत्त्वमहङ्कारान्न श्रोष्यसि विनङ्क्ष्यसि।।18.58।।",
    "tamil": "மச்சித்தஃ ஸர்வதுர்காணி மத்ப்ரஸாதாத்தரிஷ்யஸி।அத சேத்த்வமஹங்காராந்ந ஶ்ரோஷ்யஸி விநங்க்ஷ்யஸி।।18.58।।",
    "transliteration": "mac-cittaḥ sarva-durgāṇi\nmat-prasādāt tariṣyasi\natha cet tvam ahaṅkārān\nna śroṣyasi vinaṅkṣyasi",
    "english": "18.58 If you become conscious of Me, you will pass over all the obstacles of conditional life by My grace. If, however, you do not work in such consciousness but act through false ego, not hearing Me, you will be lost.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-102",
    "chapter": 18,
    "verse": 61,
    "reference": "18.61",
    "audioSrc": "/audio/18.61.mp3",
    "sanskrit": "ईश्वरः सर्वभूतानां हृद्देशेऽर्जुन तिष्ठति।भ्रामयन्सर्वभूतानि यन्त्रारूढानि मायया।।18.61।।",
    "tamil": "ஈஶ்வரஃ ஸர்வபூதாநாம் ஹிருத்தேஶே'ர்ஜுந திஷ்டதி।ப்ராமயந்ஸர்வபூதாநி யந்த்ராரூடாநி மாயயா।।18.61।।",
    "transliteration": "īśvaraḥ sarva-bhūtānāṁ\nhṛd-deśe ’rjuna tiṣṭhati\nbhrāmayan sarva-bhūtāni\nyantrārūḍhāni māyayā",
    "english": "18.61 The Supreme Lord is situated in everyone’s heart, O Arjuna, and is directing the wanderings of all living entities, who are seated as on a machine, made of the material energy.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-103",
    "chapter": 18,
    "verse": 65,
    "reference": "18.65",
    "audioSrc": "/audio/18.65.mp3",
    "sanskrit": "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु।मामेवैष्यसि सत्यं ते प्रतिजाने प्रियोऽसि मे।।18.65।।",
    "tamil": "மந்மநா பவ மத்பக்தோ மத்யாஜீ மாம் நமஸ்குரு।மாமேவைஷ்யஸி ஸத்யம் தே ப்ரதிஜாநே ப்ரியோ'ஸி மே।।18.65।।",
    "transliteration": "man-manā bhava mad-bhakto\nmad-yājī māṁ namaskuru\nmām evaiṣyasi satyaṁ te\npratijāne priyo ’si me",
    "english": "18.65 Always think of Me and become My devotee. Worship Me and offer your homage unto Me. Thus you will come to Me without fail. I promise you this because you are My very dear friend.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-104",
    "chapter": 18,
    "verse": 66,
    "reference": "18.66",
    "audioSrc": "/audio/18.66.mp3",
    "sanskrit": "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज।अहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः।।18.66।।",
    "tamil": "ஸர்வதர்மாந்பரித்யஜ்ய மாமேகம் ஶரணம் வ்ரஜ।அஹம் த்வா ஸர்வபாபேப்யோ மோக்ஷயிஷ்யாமி மா ஶுசஃ।।18.66।।",
    "transliteration": "sarva-dharmān parityajya\nmām ekaṁ śaraṇaṁ vraja\nahaṁ tvāṁ sarva-pāpebhyo\nmokṣayiṣyāmi mā śucaḥ",
    "english": "18.66 Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reaction. Do not fear.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-105",
    "chapter": 18,
    "verse": 68,
    "reference": "18.68",
    "audioSrc": "/audio/18.68.mp3",
    "sanskrit": "य इमं परमं गुह्यं मद्भक्तेष्वभिधास्यति।भक्ितं मयि परां कृत्वा मामेवैष्यत्यसंशयः।।18.68।।",
    "tamil": "ய இமம் பரமம் குஹ்யம் மத்பக்தேஷ்வபிதாஸ்யதி।பக்ிதம் மயி பராம் கிருத்வா மாமேவைஷ்யத்யஸம்ஶயஃ।।18.68।।",
    "transliteration": "ya idaṁ paramaṁ guhyaṁ\nmad-bhakteṣv abhidhāsyati\nbhaktiṁ mayi parāṁ kṛtvā\nmām evaiṣyaty asaṁśayaḥ",
    "english": "18.68 For one who explains the supreme secret to the devotees, devotional service is guaranteed, and at the end he will come back to Me.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-106",
    "chapter": 18,
    "verse": 69,
    "reference": "18.69",
    "audioSrc": "/audio/18.69.mp3",
    "sanskrit": "न च तस्मान्मनुष्येषु कश्िचन्मे प्रियकृत्तमः।भविता न च मे तस्मादन्यः प्रियतरो भुवि।।18.69।।",
    "tamil": "ந ச தஸ்மாந்மநுஷ்யேஷு கஶ்ிசந்மே ப்ரியகிருத்தமஃ।பவிதா ந ச மே தஸ்மாதந்யஃ ப்ரியதரோ புவி।।18.69।।",
    "transliteration": "na ca tasmān manuṣyeṣu\nkaścin me priya-kṛttamaḥ\nbhavitā na ca me tasmād\nanyaḥ priyataro bhuvi",
    "english": "18.69 There is no servant in this world more dear to Me than he, nor will there ever be one more dear.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-107",
    "chapter": 18,
    "verse": 78,
    "reference": "18.78",
    "audioSrc": "/audio/18.78.mp3",
    "sanskrit": "यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः।\n\nतत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम।।18.78।",
    "tamil": "யத்ர யோகேஶ்வரஃ கிருஷ்ணோ யத்ர பார்தோ தநுர்தரஃ।\n\nதத்ர ஶ்ரீர்விஜயோ பூதிர்த்ருவா நீதிர்மதிர்மம।।18.78।",
    "transliteration": "yatra yogeśvaraḥ kṛṣṇo\nyatra pārtho dhanur-dharaḥ\ntatra śrīr vijayo bhūtir\ndhruvā nītir matir mama",
    "english": "18.78 Wherever there is Kṛṣṇa, the master of all mystics, and wherever there is Arjuna, the supreme archer, there will also certainly be opulence, victory, extraordinary power, and morality. That is my opinion.",
    "translationAuthor": "A.C. Bhaktivedanta Swami Prabhupada",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  }
];

export const TOTAL_SHLOKAS = SHLOKAS.length;
export const DAILY_TARGET = 2;
export const JOURNEY_DAYS = TOTAL_SHLOKAS / DAILY_TARGET;
