export type LoopStep = "listen" | "repeat" | "understand" | "recall";

export type Shloka = {
  id: string;
  chapter: number;
  verse: number;
  reference: string;
  sanskrit: string;
  transliteration: string;
  english: string;
  translationAuthor: string;
  reflectionPrompt: string;
};

export const SHLOKA_SOURCE = "https://github.com/gita/gita";

export const SHLOKAS: Shloka[] = [
  {
    "id": "GS-001",
    "chapter": 1,
    "verse": 1,
    "reference": "1.1",
    "sanskrit": "धृतराष्ट्र उवाच\n\nधर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः।\n\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय",
    "transliteration": "dhṛitarāśhtra uvācha\ndharma-kṣhetre kuru-kṣhetre samavetā yuyutsavaḥ\nmāmakāḥ pāṇḍavāśhchaiva kimakurvata sañjaya",
    "english": "Dhṛtarāṣṭra said: “O Sanjaya, what did my people and the Pāṇḍavas do, gathered together on the holy field of Kurukshetra, eager for battle?”",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-002",
    "chapter": 1,
    "verse": 28,
    "reference": "1.28",
    "sanskrit": "अर्जुन उवाच\n\nकृपया परयाऽऽविष्टो विषीदन्निदमब्रवीत्।\n\nदृष्ट्वेमं स्वजनं कृष्ण युयुत्सुं समुपस्थितम्",
    "transliteration": "arjuna uvācha\ndṛiṣhṭvemaṁ sva-janaṁ kṛiṣhṇa yuyutsuṁ samupasthitam",
    "english": "He was filled with deep compassion and said these words in despair:",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-003",
    "chapter": 1,
    "verse": 29,
    "reference": "1.29",
    "sanskrit": "सीदन्ति मम गात्राणि मुखं च परिशुष्यति।\n\nवेपथुश्च शरीरे मे रोमहर्षश्च जायते",
    "transliteration": "sīdanti mama gātrāṇi mukhaṁ cha pariśhuṣhyati\nvepathuśh cha śharīre me roma-harṣhaśh cha jāyate",
    "english": "My limbs have weakened, my mouth has become parched, my body is trembling, and my hairs are standing on end.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-004",
    "chapter": 1,
    "verse": 30,
    "reference": "1.30",
    "sanskrit": "गाण्डीवं स्रंसते हस्तात्त्वक्चैव परिदह्यते।\n\nन च शक्नोम्यवस्थातुं भ्रमतीव च मे मनः",
    "transliteration": "gāṇḍīvaṁ sraṁsate hastāt tvak chaiva paridahyate\nna cha śhaknomy avasthātuṁ bhramatīva cha me manaḥ",
    "english": "The bow Gandiva slips from my hand and my skin is burning. I can no longer stand. My mind seems to be reeling.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-005",
    "chapter": 1,
    "verse": 31,
    "reference": "1.31",
    "sanskrit": "निमित्तानि च पश्यामि विपरीतानि केशव।\n\nन च श्रेयोऽनुपश्यामि हत्वा स्वजनमाहवे",
    "transliteration": "nimittāni cha paśhyāmi viparītāni keśhava\nna cha śhreyo ’nupaśhyāmi hatvā sva-janam āhave",
    "english": "I see, Kṛṣṇa, inauspicious omens. I foresee no good in slaying my kinsmen in battle.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-006",
    "chapter": 1,
    "verse": 32,
    "reference": "1.32",
    "sanskrit": "न काङ्क्षे विजयं कृष्ण न च राज्यं सुखानि च।\n\nकिं नो राज्येन गोविन्द किं भोगैर्जीवितेन वा",
    "transliteration": "na kāṅkṣhe vijayaṁ kṛiṣhṇa na cha rājyaṁ sukhāni cha\nkiṁ no rājyena govinda kiṁ bhogair jīvitena vā",
    "english": "I desire no victory, nor empire, nor pleasures. What have we to do with empire, O Krishna, or enjoyment, or even life?",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-007",
    "chapter": 2,
    "verse": 2,
    "reference": "2.2",
    "sanskrit": "श्री भगवानुवाच\n\nकुतस्त्वा कश्मलमिदं विषमे समुपस्थितम्।\n\nअनार्यजुष्टमस्वर्ग्यमकीर्तिकरमर्जुन",
    "transliteration": "śhrī bhagavān uvācha\nkutastvā kaśhmalamidaṁ viṣhame samupasthitam\nanārya-juṣhṭamaswargyam akīrti-karam arjuna",
    "english": "The Lord said, \"Whence comes this despondency upon you, O Arjuna, in this crisis? It is unfitting for a noble person; it is disgraceful and it obstructs one's attainment of heaven.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-008",
    "chapter": 2,
    "verse": 3,
    "reference": "2.3",
    "sanskrit": "क्लैब्यं मा स्म गमः पार्थ नैतत्त्वय्युपपद्यते।\n\nक्षुद्रं हृदयदौर्बल्यं त्यक्त्वोत्तिष्ठ परन्तप",
    "transliteration": "klaibyaṁ mā sma gamaḥ pārtha naitat tvayyupapadyate\nkṣhudraṁ hṛidaya-daurbalyaṁ tyaktvottiṣhṭha parantapa",
    "english": "Do not yield to unmanliness, O Arjuna, it does not befit you. Shake off this base faint-heartedness and arise, O conqueror of foes!",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-009",
    "chapter": 2,
    "verse": 7,
    "reference": "2.7",
    "sanskrit": "कार्पण्यदोषोपहतस्वभावः\n\nपृच्छामि त्वां धर्मसंमूढचेताः।\n\nयच्छ्रेयः स्यान्निश्िचतं ब्रूहि तन्मे\n\nशिष्यस्तेऽहं शाधि मां त्वां प्रपन्नम्",
    "transliteration": "kārpaṇya-doṣhopahata-svabhāvaḥ\npṛichchhāmi tvāṁ dharma-sammūḍha-chetāḥ\nyach-chhreyaḥ syānniśhchitaṁ brūhi tanme\nśhiṣhyaste ’haṁ śhādhi māṁ tvāṁ prapannam",
    "english": "With my heart stricken by the fault of weak compassion, my mind perplexed about my duty, I implore you to tell me for certain what is good for me. I am your disciple; teach me, who have taken refuge in you.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-010",
    "chapter": 2,
    "verse": 11,
    "reference": "2.11",
    "sanskrit": "श्री भगवानुवाच\n\nअशोच्यानन्वशोचस्त्वं प्रज्ञावादांश्च भाषसे।\n\nगतासूनगतासूंश्च नानुशोचन्ति पण्डिताः",
    "transliteration": "śhrī bhagavān uvācha\naśhochyān-anvaśhochas-tvaṁ prajñā-vādānśh cha bhāṣhase\ngatāsūn-agatāsūnśh-cha nānuśhochanti paṇḍitāḥ",
    "english": "The Lord said, \"You grieve for those who should not be grieved for; yet you speak words of wisdom. The wise grieve neither for the dead nor for the living.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-011",
    "chapter": 2,
    "verse": 13,
    "reference": "2.13",
    "sanskrit": "देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा।\n\nतथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति",
    "transliteration": "dehino ’smin yathā dehe kaumāraṁ yauvanaṁ jarā\ntathā dehāntara-prāptir dhīras tatra na muhyati",
    "english": "Just as the self associated with a body passes through childhood, youth, and old age, so too, at death, it passes into another body. A wise man is not deluded by that.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-012",
    "chapter": 2,
    "verse": 14,
    "reference": "2.14",
    "sanskrit": "मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः।\n\nआगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत",
    "transliteration": "mātrā-sparśhās tu kaunteya śhītoṣhṇa-sukha-duḥkha-dāḥ\nāgamāpāyino ’nityās tans-titikṣhasva bhārata",
    "english": "The contact of the senses with their objects, O Arjuna, gives rise to feelings of cold and heat, pleasure and pain. They come and go, never lasting long. Endure them, O Arjuna.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-013",
    "chapter": 2,
    "verse": 16,
    "reference": "2.16",
    "sanskrit": "नासतो विद्यते भावो नाभावो विद्यते सतः।\n\nउभयोरपि दृष्टोऽन्तस्त्वनयोस्तत्त्वदर्शिभिः",
    "transliteration": "nāsato vidyate bhāvo nābhāvo vidyate sataḥ\nubhayorapi dṛiṣhṭo ’nta stvanayos tattva-darśhibhiḥ",
    "english": "The unreal never comes into being, the real never ceases to be. The truth about these two is seen by the seers.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-014",
    "chapter": 2,
    "verse": 17,
    "reference": "2.17",
    "sanskrit": "अविनाशि तु तद्विद्धि येन सर्वमिदं ततम्।\n\nविनाशमव्ययस्यास्य न कश्चित् कर्तुमर्हति",
    "transliteration": "avināśhi tu tadviddhi yena sarvam idaṁ tatam\nvināśham avyayasyāsya na kaśhchit kartum arhati",
    "english": "Know that to be indestructible by which all this is pervaded. No one can cause the destruction of this immutable.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-015",
    "chapter": 2,
    "verse": 19,
    "reference": "2.19",
    "sanskrit": "य एनं वेत्ति हन्तारं यश्चैनं मन्यते हतम्।\n\nउभौ तौ न विजानीतो नायं हन्ति न हन्यते",
    "transliteration": "ya enaṁ vetti hantāraṁ yaśh chainaṁ manyate hatam\nubhau tau na vijānīto nāyaṁ hanti na hanyate",
    "english": "He who considers It (the self) to be the slayer, and he who thinks of It as slain—both are ignorant. For, the self neither slays nor is being slain.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-016",
    "chapter": 2,
    "verse": 20,
    "reference": "2.20",
    "sanskrit": "न जायते म्रियते वा कदाचि\n\nन्नायं भूत्वा भविता वा न भूयः।\n\nअजो नित्यः शाश्वतोऽयं पुराणो\n\nन हन्यते हन्यमाने शरीरे",
    "transliteration": "na jāyate mriyate vā kadāchin\nnāyaṁ bhūtvā bhavitā vā na bhūyaḥ\najo nityaḥ śhāśhvato ’yaṁ purāṇo\nna hanyate hanyamāne śharīre",
    "english": "It is never born; it never dies; having come into existence once, it never ceases to exist. Unborn, eternal, perpetual, and primordial, it is not destroyed when the body is destroyed.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-017",
    "chapter": 2,
    "verse": 22,
    "reference": "2.22",
    "sanskrit": "वासांसि जीर्णानि यथा विहाय\n\nनवानि गृह्णाति नरोऽपराणि।\n\nतथा शरीराणि विहाय जीर्णा\n\nन्यन्यानि संयाति नवानि देही",
    "transliteration": "vāsānsi jīrṇāni yathā vihāya\nnavāni gṛihṇāti naro ’parāṇi\ntathā śharīrāṇi vihāya jīrṇānya\nnyāni sanyāti navāni dehī",
    "english": "As a man casts off worn-out garments and puts on new ones, so does the embodied self cast off its worn-out bodies and enter into new ones.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-018",
    "chapter": 2,
    "verse": 27,
    "reference": "2.27",
    "sanskrit": "जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च।\n\nतस्मादपरिहार्येऽर्थे न त्वं शोचितुमर्हसि",
    "transliteration": "jātasya hi dhruvo mṛityur dhruvaṁ janma mṛitasya cha\ntasmād aparihārye ’rthe na tvaṁ śhochitum arhasi",
    "english": "For, death is certain for the born, and rebirth is certain for the dead; therefore, you should not grieve for what is inevitable.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-019",
    "chapter": 2,
    "verse": 38,
    "reference": "2.38",
    "sanskrit": "सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ।\n\nततो युद्धाय युज्यस्व नैवं पापमवाप्स्यसि",
    "transliteration": "sukha-duḥkhe same kṛitvā lābhālābhau jayājayau\ntato yuddhāya yujyasva naivaṁ pāpam avāpsyasi",
    "english": "Holding pleasure and pain, gain and loss, victory and defeat as equal, gird yourself up for the battle. Thus, you shall not incur any sin.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-020",
    "chapter": 2,
    "verse": 41,
    "reference": "2.41",
    "sanskrit": "व्यवसायात्मिका बुद्धिरेकेह कुरुनन्दन।\n\nबहुशाखा ह्यनन्ताश्च बुद्धयोऽव्यवसायिनाम्",
    "transliteration": "vyavasāyātmikā buddhir ekeha kuru-nandana\nbahu-śhākhā hyanantāśh cha buddhayo ’vyavasāyinām",
    "english": "In this (Karma Yoga), O Arjuna, the resolute mind is single-pointed; the minds of the irresolute are multi-branched and endless.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-021",
    "chapter": 2,
    "verse": 47,
    "reference": "2.47",
    "sanskrit": "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\n\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि",
    "transliteration": "karmaṇy-evādhikāras te mā phaleṣhu kadāchana\nmā karma-phala-hetur bhūr mā te saṅgo ’stvakarmaṇi",
    "english": "You have the right to work alone, but not to the fruits of it. Do not be driven by the results of your work, nor have attachment to inaction.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-022",
    "chapter": 2,
    "verse": 48,
    "reference": "2.48",
    "sanskrit": "योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय।\n\nसिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते",
    "transliteration": "yoga-sthaḥ kuru karmāṇi saṅgaṁ tyaktvā dhanañjaya\nsiddhy-asiddhyoḥ samo bhūtvā samatvaṁ yoga uchyate",
    "english": "Abandoning attachment and established in Yoga, perform works, viewing success and failure with an even mind. Evenness of mind is said to be Yoga.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-023",
    "chapter": 2,
    "verse": 50,
    "reference": "2.50",
    "sanskrit": "बुद्धियुक्तो जहातीह उभे सुकृतदुष्कृते।\n\nतस्माद्योगाय युज्यस्व योगः कर्मसु कौशलम्",
    "transliteration": "buddhi-yukto jahātīha ubhe sukṛita-duṣhkṛite\ntasmād yogāya yujyasva yogaḥ karmasu kauśhalam",
    "english": "A person with an evenness of mind discards both good and evil here and now. Therefore, strive for Yoga; for Yoga is skill in action.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-024",
    "chapter": 2,
    "verse": 55,
    "reference": "2.55",
    "sanskrit": "श्री भगवानुवाच\n\nप्रजहाति यदा कामान् सर्वान् पार्थ मनोगतान्।\n\nआत्मन्येवात्मना तुष्टः स्थितप्रज्ञस्तदोच्यते",
    "transliteration": "śhrī bhagavān uvācha\nprajahāti yadā kāmān sarvān pārtha mano-gatān\nātmany-evātmanā tuṣhṭaḥ sthita-prajñas tadochyate",
    "english": "The Lord said, \"When a man renounces all the desires of the mind and is content with himself, then he is said to possess firm wisdom.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-025",
    "chapter": 2,
    "verse": 56,
    "reference": "2.56",
    "sanskrit": "दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः।\n\nवीतरागभयक्रोधः स्थितधीर्मुनिरुच्यते",
    "transliteration": "duḥkheṣhv-anudvigna-manāḥ sukheṣhu vigata-spṛihaḥ\nvīta-rāga-bhaya-krodhaḥ sthita-dhīr munir uchyate",
    "english": "He whose mind is not perturbed by pain, who has no longing for pleasures, who is free from desire, fear, and anger—he is called a sage of firm wisdom.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-026",
    "chapter": 2,
    "verse": 62,
    "reference": "2.62",
    "sanskrit": "ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते।\n\nसङ्गात् संजायते कामः कामात्क्रोधोऽभिजायते",
    "transliteration": "dhyāyato viṣhayān puṁsaḥ saṅgas teṣhūpajāyate\nsaṅgāt sañjāyate kāmaḥ kāmāt krodho ’bhijāyate",
    "english": "To one who is thinking about sense-objects, attachment to them arises; from attachment arises desire, and from desire arises anger.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-027",
    "chapter": 2,
    "verse": 63,
    "reference": "2.63",
    "sanskrit": "क्रोधाद्भवति संमोहः संमोहात्स्मृतिविभ्रमः।\n\nस्मृतिभ्रंशाद् बुद्धिनाशो बुद्धिनाशात्प्रणश्यति",
    "transliteration": "krodhād bhavati sammohaḥ sammohāt smṛiti-vibhramaḥ\nsmṛiti-bhranśhād buddhi-nāśho buddhi-nāśhāt praṇaśhyati",
    "english": "Anger leads to delusion, which causes the loss of memory; the loss of memory leads to the destruction of discrimination, and with the destruction of discrimination, one is lost.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-028",
    "chapter": 2,
    "verse": 70,
    "reference": "2.70",
    "sanskrit": "आपूर्यमाणमचलप्रतिष्ठं\n\nसमुद्रमापः प्रविशन्ति यद्वत्।\n\nतद्वत्कामा यं प्रविशन्ति सर्वे\n\nस शान्तिमाप्नोति न कामकामी",
    "transliteration": "āpūryamāṇam achala-pratiṣhṭhaṁ\nsamudram āpaḥ praviśhanti yadvat\ntadvat kāmā yaṁ praviśhanti sarve\nsa śhāntim āpnoti na kāma-kāmī",
    "english": "He into whom all desires enter, just as the waters enter the full and undisturbed sea, attains peace, and not he who longs after objects of desire.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-029",
    "chapter": 3,
    "verse": 5,
    "reference": "3.5",
    "sanskrit": "न हि कश्िचत्क्षणमपि जातु तिष्ठत्यकर्मकृत्।\n\nकार्यते ह्यवशः कर्म सर्वः प्रकृतिजैर्गुणैः",
    "transliteration": "na hi kaśhchit kṣhaṇam api jātu tiṣhṭhatyakarma-kṛit\nkāryate hyavaśhaḥ karma sarvaḥ prakṛiti-jair guṇaiḥ",
    "english": "No one can remain still for even a moment without doing work; for everyone is compelled to act, despite themselves, by the Gunas born of Nature.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-030",
    "chapter": 3,
    "verse": 8,
    "reference": "3.8",
    "sanskrit": "नियतं कुरु कर्म त्वं कर्म ज्यायो ह्यकर्मणः।\n\nशरीरयात्रापि च ते न प्रसिद्ध्येदकर्मणः",
    "transliteration": "niyataṁ kuru karma tvaṁ karma jyāyo hyakarmaṇaḥ\nśharīra-yātrāpi cha te na prasiddhyed akarmaṇaḥ",
    "english": "You must perform your obligatory action; for action is superior to non-action (Jñāna Yoga). For a person following non-action, not even the sustenance of the body is possible.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-031",
    "chapter": 3,
    "verse": 9,
    "reference": "3.9",
    "sanskrit": "यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः।\n\nतदर्थं कर्म कौन्तेय मुक्तसंगः समाचर",
    "transliteration": "yajñārthāt karmaṇo ’nyatra loko ’yaṁ karma-bandhanaḥ\ntad-arthaṁ karma kaunteya mukta-saṅgaḥ samāchara",
    "english": "This world is held in the bondage of work only when work is not performed as a sacrifice. O Arjuna, you must perform work for this purpose, free from attachment.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-032",
    "chapter": 3,
    "verse": 13,
    "reference": "3.13",
    "sanskrit": "यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः।\n\nभुञ्जते ते त्वघं पापा ये पचन्त्यात्मकारणात्",
    "transliteration": "yajña-śhiṣhṭāśhinaḥ santo muchyante sarva-kilbiṣhaiḥ\nbhuñjate te tvaghaṁ pāpā ye pachantyātma-kāraṇāt",
    "english": "Pious people who eat the remnants of sacrifices are freed from all sins, whereas those who are sinful and cook only for their own sake will only incur sin.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-033",
    "chapter": 3,
    "verse": 19,
    "reference": "3.19",
    "sanskrit": "तस्मादसक्तः सततं कार्यं कर्म समाचर।\n\nअसक्तो ह्याचरन्कर्म परमाप्नोति पूरुषः",
    "transliteration": "tasmād asaktaḥ satataṁ kāryaṁ karma samāchara\nasakto hyācharan karma param āpnoti pūruṣhaḥ",
    "english": "Therefore, do your work without attachment, which ought to be done. For, a person who works without attachment attains the Supreme.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-034",
    "chapter": 3,
    "verse": 21,
    "reference": "3.21",
    "sanskrit": "यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः।\n\nस यत्प्रमाणं कुरुते लोकस्तदनुवर्तते",
    "transliteration": "yad yad ācharati śhreṣhṭhas tat tad evetaro janaḥ\nsa yat pramāṇaṁ kurute lokas tad anuvartate",
    "english": "Whatever a great man does, others do too. Whatever standard he sets, the world follows it.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-035",
    "chapter": 3,
    "verse": 27,
    "reference": "3.27",
    "sanskrit": "प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः।\n\nअहङ्कारविमूढात्मा कर्ताऽहमिति मन्यते",
    "transliteration": "prakṛiteḥ kriyamāṇāni guṇaiḥ karmāṇi sarvaśhaḥ\nahankāra-vimūḍhātmā kartāham iti manyate",
    "english": "Actions are being performed in every way by the Gunas of Prakrti; he whose nature is deluded by egoism, however, thinks, 'I am the doer.'",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-036",
    "chapter": 3,
    "verse": 30,
    "reference": "3.30",
    "sanskrit": "मयि सर्वाणि कर्माणि संन्यस्याध्यात्मचेतसा।\n\nनिराशीर्निर्ममो भूत्वा युध्यस्व विगतज्वरः",
    "transliteration": "mayi sarvāṇi karmāṇi sannyasyādhyātma-chetasā\nnirāśhīr nirmamo bhūtvā yudhyasva vigata-jvaraḥ",
    "english": "Surrender all your actions to Me, with a mind focused on the Self, free from desire and selfishness, and fight with the heat of excitement abated.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-037",
    "chapter": 3,
    "verse": 35,
    "reference": "3.35",
    "sanskrit": "श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात्।\n\nस्वधर्मे निधनं श्रेयः परधर्मो भयावहः",
    "transliteration": "śhreyān swa-dharmo viguṇaḥ para-dharmāt sv-anuṣhṭhitāt\nswa-dharme nidhanaṁ śhreyaḥ para-dharmo bhayāvahaḥ",
    "english": "Better is one's own duty, even if done poorly, than the duty of another done well. It is better to die while performing one's own duty; the duty of another is full of fear.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-038",
    "chapter": 4,
    "verse": 7,
    "reference": "4.7",
    "sanskrit": "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत।\n\nअभ्युत्थानमधर्मस्य तदाऽऽत्मानं सृजाम्यहम्",
    "transliteration": "yadā yadā hi dharmasya glānir bhavati bhārata\nabhyutthānam adharmasya tadātmānaṁ sṛijāmyaham",
    "english": "Whenever there is a decline of Dharma, O Arjuna, and an uprising of Adharma, then I incarnate myself.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-039",
    "chapter": 4,
    "verse": 8,
    "reference": "4.8",
    "sanskrit": "परित्राणाय साधूनां विनाशाय च दुष्कृताम्।\n\nधर्मसंस्थापनार्थाय संभवामि युगे युगे",
    "transliteration": "paritrāṇāya sādhūnāṁ vināśhāya cha duṣhkṛitām\ndharma-sansthāpanārthāya sambhavāmi yuge yuge",
    "english": "For the protection of the good and the destruction of the wicked, for the establishment of Dharma, I am born from age to age.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-040",
    "chapter": 4,
    "verse": 13,
    "reference": "4.13",
    "sanskrit": "चातुर्वर्ण्यं मया सृष्टं गुणकर्मविभागशः।\n\nतस्य कर्तारमपि मां विद्ध्यकर्तारमव्ययम्",
    "transliteration": "chātur-varṇyaṁ mayā sṛiṣhṭaṁ guṇa-karma-vibhāgaśhaḥ\ntasya kartāram api māṁ viddhyakartāram avyayam",
    "english": "The system of four stations was created by Me, according to the distinction of Gunas and Karma. Though I am their creator, know Me to be non-agent and immutable.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-041",
    "chapter": 4,
    "verse": 18,
    "reference": "4.18",
    "sanskrit": "कर्मण्यकर्म यः पश्येदकर्मणि च कर्म यः।\n\nस बुद्धिमान् मनुष्येषु स युक्तः कृत्स्नकर्मकृत्",
    "transliteration": "karmaṇyakarma yaḥ paśhyed akarmaṇi cha karma yaḥ\nsa buddhimān manuṣhyeṣhu sa yuktaḥ kṛitsna-karma-kṛit",
    "english": "He who sees inaction in action and also action in inaction is wise among men. He is fit for release and has accomplished all actions.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-042",
    "chapter": 4,
    "verse": 24,
    "reference": "4.24",
    "sanskrit": "ब्रह्मार्पणं ब्रह्महविर्ब्रह्माग्नौ ब्रह्मणा हुतम्।\n\nब्रह्मैव तेन गन्तव्यं ब्रह्मकर्मसमाधिना",
    "transliteration": "brahmārpaṇaṁ brahma havir brahmāgnau brahmaṇā hutam\nbrahmaiva tena gantavyaṁ brahma-karma-samādhinā",
    "english": "Brahman is the instrument with which to offer; Brahman is the oblation. By Brahman is the oblation offered into the fire of Brahman; Brahman alone is to be attained by one who meditates on Him in their works.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-043",
    "chapter": 4,
    "verse": 34,
    "reference": "4.34",
    "sanskrit": "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया।\n\nउपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः",
    "transliteration": "tad viddhi praṇipātena paripraśhnena sevayā\nupadekṣhyanti te jñānaṁ jñāninas tattva-darśhinaḥ",
    "english": "Know this through prostration, questioning, and service. The wise who have realized the truth will instruct you in knowledge.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-044",
    "chapter": 4,
    "verse": 38,
    "reference": "4.38",
    "sanskrit": "न हि ज्ञानेन सदृशं पवित्रमिह विद्यते।\n\nतत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति",
    "transliteration": "na hi jñānena sadṛiśhaṁ pavitramiha vidyate\ntatsvayaṁ yogasansiddhaḥ kālenātmani vindati",
    "english": "For there is no purifier equal to knowledge; he who is perfected in Karma Yoga finds this knowledge of his own accord in himself in due time.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-045",
    "chapter": 4,
    "verse": 39,
    "reference": "4.39",
    "sanskrit": "श्रद्धावाँल्लभते ज्ञानं तत्परः संयतेन्द्रियः।\n\nज्ञानं लब्ध्वा परां शान्तिमचिरेणाधिगच्छति",
    "transliteration": "śhraddhāvān labhate jñānaṁ tat-paraḥ sanyatendriyaḥ\njñānaṁ labdhvā parāṁ śhāntim achireṇādhigachchhati",
    "english": "He who has faith, is intent on it, and has mastered his senses, attains knowledge. Having attained knowledge, he quickly goes to supreme peace.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-046",
    "chapter": 5,
    "verse": 8,
    "reference": "5.8",
    "sanskrit": "नैव किंचित्करोमीति युक्तो मन्येत तत्त्ववित्।\n\nपश्यन् श्रृणवन्स्पृशञ्जिघ्रन्नश्नन्गच्छन्स्वपन् श्वसन्",
    "transliteration": "naiva kiñchit karomīti yukto manyeta tattva-vit\npaśhyañ śhṛiṇvan spṛiśhañjighrann aśhnangachchhan svapañśhvasan\npralapan visṛijan gṛihṇann unmiṣhan nimiṣhann api\nindriyāṇīndriyārtheṣhu vartanta iti dhārayan",
    "english": "The one who knows the truth and is devoted to yoga should think, \"I am not doing anything,\" even though they are seeing, hearing, touching, smelling, eating, moving, sleeping, and breathing.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-047",
    "chapter": 5,
    "verse": 10,
    "reference": "5.10",
    "sanskrit": "ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः।\n\nलिप्यते न स पापेन पद्मपत्रमिवाम्भसा",
    "transliteration": "brahmaṇyādhāya karmāṇi saṅgaṁ tyaktvā karoti yaḥ\nlipyate na sa pāpena padma-patram ivāmbhasā",
    "english": "He who acts without attachment, reposing all actions on Brahman (Prakṛti), is untouched by evil, just as a lotus leaf is untouched by water.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-048",
    "chapter": 5,
    "verse": 12,
    "reference": "5.12",
    "sanskrit": "युक्तः कर्मफलं त्यक्त्वा शान्तिमाप्नोति नैष्ठिकीम्।\n\nअयुक्तः कामकारेण फले सक्तो निबध्यते",
    "transliteration": "yuktaḥ karma-phalaṁ tyaktvā śhāntim āpnoti naiṣhṭhikīm\nayuktaḥ kāma-kāreṇa phale sakto nibadhyate",
    "english": "A yogi, renouncing the fruits of their actions, attains lasting peace. But the unsteady person who is attached to the fruits of their actions, being driven by desire, is bound.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-049",
    "chapter": 5,
    "verse": 18,
    "reference": "5.18",
    "sanskrit": "विद्याविनयसंपन्ने ब्राह्मणे गवि हस्तिनि।\n\nशुनि चैव श्वपाके च पण्डिताः समदर्शिनः",
    "transliteration": "vidyā-vinaya-sampanne brāhmaṇe gavi hastini\nśhuni chaiva śhva-pāke cha paṇḍitāḥ sama-darśhinaḥ",
    "english": "The sages look with an equal eye on one endowed with learning and humility, a Brahmana, a cow, an elephant, a dog, and a dog-eater.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-050",
    "chapter": 6,
    "verse": 5,
    "reference": "6.5",
    "sanskrit": "उद्धरेदात्मनाऽऽत्मानं नात्मानमवसादयेत्।\n\nआत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः",
    "transliteration": "uddhared ātmanātmānaṁ nātmānam avasādayet\nātmaiva hyātmano bandhur ātmaiva ripur ātmanaḥ",
    "english": "One should raise oneself by one's own mind and not allow oneself to sink; for the mind alone is the friend of the self, and the mind alone is the foe of the self.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-051",
    "chapter": 6,
    "verse": 6,
    "reference": "6.6",
    "sanskrit": "बन्धुरात्माऽऽत्मनस्तस्य येनात्मैवात्मना जितः।\n\nअनात्मनस्तु शत्रुत्वे वर्तेतात्मैव शत्रुवत्",
    "transliteration": "bandhur ātmātmanas tasya yenātmaivātmanā jitaḥ\nanātmanas tu śhatrutve vartetātmaiva śhatru-vat",
    "english": "The mind is the friend of him by whom it has been conquered. But for him whose mind is not conquered, the mind, like an enemy, remains hostile.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-052",
    "chapter": 6,
    "verse": 16,
    "reference": "6.16",
    "sanskrit": "नात्यश्नतस्तु योगोऽस्ति न चैकान्तमनश्नतः।\n\nन चातिस्वप्नशीलस्य जाग्रतो नैव चार्जुन",
    "transliteration": "nātyaśhnatastu yogo ’sti na chaikāntam anaśhnataḥ\nna chāti-svapna-śhīlasya jāgrato naiva chārjuna",
    "english": "Yoga is not for him who overeats, nor for him who fasts excessively; not for him, O Arjuna, who sleeps too much, nor for him who stays awake too long.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-053",
    "chapter": 6,
    "verse": 17,
    "reference": "6.17",
    "sanskrit": "युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु।\n\nयुक्तस्वप्नावबोधस्य योगो भवति दुःखहा",
    "transliteration": "yuktāhāra-vihārasya yukta-cheṣhṭasya karmasu\nyukta-svapnāvabodhasya yogo bhavati duḥkha-hā",
    "english": "Yoga becomes the destroyer of sorrows for those who are temperate in food and recreation, temperate in their actions, and temperate in their sleep and wakefulness.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-054",
    "chapter": 6,
    "verse": 26,
    "reference": "6.26",
    "sanskrit": "यतो यतो निश्चरति मनश्चञ्चलमस्थिरम्।\n\nततस्ततो नियम्यैतदात्मन्येव वशं नयेत्",
    "transliteration": "yato yato niśhcharati manaśh chañchalam asthiram\ntatas tato niyamyaitad ātmanyeva vaśhaṁ nayet",
    "english": "Wherever the fickle and unsteady mind wanders, one should subdue it and then bring it back under the control of the self alone.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-055",
    "chapter": 6,
    "verse": 29,
    "reference": "6.29",
    "sanskrit": "सर्वभूतस्थमात्मानं सर्वभूतानि चात्मनि।\n\nईक्षते योगयुक्तात्मा सर्वत्र समदर्शनः",
    "transliteration": "sarva-bhūta-stham ātmānaṁ sarva-bhūtāni chātmani\nīkṣhate yoga-yuktātmā sarvatra sama-darśhanaḥ",
    "english": "He whose mind is fixed in Yoga sees reality everywhere; he sees his Self as abiding in all beings and all beings in his Self.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-056",
    "chapter": 6,
    "verse": 30,
    "reference": "6.30",
    "sanskrit": "यो मां पश्यति सर्वत्र सर्वं च मयि पश्यति।\n\nतस्याहं न प्रणश्यामि स च मे न प्रणश्यति",
    "transliteration": "yo māṁ paśhyati sarvatra sarvaṁ cha mayi paśhyati\ntasyāhaṁ na praṇaśhyāmi sa cha me na praṇaśhyati",
    "english": "To him who sees Me in every self and every self in Me—I am not lost to him, nor is he lost to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-057",
    "chapter": 6,
    "verse": 32,
    "reference": "6.32",
    "sanskrit": "आत्मौपम्येन सर्वत्र समं पश्यति योऽर्जुन।\n\nसुखं वा यदि वा दुःखं सः योगी परमो मतः",
    "transliteration": "ātmaupamyena sarvatra samaṁ paśhyati yo ’rjuna\nsukhaṁ vā yadi vā duḥkhaṁ sa yogī paramo mataḥ",
    "english": "He who, due to the similarity of selves everywhere, sees pleasure or pain as the same everywhere—that yogi, O Arjuna, is considered the closest.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-058",
    "chapter": 6,
    "verse": 35,
    "reference": "6.35",
    "sanskrit": "श्री भगवानुवाच\n\nअसंशयं महाबाहो मनो दुर्निग्रहं चलं।\n\nअभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते",
    "transliteration": "śhrī bhagavān uvācha\nasanśhayaṁ mahā-bāho mano durnigrahaṁ chalam\nabhyāsena tu kaunteya vairāgyeṇa cha gṛihyate",
    "english": "The Lord said, \"The mind is indeed hard to subdue and fickle, O mighty-armed one, but, O son of Kunti, it can be brought under control through practice and the exercise of dispassion.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-059",
    "chapter": 6,
    "verse": 47,
    "reference": "6.47",
    "sanskrit": "योगिनामपि सर्वेषां मद्गतेनान्तरात्मना।\n\nश्रद्धावान्भजते यो मां स मे युक्ततमो मतः",
    "transliteration": "yoginām api sarveṣhāṁ mad-gatenāntar-ātmanā\nśhraddhāvān bhajate yo māṁ sa me yuktatamo mataḥ",
    "english": "He who, with faith, worships Me, and whose innermost self is fixed in Me, I consider him to be the greatest of the Yogins.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-060",
    "chapter": 7,
    "verse": 7,
    "reference": "7.7",
    "sanskrit": "मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय।\n\nमयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव",
    "transliteration": "mattaḥ parataraṁ nānyat kiñchid asti dhanañjaya\nmayi sarvam idaṁ protaṁ sūtre maṇi-gaṇā iva",
    "english": "There is nothing higher than Me, O Arjuna. All this is strung on Me, like rows of gems on a thread.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-061",
    "chapter": 7,
    "verse": 14,
    "reference": "7.14",
    "sanskrit": "दैवी ह्येषा गुणमयी मम माया दुरत्यया।\n\nमामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते",
    "transliteration": "daivī hyeṣhā guṇa-mayī mama māyā duratyayā\nmām eva ye prapadyante māyām etāṁ taranti te",
    "english": "(a) For this divine Maya or Mine, consisting of the three Gunas (assumed for purposes of sport), is hard to overcome.\n৷৷\n(b) ৷৷ But those who take refuge in Me alone shall pass beyond the Maya.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-062",
    "chapter": 7,
    "verse": 16,
    "reference": "7.16",
    "sanskrit": "चतुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन।\n\nआर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ",
    "transliteration": "chatur-vidhā bhajante māṁ janāḥ sukṛitino ’rjuna\nārto jijñāsur arthārthī jñānī cha bharatarṣhabha",
    "english": "Four types of men of good deeds worship Me, O Arjuna: the distressed, the seekers of knowledge, the seekers of wealth, and the men of knowledge.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-063",
    "chapter": 7,
    "verse": 19,
    "reference": "7.19",
    "sanskrit": "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते।\n\nवासुदेवः सर्वमिति स महात्मा सुदुर्लभः",
    "transliteration": "bahūnāṁ janmanām ante jñānavān māṁ prapadyate\nvāsudevaḥ sarvam iti sa mahātmā su-durlabhaḥ",
    "english": "At the end of many births, the man of knowledge finds refuge in Me, realizing that 'Vasudeva is all.' It is very difficult to find such a great-souled person.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-064",
    "chapter": 8,
    "verse": 5,
    "reference": "8.5",
    "sanskrit": "अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम्।\n\nयः प्रयाति स मद्भावं याति नास्त्यत्र संशयः",
    "transliteration": "anta-kāle cha mām eva smaran muktvā kalevaram\nyaḥ prayāti sa mad-bhāvaṁ yāti nāstyatra sanśhayaḥ",
    "english": "And at the time of death, anyone who departs, giving up the body while thinking of Me alone, attains My state; there is no doubt about this.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-065",
    "chapter": 8,
    "verse": 6,
    "reference": "8.6",
    "sanskrit": "यं यं वापि स्मरन्भावं त्यजत्यन्ते कलेवरम्।\n\nतं तमेवैति कौन्तेय सदा तद्भावभावितः",
    "transliteration": "yaṁ yaṁ vāpi smaran bhāvaṁ tyajatyante kalevaram\ntaṁ tam evaiti kaunteya sadā tad-bhāva-bhāvitaḥ",
    "english": "O son of Kunti, thinking of any entity, whichever it may be, one gives up the body at the end; he attains that very one, having been always engrossed in its thought.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-066",
    "chapter": 8,
    "verse": 7,
    "reference": "8.7",
    "sanskrit": "तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च।\n\nमय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयम्",
    "transliteration": "tasmāt sarveṣhu kāleṣhu mām anusmara yudhya cha\nmayyarpita-mano-buddhir mām evaiṣhyasyasanśhayam",
    "english": "Therefore, think of Me at all times and fight; there is no doubt that by dedicating your mind and intellect to Me, you will attain only Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-067",
    "chapter": 9,
    "verse": 2,
    "reference": "9.2",
    "sanskrit": "राजविद्या राजगुह्यं पवित्रमिदमुत्तमम्।\n\nप्रत्यक्षावगमं धर्म्यं सुसुखं कर्तुमव्ययम्",
    "transliteration": "rāja-vidyā rāja-guhyaṁ pavitram idam uttamam\npratyakṣhāvagamaṁ dharmyaṁ su-sukhaṁ kartum avyayam",
    "english": "This is the royal science, the royal mystery, the supreme purifier. It is realized through direct experience, is in accord with Dharma, is pleasant to practice, and is abiding.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-068",
    "chapter": 9,
    "verse": 4,
    "reference": "9.4",
    "sanskrit": "मया ततमिदं सर्वं जगदव्यक्तमूर्तिना।\n\nमत्स्थानि सर्वभूतानि न चाहं तेष्ववस्थितः",
    "transliteration": "mayā tatam idaṁ sarvaṁ jagad avyakta-mūrtinā\nmat-sthāni sarva-bhūtāni na chāhaṁ teṣhvavasthitaḥ",
    "english": "This entire universe is pervaded by Me, in an unmanifest form. All beings abide in Me, but I do not abide in them.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-069",
    "chapter": 9,
    "verse": 11,
    "reference": "9.11",
    "sanskrit": "अवजानन्ति मां मूढा मानुषीं तनुमाश्रितम्।\n\nपरं भावमजानन्तो मम भूतमहेश्वरम्",
    "transliteration": "avajānanti māṁ mūḍhā mānuṣhīṁ tanum āśhritam\nparaṁ bhāvam ajānanto mama bhūta-maheśhvaram",
    "english": "Fools disregard Me, dwelling in a human form, not knowing My higher nature as the Supreme Lord of all beings.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-070",
    "chapter": 9,
    "verse": 22,
    "reference": "9.22",
    "sanskrit": "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते।\n\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्",
    "transliteration": "ananyāśh chintayanto māṁ ye janāḥ paryupāsate\nteṣhāṁ nityābhiyuktānāṁ yoga-kṣhemaṁ vahāmyaham",
    "english": "Those who, excluding all else, think of Me and worship Me, aspiring after eternal union with Me, I look after their prosperity and welfare (Yoga and Ksema).",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-071",
    "chapter": 9,
    "verse": 26,
    "reference": "9.26",
    "sanskrit": "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति।\n\nतदहं भक्त्युपहृतमश्नामि प्रयतात्मनः",
    "transliteration": "patraṁ puṣhpaṁ phalaṁ toyaṁ yo me bhaktyā prayachchhati\ntadahaṁ bhaktyupahṛitam aśhnāmi prayatātmanaḥ",
    "english": "Whoever offers Me with true devotion a leaf, a flower, a fruit, or some water, I accept this offering made with devotion by them who are pure of heart.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-072",
    "chapter": 9,
    "verse": 29,
    "reference": "9.29",
    "sanskrit": "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः।\n\nये भजन्ति तु मां भक्त्या मयि ते तेषु चाप्यहम्",
    "transliteration": "samo ’haṁ sarva-bhūteṣhu na me dveṣhyo ’sti na priyaḥ\nye bhajanti tu māṁ bhaktyā mayi te teṣhu chāpyaham",
    "english": "I am the same to all creation; there is none hateful or dear to me. But those who worship me with devotion abide in me, and I in them.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-073",
    "chapter": 9,
    "verse": 30,
    "reference": "9.30",
    "sanskrit": "अपि चेत्सुदुराचारो भजते मामनन्यभाक्।\n\nसाधुरेव स मन्तव्यः सम्यग्व्यवसितो हि सः",
    "transliteration": "api chet su-durāchāro bhajate mām ananya-bhāk\nsādhur eva sa mantavyaḥ samyag vyavasito hi saḥ",
    "english": "If even the most sinful man worships Me with undivided devotion, he should be regarded as holy, for he has rightly resolved.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-074",
    "chapter": 9,
    "verse": 34,
    "reference": "9.34",
    "sanskrit": "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु।\n\nमामेवैष्यसि युक्त्वैवमात्मानं मत्परायणः",
    "transliteration": "man-manā bhava mad-bhakto mad-yājī māṁ namaskuru\nmām evaiṣhyasi yuktvaivam ātmānaṁ mat-parāyaṇaḥ",
    "english": "Focus your mind on Me, be My devotee, worship Me. Bow down to Me. Engaging your mind in this manner and regarding Me as the supreme goal, you will come to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-075",
    "chapter": 10,
    "verse": 8,
    "reference": "10.8",
    "sanskrit": "अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते।\n\nइति मत्वा भजन्ते मां बुधा भावसमन्विताः",
    "transliteration": "ahaṁ sarvasya prabhavo mattaḥ sarvaṁ pravartate\niti matvā bhajante māṁ budhā bhāva-samanvitāḥ",
    "english": "I am the origin of all; from me everything proceeds. Thinking thus, the wise worship me with all devotion (Bhava).",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-076",
    "chapter": 10,
    "verse": 9,
    "reference": "10.9",
    "sanskrit": "मच्चित्ता मद्गतप्राणा बोधयन्तः परस्परम्।\n\nकथयन्तश्च मां नित्यं तुष्यन्ति च रमन्ति च",
    "transliteration": "mach-chittā mad-gata-prāṇā bodhayantaḥ parasparam\nkathayantaśh cha māṁ nityaṁ tuṣhyanti cha ramanti cha",
    "english": "With their minds focused on Me, their pranas centered in Me, inspiring one another and always speaking of Me, they live in contentment and bliss at all times.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-077",
    "chapter": 10,
    "verse": 10,
    "reference": "10.10",
    "sanskrit": "तेषां सततयुक्तानां भजतां प्रीतिपूर्वकम्।\n\nददामि बुद्धियोगं तं येन मामुपयान्ति ते",
    "transliteration": "teṣhāṁ satata-yuktānāṁ bhajatāṁ prīti-pūrvakam\ndadāmi buddhi-yogaṁ taṁ yena mām upayānti te",
    "english": "To those who are ceaselessly united with Me and who worship Me with immense love, I lovingly grant that mental disposition (Buddhi-yoga) which leads them to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-078",
    "chapter": 10,
    "verse": 11,
    "reference": "10.11",
    "sanskrit": "तेषामेवानुकम्पार्थमहमज्ञानजं तमः।\n\nनाशयाम्यात्मभावस्थो ज्ञानदीपेन भास्वता",
    "transliteration": "teṣhām evānukampārtham aham ajñāna-jaṁ tamaḥ\nnāśhayāmyātma-bhāva-stho jñāna-dīpena bhāsvatā",
    "english": "Out of compassion for them alone, I, abiding in their mental activity as its object, dispel the darkness born of ignorance with the brilliant lamp of knowledge.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-079",
    "chapter": 10,
    "verse": 20,
    "reference": "10.20",
    "sanskrit": "अहमात्मा गुडाकेश सर्वभूताशयस्थितः।\n\nअहमादिश्च मध्यं च भूतानामन्त एव च",
    "transliteration": "aham ātmā guḍākeśha sarva-bhūtāśhaya-sthitaḥ\naham ādiśh cha madhyaṁ cha bhūtānām anta eva cha",
    "english": "I am the Self, O Arjuna, dwelling in the hearts of all beings; I am the beginning, the middle, and the end of all beings.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-080",
    "chapter": 11,
    "verse": 7,
    "reference": "11.7",
    "sanskrit": "इहैकस्थं जगत्कृत्स्नं पश्याद्य सचराचरम्।\n\nमम देहे गुडाकेश यच्चान्यद्द्रष्टुमिच्छसि",
    "transliteration": "ihaika-sthaṁ jagat kṛitsnaṁ paśhyādya sa-charācharam\nmama dehe guḍākeśha yach chānyad draṣhṭum ichchhasi",
    "english": "Behold here, O Arjuna, the entire universe with its mobile and immobile things, all centered in My body, and whatever else you desire to see.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-081",
    "chapter": 11,
    "verse": 12,
    "reference": "11.12",
    "sanskrit": "दिवि सूर्यसहस्रस्य भवेद्युगपदुत्थिता।\n\nयदि भाः सदृशी सा स्याद्भासस्तस्य महात्मनः",
    "transliteration": "divi sūrya-sahasrasya bhaved yugapad utthitā\nyadi bhāḥ sadṛiśhī sā syād bhāsas tasya mahātmanaḥ",
    "english": "If a thousand suns were to rise at once in the sky, the resulting splendour would be like the splendour of that mighty One.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-082",
    "chapter": 11,
    "verse": 32,
    "reference": "11.32",
    "sanskrit": "श्री भगवानुवाच\n\nकालोऽस्मि लोकक्षयकृत्प्रवृद्धो\n\nलोकान्समाहर्तुमिह प्रवृत्तः।\n\nऋतेऽपि त्वां न भविष्यन्ति सर्वे\n\nयेऽवस्थिताः प्रत्यनीकेषु योधाः",
    "transliteration": "śhrī-bhagavān uvācha\nkālo ’smi loka-kṣhaya-kṛit pravṛiddho\nlokān samāhartum iha pravṛittaḥ\nṛite ’pi tvāṁ na bhaviṣhyanti sarve\nye ’vasthitāḥ pratyanīkeṣhu yodhāḥ",
    "english": "The Lord said, \"I am the world-destroying Time. Manifesting myself fully, I have begun to destroy the worlds here. Even without you, none of the warriors arrayed in the hostile ranks will survive.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-083",
    "chapter": 11,
    "verse": 33,
    "reference": "11.33",
    "sanskrit": "तस्मात्त्वमुत्तिष्ठ यशो लभस्व\n\nजित्वा शत्रून् भुङ्क्ष्व राज्यं समृद्धम्।\n\nमयैवैते निहताः पूर्वमेव\n\nनिमित्तमात्रं भव सव्यसाचिन्",
    "transliteration": "tasmāt tvam uttiṣhṭha yaśho labhasva\njitvā śhatrūn bhuṅkṣhva rājyaṁ samṛiddham\nmayaivaite nihatāḥ pūrvam eva\nnimitta-mātraṁ bhava savya-sāchin",
    "english": "Therefore, arise, win glory. Conquering your foes, enjoy a prosperous kingdom. By Me they have already been slain. You be merely an instrument, O Arjuna, you great archer!",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-084",
    "chapter": 11,
    "verse": 55,
    "reference": "11.55",
    "sanskrit": "मत्कर्मकृन्मत्परमो मद्भक्तः सङ्गवर्जितः।\n\nनिर्वैरः सर्वभूतेषु यः स मामेति पाण्डव",
    "transliteration": "mat-karma-kṛin mat-paramo mad-bhaktaḥ saṅga-varjitaḥ\nnirvairaḥ sarva-bhūteṣhu yaḥ sa mām eti pāṇḍava",
    "english": "Whoever works for Me, regards Me as the highest and is devoted to Me, free from attachment and without animosity towards any creature, they come to Me, O Arjuna.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-085",
    "chapter": 12,
    "verse": 2,
    "reference": "12.2",
    "sanskrit": "श्री भगवानुवाचमय्यावेश्य मनो ये मां नित्ययुक्ता उपासते।श्रद्धया परयोपेतास्ते मे युक्ततमा मताः",
    "transliteration": "śhrī-bhagavān uvācha\nmayy āveśhya mano ye māṁ nitya-yuktā upāsate\nśhraddhayā parayopetās te me yuktatamā matāḥ",
    "english": "The Lord said, \"Those who, ever integrated with Me and possessing supreme faith, worship Me, focusing their minds on Me—these are considered by Me to be the highest among the yogis.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-086",
    "chapter": 12,
    "verse": 6,
    "reference": "12.6",
    "sanskrit": "ये तु सर्वाणि कर्माणि मयि संन्यस्य मत्पराः।अनन्येनैव योगेन मां ध्यायन्त उपासते",
    "transliteration": "ye tu sarvāṇi karmāṇi mayi sannyasya mat-paraḥ\nananyenaiva yogena māṁ dhyāyanta upāsate",
    "english": "For those who dedicate all their actions to Me, hold Me as their supreme goal, are intent on Me, and worship Me, meditating on Me with exclusive devotion;",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-087",
    "chapter": 12,
    "verse": 7,
    "reference": "12.7",
    "sanskrit": "तेषामहं समुद्धर्ता मृत्युसंसारसागरात्।भवामि नचिरात्पार्थ मय्यावेशितचेतसाम्",
    "transliteration": "teṣhām ahaṁ samuddhartā mṛityu-saṁsāra-sāgarāt\nbhavāmi na chirāt pārtha mayy āveśhita-chetasām",
    "english": "Those whose minds are thus focused on Me, I soon become their savior from the ocean of mortal life.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-088",
    "chapter": 12,
    "verse": 13,
    "reference": "12.13",
    "sanskrit": "अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च।निर्ममो निरहङ्कारः समदुःखसुखः क्षमी",
    "transliteration": "adveṣhṭā sarva-bhūtānāṁ maitraḥ karuṇa eva cha\nnirmamo nirahankāraḥ sama-duḥkha-sukhaḥ kṣhamī",
    "english": "He who never hates any being, who is friendly and compassionate, who is free from the feelings of \"I\" and \"mine,\" who looks upon all pain and pleasure equally, and who is enduring;",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-089",
    "chapter": 12,
    "verse": 14,
    "reference": "12.14",
    "sanskrit": "सन्तुष्टः सततं योगी यतात्मा दृढनिश्चयः।मय्यर्पितमनोबुद्धिर्यो मद्भक्तः स मे प्रियः",
    "transliteration": "santuṣhṭaḥ satataṁ yogī yatātmā dṛiḍha-niśhchayaḥ\nmayy arpita-mano-buddhir yo mad-bhaktaḥ sa me priyaḥ",
    "english": "He who is content, who meditates ever, is self-restrained, and is firm in his convictions, and has his mind and reason dedicated to Me—he is dear to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-090",
    "chapter": 12,
    "verse": 15,
    "reference": "12.15",
    "sanskrit": "यस्मान्नोद्विजते लोको लोकान्नोद्विजते च यः।हर्षामर्षभयोद्वेगैर्मुक्तो यः स च मे प्रियः",
    "transliteration": "yasmān nodvijate loko lokān nodvijate cha yaḥ\nharṣhāmarṣha-bhayodvegair mukto yaḥ sa cha me priyaḥ",
    "english": "He from whom the world has no cause to be frightened, who is not frightened by the world, who is free from joy and impatience, fear, and aversion - he is dear to me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-091",
    "chapter": 12,
    "verse": 16,
    "reference": "12.16",
    "sanskrit": "अनपेक्षः शुचिर्दक्ष उदासीनो गतव्यथः।सर्वारम्भपरित्यागी यो मद्भक्तः स मे प्रियः",
    "transliteration": "anapekṣhaḥ śhuchir dakṣha udāsīno gata-vyathaḥ\nsarvārambha-parityāgī yo mad-bhaktaḥ sa me priyaḥ",
    "english": "He who is free from desires, who is pure, expert, indifferent, and free from agony, who has renounced every undertaking—he is dear to me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-092",
    "chapter": 12,
    "verse": 17,
    "reference": "12.17",
    "sanskrit": "यो न हृष्यति न द्वेष्टि न शोचति न काङ्क्षति।शुभाशुभपरित्यागी भक्ितमान्यः स मे प्रियः",
    "transliteration": "yo na hṛiṣhyati na dveṣhṭi na śhochati na kāṅkṣhati\nśhubhāśhubha-parityāgī bhaktimān yaḥ sa me priyaḥ",
    "english": "He who does not rejoice, nor hate, nor grieve, nor desire, who renounces both good and evil, and who is full of devotion to Me—such a devotee is dear to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-093",
    "chapter": 12,
    "verse": 18,
    "reference": "12.18",
    "sanskrit": "समः शत्रौ च मित्रे च तथा मानापमानयोः।शीतोष्णसुखदुःखेषु समः सङ्गविवर्जितः",
    "transliteration": "samaḥ śhatrau cha mitre cha tathā mānāpamānayoḥ\nśhītoṣhṇa-sukha-duḥkheṣhu samaḥ saṅga-vivarjitaḥ",
    "english": "He who is the same to foe and friend, honor and dishonor, who is alike to both cold and heat, pleasure and pain, and who is free from all attachments;",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-094",
    "chapter": 12,
    "verse": 19,
    "reference": "12.19",
    "sanskrit": "तुल्यनिन्दास्तुतिर्मौनी सन्तुष्टो येनकेनचित्।अनिकेतः स्थिरमतिर्भक्ितमान्मे प्रियो नरः",
    "transliteration": "tulya-nindā-stutir maunī santuṣhṭo yena kenachit\naniketaḥ sthira-matir bhaktimān me priyo naraḥ",
    "english": "He who regards both blame and praise alike, who is silent and content with any lot, who has no home, who is firm of mind, and who is devoted to Me - such a man is dear to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-095",
    "chapter": 12,
    "verse": 20,
    "reference": "12.20",
    "sanskrit": "ये तु धर्म्यामृतमिदं यथोक्तं पर्युपासते।श्रद्दधाना मत्परमा भक्तास्तेऽतीव मे प्रियाः",
    "transliteration": "ye tu dharmyāmṛitam idaṁ yathoktaṁ paryupāsate\nśhraddadhānā mat-paramā bhaktās te ’tīva me priyāḥ",
    "english": "But those devotees who follow this nectar of virtuous duty, as taught above, who are full of faith and regard Me as the Supreme, are exceedingly dear to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-096",
    "chapter": 13,
    "verse": 2,
    "reference": "13.2",
    "sanskrit": "श्री भगवानुवाचइदं शरीरं कौन्तेय क्षेत्रमित्यभिधीयते।एतद्यो वेत्ति तं प्राहुः क्षेत्रज्ञ इति तद्विदः",
    "transliteration": "śhrī-bhagavān uvācha\nidaṁ śharīraṁ kaunteya kṣhetram ity abhidhīyate\netad yo vetti taṁ prāhuḥ kṣhetra-jña iti tad-vidaḥ",
    "english": "The Lord said, \"O Arjuna, this body is called the Field, Ksetra. Those who know the self call the one who knows it the Field-knower, Ksetrajna.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-097",
    "chapter": 13,
    "verse": 3,
    "reference": "13.3",
    "sanskrit": "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत।\n\nक्षेत्रक्षेत्रज्ञयोर्ज्ञानं यत्तज्ज्ञानं मतं मम",
    "transliteration": "kṣhetra-jñaṁ chāpi māṁ viddhi sarva-kṣhetreṣhu bhārata\nkṣhetra-kṣhetrajñayor jñānaṁ yat taj jñānaṁ mataṁ mama",
    "english": "And know Me also as the Knower of all Fields, O Arjuna. In My view, the knowledge of the Field and its Knower is the true knowledge.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-098",
    "chapter": 13,
    "verse": 7,
    "reference": "13.7",
    "sanskrit": "इच्छा द्वेषः सुखं दुःखं सङ्घातश्चेतनाधृतिः।एतत्क्षेत्रं समासेन सविकारमुदाहृतम्",
    "transliteration": "ichchhā dveṣhaḥ sukhaṁ duḥkhaṁ saṅghātaśh chetanā dhṛitiḥ\netat kṣhetraṁ samāsena sa-vikāram udāhṛitam",
    "english": "Desire, hatred, pleasure, and pain, and the combination that constitutes the basis of consciousness—or the individual self—have been briefly described here, along with their modifications.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-099",
    "chapter": 13,
    "verse": 22,
    "reference": "13.22",
    "sanskrit": "पुरुषः प्रकृतिस्थो हि भुङ्क्ते प्रकृतिजान्गुणान्।कारणं गुणसङ्गोऽस्य सदसद्योनिजन्मसु",
    "transliteration": "puruṣhaḥ prakṛiti-stho hi bhuṅkte prakṛiti-jān guṇān\nkāraṇaṁ guṇa-saṅgo ’sya sad-asad-yoni-janmasu",
    "english": "(a) Indeed, the self seated in Prakrti experiences the Gunas born of Prakrti.\n(b) Its attachment to these Gunas is the cause of birth in good and evil wombs.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-100",
    "chapter": 14,
    "verse": 5,
    "reference": "14.5",
    "sanskrit": "सत्त्वं रजस्तम इति गुणाः प्रकृतिसंभवाः।निबध्नन्ति महाबाहो देहे देहिनमव्ययम्",
    "transliteration": "sattvaṁ rajas tama iti guṇāḥ prakṛiti-sambhavāḥ\nnibadhnanti mahā-bāho dehe dehinam avyayam",
    "english": "The Gunas of Sattva, Rajas, and Tamas arise from Prakrti and bind the immutable Self in the body, O Arjuna.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-101",
    "chapter": 14,
    "verse": 6,
    "reference": "14.6",
    "sanskrit": "तत्र सत्त्वं निर्मलत्वात्प्रकाशकमनामयम्।सुखसङ्गेन बध्नाति ज्ञानसङ्गेन चानघ",
    "transliteration": "tatra sattvaṁ nirmalatvāt prakāśhakam anāmayam\nsukha-saṅgena badhnāti jñāna-saṅgena chānagha",
    "english": "Of these, sattva, being without impurity, is luminous and free from morbidity. It binds, O Arjuna, through attachment to pleasure and knowledge.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-102",
    "chapter": 14,
    "verse": 7,
    "reference": "14.7",
    "sanskrit": "रजो रागात्मकं विद्धि तृष्णासङ्गसमुद्भवम्।तन्निबध्नाति कौन्तेय कर्मसङ्गेन देहिनम्",
    "transliteration": "rajo rāgātmakaṁ viddhi tṛiṣhṇā-saṅga-samudbhavam\ntan nibadhnāti kaunteya karma-saṅgena dehinam",
    "english": "Know, O Arjuna, that Rajas is of the nature of passion springing from thirst and attachment. It binds the embodied self with attachment to action.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-103",
    "chapter": 14,
    "verse": 8,
    "reference": "14.8",
    "sanskrit": "तमस्त्वज्ञानजं विद्धि मोहनं सर्वदेहिनाम्।प्रमादालस्यनिद्राभिस्तन्निबध्नाति भारत",
    "transliteration": "tamas tv ajñāna-jaṁ viddhi mohanaṁ sarva-dehinām\npramādālasya-nidrābhis tan nibadhnāti bhārata",
    "english": "Know that Tamas is born of false knowledge and deludes all embodied beings. It binds, O Arjuna, with negligence, indolence, and sleep.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-104",
    "chapter": 14,
    "verse": 26,
    "reference": "14.26",
    "sanskrit": "मां च योऽव्यभिचारेण भक्ितयोगेन सेवते।स गुणान्समतीत्यैतान् ब्रह्मभूयाय कल्पते",
    "transliteration": "māṁ cha yo ’vyabhichāreṇa bhakti-yogena sevate\nsa guṇān samatītyaitān brahma-bhūyāya kalpate",
    "english": "And he who, with unwavering devotion through Yoga, serves Me, he, transcending the Gunas, becomes fit for the state of Brahman.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-105",
    "chapter": 15,
    "verse": 1,
    "reference": "15.1",
    "sanskrit": "श्री भगवानुवाचऊर्ध्वमूलमधःशाखमश्वत्थं प्राहुरव्ययम्।छन्दांसि यस्य पर्णानि यस्तं वेद स वेदवित्",
    "transliteration": "śhrī-bhagavān uvācha\nūrdhva-mūlam adhaḥ-śhākham aśhvatthaṁ prāhur avyayam\nchhandānsi yasya parṇāni yas taṁ veda sa veda-vit",
    "english": "The Lord said, \"They speak of an immutable Asvattha tree with its roots above and branches below; its leaves are the Vedas. He who knows it knows the Vedas.\"",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-106",
    "chapter": 15,
    "verse": 6,
    "reference": "15.6",
    "sanskrit": "न तद्भासयते सूर्यो न शशाङ्को न पावकः।यद्गत्वा न निवर्तन्ते तद्धाम परमं मम",
    "transliteration": "na tad bhāsayate sūryo na śhaśhāṅko na pāvakaḥ\nyad gatvā na nivartante tad dhāma paramaṁ mama",
    "english": "That supreme light, upon reaching which they do not return any more, is Mine; neither the sun nor the moon nor the fire illuminates It.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-107",
    "chapter": 15,
    "verse": 7,
    "reference": "15.7",
    "sanskrit": "ममैवांशो जीवलोके जीवभूतः सनातनः।मनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति",
    "transliteration": "mamaivānśho jīva-loke jīva-bhūtaḥ sanātanaḥ\nmanaḥ-ṣhaṣhṭhānīndriyāṇi prakṛiti-sthāni karṣhati",
    "english": "An everlasting part of Myself, having become the bound self in the world of life, attracts the senses, of which the mind is the sixth, and which abide in Prakriti.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-108",
    "chapter": 15,
    "verse": 15,
    "reference": "15.15",
    "sanskrit": "सर्वस्य चाहं हृदि सन्निविष्टो    मत्तः स्मृतिर्ज्ञानमपोहनं च।वेदैश्च सर्वैरहमेव वेद्यो    वेदान्तकृद्वेदविदेव चाहम्",
    "transliteration": "sarvasya chāhaṁ hṛidi sanniviṣhṭo\nmattaḥ smṛitir jñānam apohanaṁ cha\nvedaiśh cha sarvair aham eva vedyo\nvedānta-kṛid veda-vid eva chāham",
    "english": "And I am seated in the hearts of all. From Me come memory, knowledge, and their removal too. Indeed, I alone am to be known from all the Vedas. I bring about the fruition of the Vedic rituals; I alone am the knower of the Vedas.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-109",
    "chapter": 16,
    "verse": 1,
    "reference": "16.1",
    "sanskrit": "श्री भगवानुवाच\n\nअभयं सत्त्वसंशुद्धिः ज्ञानयोगव्यवस्थितिः।\n\nदानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम्",
    "transliteration": "śhrī-bhagavān uvācha\nabhayaṁ sattva-sanśhuddhir jñāna-yoga-vyavasthitiḥ\ndānaṁ damaśh cha yajñaśh cha svādhyāyas tapa ārjavam",
    "english": "The Lord said, \"Fearlessness, purity of mind, devotion to meditation on the knowledge of the self, alms-giving, self-control, worship, study of the Vedas, austerity, and uprightness—",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-110",
    "chapter": 16,
    "verse": 2,
    "reference": "16.2",
    "sanskrit": "अहिंसा सत्यमक्रोधस्त्यागः शान्तिरपैशुनम्।दया भूतेष्वलोलुप्त्वं मार्दवं ह्रीरचापलम्",
    "transliteration": "ahinsā satyam akrodhas tyāgaḥ śhāntir apaiśhunam\ndayā bhūteṣhv aloluptvaṁ mārdavaṁ hrīr achāpalam",
    "english": "Non-injury, truth, freedom from anger, renunciation, tranquility, non-slandering of others, compassion for all beings, freedom from desire, gentleness, a sense of shame, and freedom from fickleness;",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-111",
    "chapter": 16,
    "verse": 3,
    "reference": "16.3",
    "sanskrit": "तेजः क्षमा धृतिः शौचमद्रोहो नातिमानिता।\n\nभवन्ति सम्पदं दैवीमभिजातस्य भारत",
    "transliteration": "tejaḥ kṣhamā dhṛitiḥ śhaucham adroho nāti-mānitā\nbhavanti sampadaṁ daivīm abhijātasya bhārata",
    "english": "Grandeur, patience, fortitude, purity, freedom from hatred and over-pride—these, O Arjuna, belong to one who is born to a divine destiny.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-112",
    "chapter": 16,
    "verse": 21,
    "reference": "16.21",
    "sanskrit": "त्रिविधं नरकस्येदं द्वारं नाशनमात्मनः।कामः क्रोधस्तथा लोभस्तस्मादेतत्त्रयं त्यजेत्",
    "transliteration": "tri-vidhaṁ narakasyedaṁ dvāraṁ nāśhanam ātmanaḥ\nkāmaḥ krodhas tathā lobhas tasmād etat trayaṁ tyajet",
    "english": "Desire, wrath, and greed—these are the three gateways to Naraka, ruinous to the self. Therefore, one should abandon these three.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-113",
    "chapter": 17,
    "verse": 3,
    "reference": "17.3",
    "sanskrit": "सत्त्वानुरूपा सर्वस्य श्रद्धा भवति भारत।श्रद्धामयोऽयं पुरुषो यो यच्छ्रद्धः स एव सः",
    "transliteration": "sattvānurūpā sarvasya śhraddhā bhavati bhārata\nśhraddhā-mayo ‘yaṁ puruṣho yo yach-chhraddhaḥ sa eva saḥ",
    "english": "O Arjuna, the faith of everyone is in accordance with their inner organ (Antahkarana). Each person consists of faith; whatever their faith is, that is who they are.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-114",
    "chapter": 17,
    "verse": 14,
    "reference": "17.14",
    "sanskrit": "देवद्विजगुरुप्राज्ञपूजनं शौचमार्जवम्।ब्रह्मचर्यमहिंसा च शारीरं तप उच्यते",
    "transliteration": "deva-dwija-guru-prājña- pūjanaṁ śhaucham ārjavam\nbrahmacharyam ahinsā cha śhārīraṁ tapa uchyate",
    "english": "Worshiping the gods, the twice-born, the preceptors, the enlightened ones, practicing purity, uprightness, continence, and non-injury—these are called austerity of the body.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-115",
    "chapter": 17,
    "verse": 15,
    "reference": "17.15",
    "sanskrit": "अनुद्वेगकरं वाक्यं सत्यं प्रियहितं च यत्।स्वाध्यायाभ्यसनं चैव वाङ्मयं तप उच्यते",
    "transliteration": "anudvega-karaṁ vākyaṁ satyaṁ priya-hitaṁ cha yat\nsvādhyāyābhyasanaṁ chaiva vāṅ-mayaṁ tapa uchyate",
    "english": "Speech that causes no shock, is true, pleasant, and beneficial, and also the practice of reciting scriptures, is called the austerity of speech.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-116",
    "chapter": 17,
    "verse": 16,
    "reference": "17.16",
    "sanskrit": "मनःप्रसादः सौम्यत्वं मौनमात्मविनिग्रहः।भावसंशुद्धिरित्येतत्तपो मानसमुच्यते",
    "transliteration": "manaḥ-prasādaḥ saumyatvaṁ maunam ātma-vinigrahaḥ\nbhāva-sanśhuddhir ity etat tapo mānasam uchyate",
    "english": "Serenity of mind, benevolence, silence, self-control, and purity of mind—these are known as austerity of the mind.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-117",
    "chapter": 18,
    "verse": 5,
    "reference": "18.5",
    "sanskrit": "यज्ञदानतपःकर्म न त्याज्यं कार्यमेव तत्।यज्ञो दानं तपश्चैव पावनानि मनीषिणाम्",
    "transliteration": "yajña-dāna-tapaḥ-karma na tyājyaṁ kāryam eva tat\nyajño dānaṁ tapaśh chaiva pāvanāni manīṣhiṇām",
    "english": "(a) The acts of sacrifice, gifts, and austerities should not be relinquished; but should be performed...\n\n(b) ...For sacrifices, gifts, and austerities are the means of purification for the wise.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-118",
    "chapter": 18,
    "verse": 14,
    "reference": "18.14",
    "sanskrit": "अधिष्ठानं तथा कर्ता करणं च पृथग्विधम्।विविधाश्च पृथक्चेष्टा दैवं चैवात्र पञ्चमम्",
    "transliteration": "adhiṣhṭhānaṁ tathā kartā karaṇaṁ cha pṛithag-vidham\nvividhāśh cha pṛithak cheṣhṭā daivaṁ chaivātra pañchamam",
    "english": "The seat of action, the agent, the various kinds of organs, the different and distinctive functions of vital air, and the fifth among these—Divinity—all these.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-119",
    "chapter": 18,
    "verse": 46,
    "reference": "18.46",
    "sanskrit": "यतः प्रवृत्तिर्भूतानां येन सर्वमिदं ततम्।स्वकर्मणा तमभ्यर्च्य सिद्धिं विन्दति मानवः",
    "transliteration": "yataḥ pravṛittir bhūtānāṁ yena sarvam idaṁ tatam\nsva-karmaṇā tam abhyarchya siddhiṁ vindati mānavaḥ",
    "english": "From whom all beings arise and by whom all this is pervaded—by worshipping Him with one's own duty, one reaches perfection.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-120",
    "chapter": 18,
    "verse": 55,
    "reference": "18.55",
    "sanskrit": "भक्त्या मामभिजानाति यावान्यश्चास्मि तत्त्वतः।ततो मां तत्त्वतो ज्ञात्वा विशते तदनन्तरम्",
    "transliteration": "bhaktyā mām abhijānāti yāvān yaśh chāsmi tattvataḥ\ntato māṁ tattvato jñātvā viśhate tad-anantaram",
    "english": "Through devotion, he comes to know Me fully—who and what I am in reality, who I am and how I am. Knowing Me thus in truth, he forthwith enters into Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-121",
    "chapter": 18,
    "verse": 58,
    "reference": "18.58",
    "sanskrit": "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि।अथ चेत्त्वमहङ्कारान्न श्रोष्यसि विनङ्क्ष्यसि",
    "transliteration": "mach-chittaḥ sarva-durgāṇi mat-prasādāt tariṣhyasi\natha chet tvam ahankārān na śhroṣhyasi vinaṅkṣhyasi",
    "english": "Focusing your thoughts on Me, you shall, by My grace, cross over all difficulties. If, however, out of self-conceit, you do not heed Me, you will perish.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-122",
    "chapter": 18,
    "verse": 61,
    "reference": "18.61",
    "sanskrit": "ईश्वरः सर्वभूतानां हृद्देशेऽर्जुन तिष्ठति।भ्रामयन्सर्वभूतानि यन्त्रारूढानि मायया",
    "transliteration": "īśhvaraḥ sarva-bhūtānāṁ hṛid-deśhe ‘rjuna tiṣhṭhati\nbhrāmayan sarva-bhūtāni yantrārūḍhāni māyayā",
    "english": "The Lord, O Arjuna, abides in the heart of every being, spinning them round and round, as if mounted on a wheel, by His power.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-123",
    "chapter": 18,
    "verse": 63,
    "reference": "18.63",
    "sanskrit": "इति ते ज्ञानमाख्यातं गुह्याद्गुह्यतरं मया।विमृश्यैतदशेषेण यथेच्छसि तथा कुरु",
    "transliteration": "iti te jñānam ākhyātaṁ guhyād guhyataraṁ mayā\nvimṛiśhyaitad aśheṣheṇa yathechchhasi tathā kuru",
    "english": "Thus, the knowledge, the mystery of mysteries, has been declared to you by Me. Reflecting on it fully, do as you will.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-124",
    "chapter": 18,
    "verse": 65,
    "reference": "18.65",
    "sanskrit": "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु।मामेवैष्यसि सत्यं ते प्रतिजाने प्रियोऽसि मे",
    "transliteration": "man-manā bhava mad-bhakto mad-yājī māṁ namaskuru\nmām evaiṣhyasi satyaṁ te pratijāne priyo ‘si me",
    "english": "Focus your mind on Me. Be My devotee. Worship Me. Prostrate before Me. You will come to Me alone. I promise you truly; for you are dear to Me.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-125",
    "chapter": 18,
    "verse": 66,
    "reference": "18.66",
    "sanskrit": "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज।अहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः",
    "transliteration": "sarva-dharmān parityajya mām ekaṁ śharaṇaṁ vraja\nahaṁ tvāṁ sarva-pāpebhyo mokṣhayiṣhyāmi mā śhuchaḥ",
    "english": "Relinquishing all Dharmas completely, seek Me alone for refuge. I will release you from all sins; grieve not.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-126",
    "chapter": 18,
    "verse": 78,
    "reference": "18.78",
    "sanskrit": "यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः।\n\nतत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम।।18.78।",
    "transliteration": "yatra yogeśhvaraḥ kṛiṣhṇo yatra pārtho dhanur-dharaḥ\ntatra śhrīr vijayo bhūtir dhruvā nītir matir mama",
    "english": "Wherever there is Sri Krsna, the Lord of Yoga, and Arjuna the archer, there is always fortune, victory, wealth, and sound morality. This is my firm conviction.",
    "translationAuthor": "Swami Adidevananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  }
];

export const TOTAL_SHLOKAS = SHLOKAS.length;
export const DAILY_TARGET = 2;
export const JOURNEY_DAYS = TOTAL_SHLOKAS / DAILY_TARGET;
