export type LoopStep = "listen" | "repeat" | "understand" | "recall";

export type Shloka = {
  id: string;
  chapter: number;
  verse: number;
  reference: string;
  sanskrit: string;
  transliteration: string;
  english: string;
  translationAuthor: string;
  reflectionPrompt: string;
  audioSrc?: string;
};

export const SHLOKA_SOURCE = "https://github.com/gita/gita";

export const SHLOKAS: Shloka[] = [
  {
    "id": "GS-001",
    "chapter": 1,
    "verse": 1,
    "reference": "1.1",
      "audioSrc": "/audio/1.1.mp3",
    "sanskrit": "धृतराष्ट्र उवाच |\nधर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः |\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय ||१-१||",
    "transliteration": "dhṛtarāṣṭra uvāca .\ndharmakṣetre kurukṣetre samavetā yuyutsavaḥ .\nmāmakāḥ pāṇḍavāścaiva kimakurvata sañjaya ||1-1||",
    "english": "1.1 Dhritarashtra said  What did my people and the sons of Pandu do when they had assembled\ntogether eager for battle on the holy plain of Kurukshetra, O Sanjaya.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-002",
    "chapter": 2,
    "verse": 2,
    "reference": "2.2",
      "audioSrc": "/audio/2.2.mp3",
    "sanskrit": "श्रीभगवानुवाच |\nकुतस्त्वा कश्मलमिदं विषमे समुपस्थितम् |\nअनार्यजुष्टमस्वर्ग्यमकीर्तिकरमर्जुन ||२-२||",
    "transliteration": "śrībhagavānuvāca .\nkutastvā kaśmalamidaṃ viṣame samupasthitam .\nanāryajuṣṭamasvargyamakīrtikaramarjuna ||2-2||",
    "english": "2.2 The Blessed Lord said  Whence is this perilous strait come upon thee, this dejection which is unworthy of you, disgraceful, and which will close the gates of heaven upon you, O Arjuna?",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-003",
    "chapter": 2,
    "verse": 3,
    "reference": "2.3",
      "audioSrc": "/audio/2.3.mp3",
    "sanskrit": "क्लैब्यं मा स्म गमः पार्थ नैतत्त्वय्युपपद्यते |\nक्षुद्रं हृदयदौर्बल्यं त्यक्त्वोत्तिष्ठ परन्तप ||२-३||",
    "transliteration": "klaibyaṃ mā sma gamaḥ pārtha naitattvayyupapadyate .\nkṣudraṃ hṛdayadaurbalyaṃ tyaktvottiṣṭha parantapa ||2-3||",
    "english": "2.3 Yield not to impotence, O Arjuna, son of Pritha. It does not befit thee. Cast off this mean weakness of the heart! Stand up, O scorcher of the foes!",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-004",
    "chapter": 2,
    "verse": 4,
    "reference": "2.4",
      "audioSrc": "/audio/2.4.mp3",
    "sanskrit": "अर्जुन उवाच |\nकथं भीष्ममहं सङ्ख्ये द्रोणं च मधुसूदन |\nइषुभिः प्रतियोत्स्यामि पूजार्हावरिसूदन ||२-४||",
    "transliteration": "arjuna uvāca .\nkathaṃ bhīṣmamahaṃ saṅkhye droṇaṃ ca madhusūdana .\niṣubhiḥ pratiyotsyāmi pūjārhāvarisūdana ||2-4||",
    "english": "2.4 Arjuna said  How, O Madhusudana, shall I fight in battle with arrows against Bhishma and Drona, who are fit to be worshipped, O destroyer of enemies?",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-005",
    "chapter": 2,
    "verse": 7,
    "reference": "2.7",
      "audioSrc": "/audio/2.7.mp3",
    "sanskrit": "कार्पण्यदोषोपहतस्वभावः\nपृच्छामि त्वां धर्मसम्मूढचेताः |\nयच्छ्रेयः स्यान्निश्चितं ब्रूहि तन्मे\nशिष्यस्तेऽहं शाधि मां त्वां प्रपन्नम् ||२-७||",
    "transliteration": "kārpaṇyadoṣopahatasvabhāvaḥ pṛcchāmi tvāṃ dharmasammūḍhacetāḥ .\nyacchreyaḥ syānniścitaṃ brūhi tanme śiṣyaste.ahaṃ śādhi māṃ tvāṃ prapannam ||2-7||",
    "english": "2.7 My heart is overpowered by the taint of pity; my mind is confused as to duty. I ask Thee: Tell me decisively what is good for me. I am Thy disciple. Instruct me who has taken refuge in Thee.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-006",
    "chapter": 2,
    "verse": 11,
    "reference": "2.11",
      "audioSrc": "/audio/2.11.mp3",
    "sanskrit": "श्रीभगवानुवाच |\nअशोच्यानन्वशोचस्त्वं प्रज्ञावादांश्च भाषसे |\nगतासूनगतासूंश्च नानुशोचन्ति पण्डिताः ||२-११||",
    "transliteration": "śrībhagavānuvāca .\naśocyānanvaśocastvaṃ prajñāvādāṃśca bhāṣase .\ngatāsūnagatāsūṃśca nānuśocanti paṇḍitāḥ ||2-11||",
    "english": "2.11 The Blessed Lord said  Thou hast grieved for those that should not be grieved for, yet thou speakest words of wisdom. The wise grieve neither for the living nor for the dead.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-007",
    "chapter": 2,
    "verse": 12,
    "reference": "2.12",
      "audioSrc": "/audio/2.12.mp3",
    "sanskrit": "न त्वेवाहं जातु नासं न त्वं नेमे जनाधिपाः |\nन चैव न भविष्यामः सर्वे वयमतः परम् ||२-१२||",
    "transliteration": "na tvevāhaṃ jātu nāsaṃ na tvaṃ neme janādhipāḥ .\nna caiva na bhaviṣyāmaḥ sarve vayamataḥ param ||2-12||",
    "english": "2.12 Nor at any time indeed was I not, nor thou, nor these rulers of men, nor verily shall we ever cease to be hereafter.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-008",
    "chapter": 2,
    "verse": 13,
    "reference": "2.13",
      "audioSrc": "/audio/2.13.mp3",
    "sanskrit": "देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा |\nतथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति ||२-१३||",
    "transliteration": "dehino.asminyathā dehe kaumāraṃ yauvanaṃ jarā .\ntathā dehāntaraprāptirdhīrastatra na muhyati ||2-13||",
    "english": "2.13 Just as in this body the embodied (soul) passes into childhood, youth and old age, so also does it pass into another body; the firm man does not grieve thereat.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-009",
    "chapter": 2,
    "verse": 14,
    "reference": "2.14",
      "audioSrc": "/audio/2.14.mp3",
    "sanskrit": "मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः |\nआगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत ||२-१४||",
    "transliteration": "mātrāsparśāstu kaunteya śītoṣṇasukhaduḥkhadāḥ .\nāgamāpāyino.anityāstāṃstitikṣasva bhārata ||2-14||",
    "english": "2.14 The contacts of the senses with the objects, O son of Kunti, which cause heat and cold, pleasure and pain, have a beginning and an end; they are impermanent; endure them bravely, O Arjuna.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-010",
    "chapter": 2,
    "verse": 22,
    "reference": "2.22",
      "audioSrc": "/audio/2.22.mp3",
    "sanskrit": "वासांसि जीर्णानि यथा विहाय\nनवानि गृह्णाति नरोऽपराणि |\nतथा शरीराणि विहाय जीर्णा-\nन्यन्यानि संयाति नवानि देही ||२-२२||",
    "transliteration": "vāsāṃsi jīrṇāni yathā vihāya navāni gṛhṇāti naro.aparāṇi .\ntathā śarīrāṇi vihāya jīrṇāni anyāni saṃyāti navāni dehī ||2-22||",
    "english": "2.22 Just as a man casts off worn-out clothes and puts on new ones, so also the embodied Self casts off worn-out bodies and enters others which are new.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-011",
    "chapter": 2,
    "verse": 23,
    "reference": "2.23",
      "audioSrc": "/audio/2.23.mp3",
    "sanskrit": "नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः |\nन चैनं क्लेदयन्त्यापो न शोषयति मारुतः ||२-२३||",
    "transliteration": "nainaṃ chindanti śastrāṇi nainaṃ dahati pāvakaḥ .\nna cainaṃ kledayantyāpo na śoṣayati mārutaḥ ||2-23||",
    "english": "2.23 Weapons cut It not, fire burns It not, water wets It not, wind dries It not.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-012",
    "chapter": 2,
    "verse": 27,
    "reference": "2.27",
      "audioSrc": "/audio/2.27.mp3",
    "sanskrit": "जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च |\nतस्मादपरिहार्येऽर्थे न त्वं शोचितुमर्हसि ||२-२७||",
    "transliteration": "jātasya hi dhruvo mṛtyurdhruvaṃ janma mṛtasya ca .\ntasmādaparihārye.arthe na tvaṃ śocitumarhasi ||2-27||",
    "english": "2.27 For certain is death for the born, and certain is birth for the dead; therefore, over the inevitable thou shouldst not grieve.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-013",
    "chapter": 2,
    "verse": 41,
    "reference": "2.41",
      "audioSrc": "/audio/2.41.mp3",
    "sanskrit": "व्यवसायात्मिका बुद्धिरेकेह कुरुनन्दन |\nबहुशाखा ह्यनन्ताश्च बुद्धयोऽव्यवसायिनाम् ||२-४१||",
    "transliteration": "vyavasāyātmikā buddhirekeha kurunandana .\nbahuśākhā hyanantāśca buddhayo.avyavasāyinām ||2-41||",
    "english": "2.41 Here, O joy of the Kurus, there is but a single one-pointed determination; many-branched and endless are the thoughts of the irresolute.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-014",
    "chapter": 2,
    "verse": 44,
    "reference": "2.44",
      "audioSrc": "/audio/2.44.mp3",
    "sanskrit": "भोगैश्वर्यप्रसक्तानां तयापहृतचेतसाम् |\nव्यवसायात्मिका बुद्धिः समाधौ न विधीयते ||२-४४||",
    "transliteration": "bhogaiśvaryaprasaktānāṃ tayāpahṛtacetasām .\nvyavasāyātmikā buddhiḥ samādhau na vidhīyate ||2-44||",
    "english": "2.44 For those who are attached to pleasure and power, whose minds are drawn away by such teaching, ï1thatï1 determinate reason is not formed which is steadily bent on meditation and Samadhi (superconscious state).",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-015",
    "chapter": 2,
    "verse": 45,
    "reference": "2.45",
      "audioSrc": "/audio/2.45.mp3",
    "sanskrit": "त्रैगुण्यविषया वेदा निस्त्रैगुण्यो भवार्जुन |\nनिर्द्वन्द्वो नित्यसत्त्वस्थो निर्योगक्षेम आत्मवान् ||२-४५||",
    "transliteration": "traiguṇyaviṣayā vedā nistraiguṇyo bhavārjuna .\nnirdvandvo nityasattvastho niryogakṣema ātmavān ||2-45||",
    "english": "2.45 The Vedas deal with the three attributes (of Nature); be thou above these three attributes. O Arjuna, free yourself from the pairs of opposites, and ever remain in the ality of Sattva (goodness), freed from (the thought of) acisition and preservation, and be established in the Self.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-016",
    "chapter": 2,
    "verse": 46,
    "reference": "2.46",
      "audioSrc": "/audio/2.46.mp3",
    "sanskrit": "यावानर्थ उदपाने सर्वतः सम्प्लुतोदके |\nतावान्सर्वेषु वेदेषु ब्राह्मणस्य विजानतः ||२-४६||",
    "transliteration": "yāvānartha udapāne sarvataḥ samplutodake .\ntāvānsarveṣu vedeṣu brāhmaṇasya vijānataḥ ||2-46||",
    "english": "2.46 To the Brahmana who has known the Self, all the Vedas are of as much use as is a reservoir of water in a place where there is a flood.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-017",
    "chapter": 2,
    "verse": 47,
    "reference": "2.47",
    "sanskrit": "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन |\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ||२-४७||",
    "transliteration": "karmaṇyevādhikāraste mā phaleṣu kadācana .\nmā karmaphalaheturbhūrmā te saṅgo.astvakarmaṇi ||2-47||",
    "english": "2.47 Thy right is to work only, but never with its fruits; let not the fruits of action be thy motive, nor let thy attachment be to inaction.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-018",
    "chapter": 2,
    "verse": 59,
    "reference": "2.59",
      "audioSrc": "/audio/2.59.mp3",
    "sanskrit": "विषया विनिवर्तन्ते निराहारस्य देहिनः |\nरसवर्जं रसोऽप्यस्य परं दृष्ट्वा निवर्तते ||२-५९||",
    "transliteration": "viṣayā vinivartante nirāhārasya dehinaḥ .\nrasavarjaṃ raso.apyasya paraṃ dṛṣṭvā nivartate ||2-59||",
    "english": "2.59 The objects of the senses turn away from the abstinent man leaving the longing (behind); but his longing also turns away on seeing the Supreme.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-019",
    "chapter": 2,
    "verse": 62,
    "reference": "2.62",
      "audioSrc": "/audio/2.62.mp3",
    "sanskrit": "ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते |\nसङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते ||२-६२||",
    "transliteration": "dhyāyato viṣayānpuṃsaḥ saṅgasteṣūpajāyate .\nsaṅgātsañjāyate kāmaḥ kāmātkrodho.abhijāyate ||2-62||",
    "english": "2.62 When a man thinks of the objects, attachment for them arises; from attachment desire is born; from desire anger arises.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-020",
    "chapter": 2,
    "verse": 63,
    "reference": "2.63",
      "audioSrc": "/audio/2.63.mp3",
    "sanskrit": "क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः |\nस्मृतिभ्रंशाद् बुद्धिनाशो बुद्धिनाशात्प्रणश्यति ||२-६३||",
    "transliteration": "krodhādbhavati sammohaḥ sammohātsmṛtivibhramaḥ .\nsmṛtibhraṃśād buddhināśo buddhināśātpraṇaśyati ||2-63||",
    "english": "2.63 From anger comes delusion; from delusion loss of memory; from loss of memory the destruction of discrimination; from the destruction of discrimination he perishes.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-021",
    "chapter": 2,
    "verse": 64,
    "reference": "2.64",
      "audioSrc": "/audio/2.64.mp3",
    "sanskrit": "रागद्वेषविमुक्तैस्तु विषयानिन्द्रियैश्चरन् | (or वियुक्तैस्तु)\nआत्मवश्यैर्विधेयात्मा प्रसादमधिगच्छति ||२-६४||",
    "transliteration": "rāgadveṣavimuktaistu viṣayānindriyaiścaran .\norviyuktaistu ātmavaśyairvidheyātmā prasādamadhigacchati ||2-64||",
    "english": "2.64 But the self-controlled man, moving among the objects with the senses under restraint and free from attraction and repulsion, attains to peace.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-022",
    "chapter": 2,
    "verse": 69,
    "reference": "2.69",
      "audioSrc": "/audio/2.69.mp3",
    "sanskrit": "या निशा सर्वभूतानां तस्यां जागर्ति संयमी |\nयस्यां जाग्रति भूतानि सा निशा पश्यतो मुनेः ||२-६९||",
    "transliteration": "yā niśā sarvabhūtānāṃ tasyāṃ jāgarti saṃyamī .\nyasyāṃ jāgrati bhūtāni sā niśā paśyato muneḥ ||2-69||",
    "english": "2.69 That which is night to all beings, in that the self-controlled man is awake; when all beings are awake, that is night for the Muni (sage) who sees.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-023",
    "chapter": 3,
    "verse": 9,
    "reference": "3.9",
      "audioSrc": "/audio/3.9.mp3",
    "sanskrit": "यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः |\nतदर्थं कर्म कौन्तेय मुक्तसङ्गः समाचर ||३-९||",
    "transliteration": "yajñārthātkarmaṇo.anyatra loko.ayaṃ karmabandhanaḥ .\ntadarthaṃ karma kaunteya muktasaṅgaḥ samācara ||3-9||",
    "english": "3.9 The world is bound by actions other than those performed for the sake of sacrifice; do thou, therefore, O son of Kunti (Arjuna), perform action for that sake (for sacrifice alone), free from attachment.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-024",
    "chapter": 3,
    "verse": 14,
    "reference": "3.14",
      "audioSrc": "/audio/3.14.mp3",
    "sanskrit": "अन्नाद्भवन्ति भूतानि पर्जन्यादन्नसम्भवः |\nयज्ञाद्भवति पर्जन्यो यज्ञः कर्मसमुद्भवः ||३-१४||",
    "transliteration": "annādbhavanti bhūtāni parjanyādannasambhavaḥ .\nyajñādbhavati parjanyo yajñaḥ karmasamudbhavaḥ ||3-14||",
    "english": "3.14 From food come forth beings; from rain food is produced; from sacrifice arises rain and sacrifice is born of action.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-025",
    "chapter": 3,
    "verse": 21,
    "reference": "3.21",
      "audioSrc": "/audio/3.21.mp3",
    "sanskrit": "यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः |\nस यत्प्रमाणं कुरुते लोकस्तदनुवर्तते ||३-२१||",
    "transliteration": "yadyadācarati śreṣṭhastattadevetaro janaḥ .\nsa yatpramāṇaṃ kurute lokastadanuvartate ||3-21||",
    "english": "3.21 Whatsoever a great man does, that the other men also do; whatever he sets up as the standard, that the world (mankind) follows.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-026",
    "chapter": 3,
    "verse": 27,
    "reference": "3.27",
      "audioSrc": "/audio/3.27.mp3",
    "sanskrit": "प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः |\nअहङ्कारविमूढात्मा कर्ताहमिति मन्यते ||३-२७||",
    "transliteration": "prakṛteḥ kriyamāṇāni guṇaiḥ karmāṇi sarvaśaḥ .\nahaṅkāravimūḍhātmā kartāhamiti manyate ||3-27||",
    "english": "3.27 All actions are wrought in all cases by the alities of Nature only. He whose mind is deluded by egoism thinks, \"I am the doer.\"",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-027",
    "chapter": 3,
    "verse": 37,
    "reference": "3.37",
      "audioSrc": "/audio/3.37.mp3",
    "sanskrit": "श्रीभगवानुवाच |\nकाम एष क्रोध एष रजोगुणसमुद्भवः |\nमहाशनो महापाप्मा विद्ध्येनमिह वैरिणम् ||३-३७||",
    "transliteration": "śrībhagavānuvāca .\nkāma eṣa krodha eṣa rajoguṇasamudbhavaḥ .\nmahāśano mahāpāpmā viddhyenamiha vairiṇam ||3-37||",
    "english": "3.37 The Blessed Lord said  It is desire, it is anger both of the ality of Rajas, all-devouring, all-sinful; know this as the foe here (in this world).",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-028",
    "chapter": 4,
    "verse": 1,
    "reference": "4.1",
      "audioSrc": "/audio/4.1.mp3",
    "sanskrit": "श्रीभगवानुवाच |\nइमं विवस्वते योगं प्रोक्तवानहमव्ययम् |\nविवस्वान्मनवे प्राह मनुरिक्ष्वाकवेऽब्रवीत् ||४-१||",
    "transliteration": "śrībhagavānuvāca .\nimaṃ vivasvate yogaṃ proktavānahamavyayam .\nvivasvānmanave prāha manurikṣvākave.abravīt ||4-1||",
    "english": "4.1 The Blessed Lord said  I taught this imperishable Yoga to Vivasvan; he told it to Manu; Manu proclaimed it to Ikshvaku.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-029",
    "chapter": 4,
    "verse": 2,
    "reference": "4.2",
      "audioSrc": "/audio/4.2.mp3",
    "sanskrit": "एवं परम्पराप्राप्तमिमं राजर्षयो विदुः |\nस कालेनेह महता योगो नष्टः परन्तप ||४-२||",
    "transliteration": "evaṃ paramparāprāptamimaṃ rājarṣayo viduḥ .\nsa kāleneha mahatā yogo naṣṭaḥ parantapa ||4-2||",
    "english": "4.2 This, handed down thus in regular succession, the royal sages knew. This Yoga, by long lapse of time, has been lost here, O Parantapa (burner of the foes).",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-030",
    "chapter": 4,
    "verse": 3,
    "reference": "4.3",
      "audioSrc": "/audio/4.3.mp3",
    "sanskrit": "स एवायं मया तेऽद्य योगः प्रोक्तः पुरातनः |\nभक्तोऽसि मे सखा चेति रहस्यं ह्येतदुत्तमम् ||४-३||",
    "transliteration": "sa evāyaṃ mayā te.adya yogaḥ proktaḥ purātanaḥ .\nbhakto.asi me sakhā ceti rahasyaṃ hyetaduttamam ||4-3||",
    "english": "4.3 That same ancient Yoga has been today taught to thee by Me, for thou art My devotee and My friend; it is the supreme secret.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-031",
    "chapter": 4,
    "verse": 6,
    "reference": "4.6",
      "audioSrc": "/audio/4.6.mp3",
    "sanskrit": "अजोऽपि सन्नव्ययात्मा भूतानामीश्वरोऽपि सन् |\nप्रकृतिं स्वामधिष्ठाय सम्भवाम्यात्ममायया ||४-६||",
    "transliteration": "ajo.api sannavyayātmā bhūtānāmīśvaro.api san .\nprakṛtiṃ svāmadhiṣṭhāya sambhavāmyātmamāyayā ||4-6||",
    "english": "4.6 Though I am unborn, of imperishable nature, and though I am the Lord of all beings, yet, governing My own Nature, I am born by My own Maya.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-032",
    "chapter": 4,
    "verse": 7,
    "reference": "4.7",
      "audioSrc": "/audio/4.7.mp3",
    "sanskrit": "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत |\nअभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम् ||४-७||",
    "transliteration": "yadā yadā hi dharmasya glānirbhavati bhārata .\nabhyutthānamadharmasya tadātmānaṃ sṛjāmyaham ||4-7||",
    "english": "4.7 Whenever there is decline of righteousness, O Arjuna, and rise of unrighteousness, then I manifest Myself.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-033",
    "chapter": 4,
    "verse": 8,
    "reference": "4.8",
      "audioSrc": "/audio/4.8.mp3",
    "sanskrit": "परित्राणाय साधूनां विनाशाय च दुष्कृताम् |\nधर्मसंस्थापनार्थाय सम्भवामि युगे युगे ||४-८||",
    "transliteration": "paritrāṇāya sādhūnāṃ vināśāya ca duṣkṛtām .\ndharmasaṃsthāpanārthāya sambhavāmi yuge yuge ||4-8||",
    "english": "4.8 For the protection of the good, for the destruction of the wicked and for the establishment of righteousness, I am born in every age.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-034",
    "chapter": 4,
    "verse": 9,
    "reference": "4.9",
      "audioSrc": "/audio/4.9.mp3",
    "sanskrit": "जन्म कर्म च मे दिव्यमेवं यो वेत्ति तत्त्वतः |\nत्यक्त्वा देहं पुनर्जन्म नैति मामेति सोऽर्जुन ||४-९||",
    "transliteration": "janma karma ca me divyamevaṃ yo vetti tattvataḥ .\ntyaktvā dehaṃ punarjanma naiti māmeti so.arjuna ||4-9||",
    "english": "4.9 He who thus know, in their true light, My divine birth and action, having abandoned the body, is not born again, he comes to Me, O Arjuna.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-035",
    "chapter": 4,
    "verse": 11,
    "reference": "4.11",
      "audioSrc": "/audio/4.11.mp3",
    "sanskrit": "ये यथा मां प्रपद्यन्ते तांस्तथैव भजाम्यहम् |\nमम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः ||४-११||",
    "transliteration": "ye yathā māṃ prapadyante tāṃstathaiva bhajāmyaham .\nmama vartmānuvartante manuṣyāḥ pārtha sarvaśaḥ ||4-11||",
    "english": "4.11 In whatever way men approach Me even so do I reward them; My path do men tread in all ways, O Arjuna.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-036",
    "chapter": 4,
    "verse": 13,
    "reference": "4.13",
      "audioSrc": "/audio/4.13.mp3",
    "sanskrit": "चातुर्वर्ण्यं मया सृष्टं गुणकर्मविभागशः |\nतस्य कर्तारमपि मां विद्ध्यकर्तारमव्ययम् ||४-१३||",
    "transliteration": "cāturvarṇyaṃ mayā sṛṣṭaṃ guṇakarmavibhāgaśaḥ .\ntasya kartāramapi māṃ viddhyakartāramavyayam ||4-13||",
    "english": "4.13 The fourfold caste has been created by Me according to the differentiation of Guna and Karma; though I am the author thereof know Me as non-doer and immutable.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-037",
    "chapter": 4,
    "verse": 34,
    "reference": "4.34",
      "audioSrc": "/audio/4.34.mp3",
    "sanskrit": "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया |\nउपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः ||४-३४||",
    "transliteration": "tadviddhi praṇipātena paripraśnena sevayā .\nupadekṣyanti te jñānaṃ jñāninastattvadarśinaḥ ||4-34||",
    "english": "4.34 Know That by long prostration, by estion and by service; the wise who have realised the Truth will instruct thee in (that) knowledge.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-038",
    "chapter": 5,
    "verse": 18,
    "reference": "5.18",
      "audioSrc": "/audio/5.18.mp3",
    "sanskrit": "विद्याविनयसम्पन्ने ब्राह्मणे गवि हस्तिनि |\nशुनि चैव श्वपाके च पण्डिताः समदर्शिनः ||५-१८||",
    "transliteration": "vidyāvinayasampanne brāhmaṇe gavi hastini .\nśuni caiva śvapāke ca paṇḍitāḥ samadarśinaḥ ||5-18||",
    "english": "5.18 Sages look with an eal eye on a Brahmana endowed with learning and humility, on a cow, on an elephant, and even on a dog and an outcaste.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-039",
    "chapter": 5,
    "verse": 22,
    "reference": "5.22",
      "audioSrc": "/audio/5.22.mp3",
    "sanskrit": "ये हि संस्पर्शजा भोगा दुःखयोनय एव ते |\nआद्यन्तवन्तः कौन्तेय न तेषु रमते बुधः ||५-२२||",
    "transliteration": "ye hi saṃsparśajā bhogā duḥkhayonaya eva te .\nādyantavantaḥ kaunteya na teṣu ramate budhaḥ ||5-22||",
    "english": "5.22 The enjoyments that are born of contacts are only generators of pain, for they have a beginning and an end, O Arjuna; the wise man does not rejoice in them.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-040",
    "chapter": 5,
    "verse": 29,
    "reference": "5.29",
      "audioSrc": "/audio/5.29.mp3",
    "sanskrit": "भोक्तारं यज्ञतपसां सर्वलोकमहेश्वरम् |\nसुहृदं सर्वभूतानां ज्ञात्वा मां शान्तिमृच्छति ||५-२९||",
    "transliteration": "bhoktāraṃ yajñatapasāṃ sarvalokamaheśvaram .\nsuhṛdaṃ sarvabhūtānāṃ jñātvā māṃ śāntimṛcchati ||5-29||",
    "english": "5.29 He who knows Me as the enjoyer of sacrifices and austerities, the great Lord of all the worlds and the friend of all beings, attains to peace.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-041",
    "chapter": 6,
    "verse": 17,
    "reference": "6.17",
      "audioSrc": "/audio/6.17.mp3",
    "sanskrit": "युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु |\nयुक्तस्वप्नावबोधस्य योगो भवति दुःखहा ||६-१७||",
    "transliteration": "yuktāhāravihārasya yuktaceṣṭasya karmasu .\nyuktasvapnāvabodhasya yogo bhavati duḥkhahā ||6-17||",
    "english": "6.17 Yoga becomes the destroyer of pain for him who is moderate in eating and recreation (such \nas walking, etc.), who is moderate in exertion in actions, who is moderate in sleep and wakefulness.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-042",
    "chapter": 6,
    "verse": 41,
    "reference": "6.41",
      "audioSrc": "/audio/6.41.mp3",
    "sanskrit": "प्राप्य पुण्यकृतां लोकानुषित्वा शाश्वतीः समाः |\nशुचीनां श्रीमतां गेहे योगभ्रष्टोऽभिजायते ||६-४१||",
    "transliteration": "prāpya puṇyakṛtāṃ lokānuṣitvā śāśvatīḥ samāḥ .\nśucīnāṃ śrīmatāṃ gehe yogabhraṣṭo.abhijāyate ||6-41||",
    "english": "6.41 Having attained to the worlds of the righteous and having dwelt there for everlasting years, he who fell from Yoga is rorn in a house of the pure and wealthy.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-043",
    "chapter": 6,
    "verse": 47,
    "reference": "6.47",
      "audioSrc": "/audio/6.47.mp3",
    "sanskrit": "योगिनामपि सर्वेषां मद्गतेनान्तरात्मना |\nश्रद्धावान्भजते यो मां स मे युक्ततमो मतः ||६-४७||",
    "transliteration": "yogināmapi sarveṣāṃ madgatenāntarātmanā .\nśraddhāvānbhajate yo māṃ sa me yuktatamo mataḥ ||6-47||",
    "english": "6.47 And among all the Yogis he who, full of faith and with his inner self merged in Me, worships Me is deemed by Me to be the most devout.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-044",
    "chapter": 7,
    "verse": 3,
    "reference": "7.3",
      "audioSrc": "/audio/7.3.mp3",
    "sanskrit": "मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये |\nयततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः ||७-३||",
    "transliteration": "manuṣyāṇāṃ sahasreṣu kaścidyatati siddhaye .\nyatatāmapi siddhānāṃ kaścinmāṃ vetti tattvataḥ ||7-3||",
    "english": "7.3 Among thousands of men, one perchance strives for perfection; even among those successful strivers, only one perchance knows Me in essence.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-045",
    "chapter": 7,
    "verse": 4,
    "reference": "7.4",
      "audioSrc": "/audio/7.4.mp3",
    "sanskrit": "भूमिरापोऽनलो वायुः खं मनो बुद्धिरेव च |\nअहंकार इतीयं मे भिन्ना प्रकृतिरष्टधा ||७-४||",
    "transliteration": "bhūmirāpo.analo vāyuḥ khaṃ mano buddhireva ca .\nahaṃkāra itīyaṃ me bhinnā prakṛtiraṣṭadhā ||7-4||",
    "english": "7.4 Earth, water, fire, air, ether, mind, intellect and egoism  thus is My Nature divided eightfold.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-046",
    "chapter": 7,
    "verse": 5,
    "reference": "7.5",
      "audioSrc": "/audio/7.5.mp3",
    "sanskrit": "अपरेयमितस्त्वन्यां प्रकृतिं विद्धि मे पराम् |\nजीवभूतां महाबाहो ययेदं धार्यते जगत् ||७-५||",
    "transliteration": "apareyamitastvanyāṃ prakṛtiṃ viddhi me parām .\njīvabhūtāṃ mahābāho yayedaṃ dhāryate jagat ||7-5||",
    "english": "7.5 This is the inferior Prakriti, O mighty-armed (Arjuna); know thou as different from it My higher Prakriti (Nature), the very life-element, by which this world is upheld.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-047",
    "chapter": 7,
    "verse": 7,
    "reference": "7.7",
      "audioSrc": "/audio/7.7.mp3",
    "sanskrit": "मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय |\nमयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव ||७-७||",
    "transliteration": "mattaḥ parataraṃ nānyatkiñcidasti dhanañjaya .\nmayi sarvamidaṃ protaṃ sūtre maṇigaṇā iva ||7-7||",
    "english": "7.7 There is nothing whatsoever higher than Me, O Arjuna. All this is strung on Me, as clusters of gems on a string.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-048",
    "chapter": 7,
    "verse": 14,
    "reference": "7.14",
      "audioSrc": "/audio/7.14.mp3",
    "sanskrit": "दैवी ह्येषा गुणमयी मम माया दुरत्यया |\nमामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते ||७-१४||",
    "transliteration": "daivī hyeṣā guṇamayī mama māyā duratyayā .\nmāmeva ye prapadyante māyāmetāṃ taranti te ||7-14||",
    "english": "7.14 Verily, this divine illusion of Mine, made up of the (three) alities (of Nature) is difficult to cross over; those who take refuge in Me alone, cross over this illusion.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-049",
    "chapter": 7,
    "verse": 15,
    "reference": "7.15",
      "audioSrc": "/audio/7.15.mp3",
    "sanskrit": "न मां दुष्कृतिनो मूढाः प्रपद्यन्ते नराधमाः |\nमाययापहृतज्ञाना आसुरं भावमाश्रिताः ||७-१५||",
    "transliteration": "na māṃ duṣkṛtino mūḍhāḥ prapadyante narādhamāḥ .\nmāyayāpahṛtajñānā āsuraṃ bhāvamāśritāḥ ||7-15||",
    "english": "7.15 The evil-doers and the deluded who are the lowest of men do not seek Me; they whose knowledge is destroyed by illusion follow the ways of demons.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-050",
    "chapter": 7,
    "verse": 16,
    "reference": "7.16",
      "audioSrc": "/audio/7.16.mp3",
    "sanskrit": "चतुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन |\nआर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ ||७-१६||",
    "transliteration": "caturvidhā bhajante māṃ janāḥ sukṛtino.arjuna .\nārto jijñāsurarthārthī jñānī ca bharatarṣabha ||7-16||",
    "english": "7.16 Four kinds of virtuous men worship Me, O Arjuna, and they are the distressed, the seekr of knowledge, the seekr of wealth and the wise, O lord of the Bharatas.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-051",
    "chapter": 7,
    "verse": 19,
    "reference": "7.19",
      "audioSrc": "/audio/7.19.mp3",
    "sanskrit": "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते |\nवासुदेवः सर्वमिति स महात्मा सुदुर्लभः ||७-१९||",
    "transliteration": "bahūnāṃ janmanāmante jñānavānmāṃ prapadyate .\nvāsudevaḥ sarvamiti sa mahātmā sudurlabhaḥ ||7-19||",
    "english": "7.19 At the end of many births the wise man comes to Me, realising that all this is Vaasudeva (the innermost Self); such a great soul (Mahatma) is very hard to find.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-052",
    "chapter": 7,
    "verse": 25,
    "reference": "7.25",
      "audioSrc": "/audio/7.25.mp3",
    "sanskrit": "नाहं प्रकाशः सर्वस्य योगमायासमावृतः |\nमूढोऽयं नाभिजानाति लोको मामजमव्ययम् ||७-२५||",
    "transliteration": "nāhaṃ prakāśaḥ sarvasya yogamāyāsamāvṛtaḥ .\nmūḍho.ayaṃ nābhijānāti loko māmajamavyayam ||7-25||",
    "english": "7.25 I am not manifest to all (as I am) veiled by the Yoga-Maya. This deluded world does not know Me, the unborn and imperishable.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-053",
    "chapter": 7,
    "verse": 26,
    "reference": "7.26",
      "audioSrc": "/audio/7.26.mp3",
    "sanskrit": "वेदाहं समतीतानि वर्तमानानि चार्जुन |\nभविष्याणि च भूतानि मां तु वेद न कश्चन ||७-२६||",
    "transliteration": "vedāhaṃ samatītāni vartamānāni cārjuna .\nbhaviṣyāṇi ca bhūtāni māṃ tu veda na kaścana ||7-26||",
    "english": "7.26 I know, O Arjuna, the beings of the past, the present and the future, but no one knows Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-054",
    "chapter": 7,
    "verse": 27,
    "reference": "7.27",
      "audioSrc": "/audio/7.27.mp3",
    "sanskrit": "इच्छाद्वेषसमुत्थेन द्वन्द्वमोहेन भारत |\nसर्वभूतानि सम्मोहं सर्गे यान्ति परन्तप ||७-२७||",
    "transliteration": "icchādveṣasamutthena dvandvamohena bhārata .\nsarvabhūtāni sammohaṃ sarge yānti parantapa ||7-27||",
    "english": "7.27 By the delusion of the pairs of opposites arising from desire and aversion, O Bharata, all beings are subject to delusion at birth, O Parantapa.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-055",
    "chapter": 7,
    "verse": 28,
    "reference": "7.28",
      "audioSrc": "/audio/7.28.mp3",
    "sanskrit": "येषां त्वन्तगतं पापं जनानां पुण्यकर्मणाम् |\nते द्वन्द्वमोहनिर्मुक्ता भजन्ते मां दृढव्रताः ||७-२८||",
    "transliteration": "yeṣāṃ tvantagataṃ pāpaṃ janānāṃ puṇyakarmaṇām .\nte dvandvamohanirmuktā bhajante māṃ dṛḍhavratāḥ ||7-28||",
    "english": "7.28 But those men of virtuous deeds whose sins have come to an end, and who are freed from the delusion of the pairs of opposites, worship Me, steadfast in their vows.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-056",
    "chapter": 8,
    "verse": 5,
    "reference": "8.5",
      "audioSrc": "/audio/8.5.mp3",
    "sanskrit": "अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम् |\nयः प्रयाति स मद्भावं याति नास्त्यत्र संशयः ||८-५||",
    "transliteration": "antakāle ca māmeva smaranmuktvā kalevaram .\nyaḥ prayāti sa madbhāvaṃ yāti nāstyatra saṃśayaḥ ||8-5||",
    "english": "8.5 And whosoever, leaving the body, goes forth remembering Me alone, at the time of death, he attains My Being: there is no doubt about this.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-057",
    "chapter": 8,
    "verse": 6,
    "reference": "8.6",
      "audioSrc": "/audio/8.6.mp3",
    "sanskrit": "यं यं वापि स्मरन्भावं त्यजत्यन्ते कलेवरम् |\nतं तमेवैति कौन्तेय सदा तद्भावभावितः ||८-६||",
    "transliteration": "yaṃ yaṃ vāpi smaranbhāvaṃ tyajatyante kalevaram .\ntaṃ tamevaiti kaunteya sadā tadbhāvabhāvitaḥ ||8-6||",
    "english": "8.6 Whosoever at the end leaves the body, thinking of any being, to that being only does he go, O son of Kunti (Arjuna), because of his constant thought of that being.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-058",
    "chapter": 8,
    "verse": 7,
    "reference": "8.7",
      "audioSrc": "/audio/8.7.mp3",
    "sanskrit": "तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च |\nमय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयः (orसंशयम्) ||८-७||",
    "transliteration": "tasmātsarveṣu kāleṣu māmanusmara yudhya ca .\nmayyarpitamanobuddhirmāmevaiṣyasyasaṃśayaḥ ||8-7||",
    "english": "8.7 Therefore at all times remember Me only and fight. With mind and intellect fixed (or absorbed) in Me, thou shalt doubtessly come to Me alone.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-059",
    "chapter": 8,
    "verse": 14,
    "reference": "8.14",
      "audioSrc": "/audio/8.14.mp3",
    "sanskrit": "अनन्यचेताः सततं यो मां स्मरति नित्यशः |\nतस्याहं सुलभः पार्थ नित्ययुक्तस्य योगिनः ||८-१४||",
    "transliteration": "ananyacetāḥ satataṃ yo māṃ smarati nityaśaḥ .\ntasyāhaṃ sulabhaḥ pārtha nityayuktasya yoginaḥ ||8-14||",
    "english": "8.14 I am easily attainable by that ever-steadfast Yogi who constantly and daily remembers Me (for a long time), not thinking of anything else (with a single mind or one-pointed mind), O Partha (Arjuna).",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-060",
    "chapter": 8,
    "verse": 15,
    "reference": "8.15",
      "audioSrc": "/audio/8.15.mp3",
    "sanskrit": "मामुपेत्य पुनर्जन्म दुःखालयमशाश्वतम् |\nनाप्नुवन्ति महात्मानः संसिद्धिं परमां गताः ||८-१५||",
    "transliteration": "māmupetya punarjanma duḥkhālayamaśāśvatam .\nnāpnuvanti mahātmānaḥ saṃsiddhiṃ paramāṃ gatāḥ ||8-15||",
    "english": "8.15 Having attained Me these great souls do not again take birth (here) which is the place of pain \nand is non-eternal: they have reached the highest perfection (liberation).",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-061",
    "chapter": 8,
    "verse": 16,
    "reference": "8.16",
      "audioSrc": "/audio/8.16.mp3",
    "sanskrit": "आब्रह्मभुवनाल्लोकाः पुनरावर्तिनोऽर्जुन |\nमामुपेत्य तु कौन्तेय पुनर्जन्म न विद्यते ||८-१६||",
    "transliteration": "ābrahmabhuvanāllokāḥ punarāvartino.arjuna .\nmāmupetya tu kaunteya punarjanma na vidyate ||8-16||",
    "english": "8.16 (All) the worlds including the world of Brahma are subject to return again, O Arjuna; but he who reaches Me, O son of Kunti, has no rirth.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-062",
    "chapter": 8,
    "verse": 28,
    "reference": "8.28",
      "audioSrc": "/audio/8.28.mp3",
    "sanskrit": "वेदेषु यज्ञेषु तपःसु चैव\nदानेषु यत्पुण्यफलं प्रदिष्टम् |\nअत्येति तत्सर्वमिदं विदित्वा\nयोगी परं स्थानमुपैति चाद्यम् ||८-२८||",
    "transliteration": "vedeṣu yajñeṣu tapaḥsu caiva dāneṣu yatpuṇyaphalaṃ pradiṣṭam .\natyeti tatsarvamidaṃ viditvā yogī paraṃ sthānamupaiti cādyam ||8-28||",
    "english": "8.28 Whatever fruit of merit is declared (in the scriptures) to accrue from (the study of) the Vedas, (the performance of) sacrifices, (the practice of) austerities, and gifts  beyond all this goes the Yogi, having known this; and he attains to the Supreme Primeval (first or ancient) Abode.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-063",
    "chapter": 9,
    "verse": 1,
    "reference": "9.1",
      "audioSrc": "/audio/9.1.mp3",
    "sanskrit": "श्रीभगवानुवाच |\nइदं तु ते गुह्यतमं प्रवक्ष्याम्यनसूयवे |\nज्ञानं विज्ञानसहितं यज्ज्ञात्वा मोक्ष्यसेऽशुभात् ||९-१||",
    "transliteration": "śrībhagavānuvāca .\nidaṃ tu te guhyatamaṃ pravakṣyāmyanasūyave .\njñānaṃ vijñānasahitaṃ yajjñātvā mokṣyase.aśubhāt ||9-1||",
    "english": "9.1 The Blessed Lord said  I shall now declare to thee who does not cavil, the greatest secret, the knowledge combined with experience (Self-realisation). Having known this thou shalt be free evil.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-064",
    "chapter": 9,
    "verse": 2,
    "reference": "9.2",
      "audioSrc": "/audio/9.2.mp3",
    "sanskrit": "राजविद्या राजगुह्यं पवित्रमिदमुत्तमम् |\nप्रत्यक्षावगमं धर्म्यं सुसुखं कर्तुमव्ययम् ||९-२||",
    "transliteration": "rājavidyā rājaguhyaṃ pavitramidamuttamam .\npratyakṣāvagamaṃ dharmyaṃ susukhaṃ kartumavyayam ||9-2||",
    "english": "9.2 This is the kingl science, the kingly secret, the supreme purifier, realisable by direct intuitional knowledge, according to righteousness, very easy to perform and imperishable.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-065",
    "chapter": 9,
    "verse": 3,
    "reference": "9.3",
      "audioSrc": "/audio/9.3.mp3",
    "sanskrit": "अश्रद्दधानाः पुरुषा धर्मस्यास्य परन्तप |\nअप्राप्य मां निवर्तन्ते मृत्युसंसारवर्त्मनि ||९-३||",
    "transliteration": "aśraddadhānāḥ puruṣā dharmasyāsya parantapa .\naprāpya māṃ nivartante mṛtyusaṃsāravartmani ||9-3||",
    "english": "9.3 Those who have no faith in this Dharma (knowledge of the Self), O Parantapa (Arjuna), return to the path of this world of death without attaining Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-066",
    "chapter": 9,
    "verse": 4,
    "reference": "9.4",
      "audioSrc": "/audio/9.4.mp3",
    "sanskrit": "मया ततमिदं सर्वं जगदव्यक्तमूर्तिना |\nमत्स्थानि सर्वभूतानि न चाहं तेष्ववस्थितः ||९-४||",
    "transliteration": "mayā tatamidaṃ sarvaṃ jagadavyaktamūrtinā .\nmatsthāni sarvabhūtāni na cāhaṃ teṣvavasthitaḥ ||9-4||",
    "english": "9.4 All this world is pervaded by Me in My unmanifest aspect; all beings exist in Me, but I do not dwell in them.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-067",
    "chapter": 9,
    "verse": 11,
    "reference": "9.11",
      "audioSrc": "/audio/9.11.mp3",
    "sanskrit": "अवजानन्ति मां मूढा मानुषीं तनुमाश्रितम् |\nपरं भावमजानन्तो मम भूतमहेश्वरम् ||९-११||",
    "transliteration": "avajānanti māṃ mūḍhā mānuṣīṃ tanumāśritam .\nparaṃ bhāvamajānanto mama bhūtamaheśvaram ||9-11||",
    "english": "9.11 Fools disregard Me, clad in human form, not knowing My higher Being as the great Lord of (all) beings.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-068",
    "chapter": 9,
    "verse": 12,
    "reference": "9.12",
      "audioSrc": "/audio/9.12.mp3",
    "sanskrit": "मोघाशा मोघकर्माणो मोघज्ञाना विचेतसः |\nराक्षसीमासुरीं चैव प्रकृतिं मोहिनीं श्रिताः ||९-१२||",
    "transliteration": "moghāśā moghakarmāṇo moghajñānā vicetasaḥ .\nrākṣasīmāsurīṃ caiva prakṛtiṃ mohinīṃ śritāḥ ||9-12||",
    "english": "9.12 Of vain hopes, of vain actions, of vain knowledge and senseless, they verily are possessed of the deceitful nature of demons and undivine beings.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-069",
    "chapter": 9,
    "verse": 13,
    "reference": "9.13",
      "audioSrc": "/audio/9.13.mp3",
    "sanskrit": "महात्मानस्तु मां पार्थ दैवीं प्रकृतिमाश्रिताः |\nभजन्त्यनन्यमनसो ज्ञात्वा भूतादिमव्ययम् ||९-१३||",
    "transliteration": "mahātmānastu māṃ pārtha daivīṃ prakṛtimāśritāḥ .\nbhajantyananyamanaso jñātvā bhūtādimavyayam ||9-13||",
    "english": "9.13 But the great souls, O Arjuna, partaking of My divine nature, worship Me with a single mind (with the mind devoted to nothing else), knowing Me as the imperishable source of beings.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-070",
    "chapter": 9,
    "verse": 14,
    "reference": "9.14",
      "audioSrc": "/audio/9.14.mp3",
    "sanskrit": "सततं कीर्तयन्तो मां यतन्तश्च दृढव्रताः |\nनमस्यन्तश्च मां भक्त्या नित्ययुक्ता उपासते ||९-१४||",
    "transliteration": "satataṃ kīrtayanto māṃ yatantaśca dṛḍhavratāḥ .\nnamasyantaśca māṃ bhaktyā nityayuktā upāsate ||9-14||",
    "english": "9.14 Always glorifying Me, striving,firm in vows, prostrating themselves before Me, they worship Me with devotion always steadfast.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-071",
    "chapter": 9,
    "verse": 22,
    "reference": "9.22",
      "audioSrc": "/audio/9.22.mp3",
    "sanskrit": "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते |\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम् ||९-२२||",
    "transliteration": "ananyāścintayanto māṃ ye janāḥ paryupāsate .\nteṣāṃ nityābhiyuktānāṃ yogakṣemaṃ vahāmyaham ||9-22||",
    "english": "9.22 For those men who worship Me alone, thinking of no other, for those ever-united, I secure what is not already possessed and preserve what they already possess.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-072",
    "chapter": 9,
    "verse": 25,
    "reference": "9.25",
      "audioSrc": "/audio/9.25.mp3",
    "sanskrit": "यान्ति देवव्रता देवान्पितॄन्यान्ति पितृव्रताः |\nभूतानि यान्ति भूतेज्या यान्ति मद्याजिनोऽपि माम् ||९-२५||",
    "transliteration": "yānti devavratā devānpitṝnyānti pitṛvratāḥ .\nbhūtāni yānti bhūtejyā yānti madyājino.api mām ||9-25||",
    "english": "9.25 The worshippers of the gods go to them; to the manes go the ancestor-worshippers; to the deities who preside over the elements go their worshippers; but My devotees come to Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-073",
    "chapter": 9,
    "verse": 26,
    "reference": "9.26",
      "audioSrc": "/audio/9.26.mp3",
    "sanskrit": "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति |\nतदहं भक्त्युपहृतमश्नामि प्रयतात्मनः ||९-२६||",
    "transliteration": "patraṃ puṣpaṃ phalaṃ toyaṃ yo me bhaktyā prayacchati .\ntadahaṃ bhaktyupahṛtamaśnāmi prayatātmanaḥ ||9-26||",
    "english": "9.26 Whoever offers Me with devotion a leaf, a flower, a fruit or a little water  that, so offered devotedly by the pure-minded, I accept.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-074",
    "chapter": 9,
    "verse": 27,
    "reference": "9.27",
      "audioSrc": "/audio/9.27.mp3",
    "sanskrit": "यत्करोषि यदश्नासि यज्जुहोषि ददासि यत् |\nयत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम् ||९-२७||",
    "transliteration": "yatkaroṣi yadaśnāsi yajjuhoṣi dadāsi yat .\nyattapasyasi kaunteya tatkuruṣva madarpaṇam ||9-27||",
    "english": "9.27 Whatever thou doest, whatever thou eatest, whatever thou offerest in sacrifice, whatever thou givest, whatever thou practisest as austerity, O Arjuna, do it as an offering unto Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-075",
    "chapter": 9,
    "verse": 29,
    "reference": "9.29",
      "audioSrc": "/audio/9.29.mp3",
    "sanskrit": "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः |\nये भजन्ति तु मां भक्त्या मयि ते तेषु चाप्यहम् ||९-२९||",
    "transliteration": "samo.ahaṃ sarvabhūteṣu na me dveṣyo.asti na priyaḥ .\nye bhajanti tu māṃ bhaktyā mayi te teṣu cāpyaham ||9-29||",
    "english": "9.29 The same am I to all beings; to Me there is none hateful or dear; but those who worship Me with devotion are in Me and I am also in them.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-076",
    "chapter": 9,
    "verse": 32,
    "reference": "9.32",
      "audioSrc": "/audio/9.32.mp3",
    "sanskrit": "मां हि पार्थ व्यपाश्रित्य येऽपि स्युः पापयोनयः |\nस्त्रियो वैश्यास्तथा शूद्रास्तेऽपि यान्ति परां गतिम् ||९-३२||",
    "transliteration": "māṃ hi pārtha vyapāśritya ye.api syuḥ pāpayonayaḥ .\nstriyo vaiśyāstathā śūdrāste.api yānti parāṃ gatim ||9-32||",
    "english": "9.32 For, taking refuge in Me, they also who, O Arjuna, may be of a sinful birth  women, Vaisyas as well as Sudras  attain the Supreme Goal.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-077",
    "chapter": 9,
    "verse": 34,
    "reference": "9.34",
      "audioSrc": "/audio/9.34.mp3",
    "sanskrit": "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु |\nमामेवैष्यसि युक्त्वैवमात्मानं मत्परायणः ||९-३४||",
    "transliteration": "manmanā bhava madbhakto madyājī māṃ namaskuru .\nmāmevaiṣyasi yuktvaivamātmānaṃ matparāyaṇaḥ ||9-34||",
    "english": "9.34 Fix thy mind on Me; by devoted to Me; sacrifice unto Me; bow down to Me; having thus united thy whole self to Me, taking Me as the supreme goal, thou shalt come unto Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-078",
    "chapter": 10,
    "verse": 1,
    "reference": "10.1",
      "audioSrc": "/audio/10.1.mp3",
    "sanskrit": "श्रीभगवानुवाच |\nभूय एव महाबाहो शृणु मे परमं वचः |\nयत्तेऽहं प्रीयमाणाय वक्ष्यामि हितकाम्यया ||१०-१||",
    "transliteration": "śrībhagavānuvāca .\nbhūya eva mahābāho śṛṇu me paramaṃ vacaḥ .\nyatte.ahaṃ prīyamāṇāya vakṣyāmi hitakāmyayā ||10-1||",
    "english": "10.1 The Blessed Lord said  Again, O mighty-armed Arjuna, listen to my supreme word which I will declare to thee who who art beloved, for thy welfare.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-079",
    "chapter": 10,
    "verse": 8,
    "reference": "10.8",
      "audioSrc": "/audio/10.8.mp3",
    "sanskrit": "अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते |\nइति मत्वा भजन्ते मां बुधा भावसमन्विताः ||१०-८||",
    "transliteration": "ahaṃ sarvasya prabhavo mattaḥ sarvaṃ pravartate .\niti matvā bhajante māṃ budhā bhāvasamanvitāḥ ||10-8||",
    "english": "10.8 I am the source of all; from Me everything evolves; understanding thus, the wise, endowed with meditation, worship Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-080",
    "chapter": 10,
    "verse": 9,
    "reference": "10.9",
      "audioSrc": "/audio/10.9.mp3",
    "sanskrit": "मच्चित्ता मद्गतप्राणा बोधयन्तः परस्परम् |\nकथयन्तश्च मां नित्यं तुष्यन्ति च रमन्ति च ||१०-९||",
    "transliteration": "maccittā madgataprāṇā bodhayantaḥ parasparam .\nkathayantaśca māṃ nityaṃ tuṣyanti ca ramanti ca ||10-9||",
    "english": "10.9 With their mind and their life wholly absorbed in Me, enlightening each other and ever speaking of Me, they are satisfied and delighted.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-081",
    "chapter": 10,
    "verse": 11,
    "reference": "10.11",
      "audioSrc": "/audio/10.11.mp3",
    "sanskrit": "तेषामेवानुकम्पार्थमहमज्ञानजं तमः |\nनाशयाम्यात्मभावस्थो ज्ञानदीपेन भास्वता ||१०-११||",
    "transliteration": "teṣāmevānukampārthamahamajñānajaṃ tamaḥ .\nnāśayāmyātmabhāvastho jñānadīpena bhāsvatā ||10-11||",
    "english": "10.11 Out of mere compassion for them, I, dwelling within their Self, destroy the darkness born of ignorance by the luminous lamp of knowledge.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-082",
    "chapter": 10,
    "verse": 12,
    "reference": "10.12",
      "audioSrc": "/audio/10.12.mp3",
    "sanskrit": "अर्जुन उवाच |\nपरं ब्रह्म परं धाम पवित्रं परमं भवान् |\nपुरुषं शाश्वतं दिव्यमादिदेवमजं विभुम् ||१०-१२||",
    "transliteration": "arjuna uvāca .\nparaṃ brahma paraṃ dhāma pavitraṃ paramaṃ bhavān .\npuruṣaṃ śāśvataṃ divyamādidevamajaṃ vibhum ||10-12||",
    "english": "10.12 Arjuna said  Thou art the Supreme Brahman, the supreme abode (or the supreme light), the supreme purifier, eternal, divine Person, the primeval God, unborn andn omnipresent.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-083",
    "chapter": 10,
    "verse": 13,
    "reference": "10.13",
      "audioSrc": "/audio/10.13.mp3",
    "sanskrit": "आहुस्त्वामृषयः सर्वे देवर्षिर्नारदस्तथा |\nअसितो देवलो व्यासः स्वयं चैव ब्रवीषि मे ||१०-१३||",
    "transliteration": "āhustvāmṛṣayaḥ sarve devarṣirnāradastathā .\nasito devalo vyāsaḥ svayaṃ caiva bravīṣi me ||10-13||",
    "english": "10.13 All the sages have thus declared Thee, as also the divine sage Narada; so also Asita, Devala and Vyasa; and now Thou Thyself sayest so to me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-084",
    "chapter": 10,
    "verse": 41,
    "reference": "10.41",
      "audioSrc": "/audio/10.41.mp3",
    "sanskrit": "यद्यद्विभूतिमत्सत्त्वं श्रीमदूर्जितमेव वा |\nतत्तदेवावगच्छ त्वं मम तेजोंऽशसम्भवम् ||१०-४१||",
    "transliteration": "yadyadvibhūtimatsattvaṃ śrīmadūrjitameva vā .\ntattadevāvagaccha tvaṃ mama tejoṃśasambhavam ||10-41||",
    "english": "10.41 Whatever being there is glorious, prosperous or powerful, that know thou to be a manifestation of a part of My splendour.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-085",
    "chapter": 11,
    "verse": 54,
    "reference": "11.54",
      "audioSrc": "/audio/11.54.mp3",
    "sanskrit": "भक्त्या त्वनन्यया शक्य अहमेवंविधोऽर्जुन |\nज्ञातुं द्रष्टुं च तत्त्वेन प्रवेष्टुं च परन्तप ||११-५४||",
    "transliteration": "bhaktyā tvananyayā śakya ahamevaṃvidho.arjuna .\njñātuṃ draṣṭuṃ ca tattvena praveṣṭuṃ ca parantapa ||11-54||",
    "english": "11.54 But by single-minded devotion can I, of this Form, be known and seen in reality and also entered into, O Arjuna.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-086",
    "chapter": 11,
    "verse": 55,
    "reference": "11.55",
      "audioSrc": "/audio/11.55.mp3",
    "sanskrit": "मत्कर्मकृन्मत्परमो मद्भक्तः सङ्गवर्जितः |\nनिर्वैरः सर्वभूतेषु यः स मामेति पाण्डव ||११-५५||",
    "transliteration": "matkarmakṛnmatparamo madbhaktaḥ saṅgavarjitaḥ .\nnirvairaḥ sarvabhūteṣu yaḥ sa māmeti pāṇḍava ||11-55||",
    "english": "11.55 He who does all actions for Me, who looks upon Me as the Supreme, who is devoted to Me, who is free from attachment, who bears enmity towards no creature, he comes to Me, O Arjuna.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-087",
    "chapter": 12,
    "verse": 1,
    "reference": "12.1",
      "audioSrc": "/audio/12.1.mp3",
    "sanskrit": "अर्जुन उवाच |\nएवं सततयुक्ता ये भक्तास्त्वां पर्युपासते |\nये चाप्यक्षरमव्यक्तं तेषां के योगवित्तमाः ||१२-१||",
    "transliteration": "arjuna uvāca .\nevaṃ satatayuktā ye bhaktāstvāṃ paryupāsate .\nye cāpyakṣaramavyaktaṃ teṣāṃ ke yogavittamāḥ ||12-1||",
    "english": "12.1 Arjuna said  Those devotees who, ever steadfast, thus worship Thee and those also who worship the imperishable and the unmanifested  which of them are better versed in Yoga?",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-088",
    "chapter": 12,
    "verse": 5,
    "reference": "12.5",
      "audioSrc": "/audio/12.5.mp3",
    "sanskrit": "क्लेशोऽधिकतरस्तेषामव्यक्तासक्तचेतसाम् |\nअव्यक्ता हि गतिर्दुःखं देहवद्भिरवाप्यते ||१२-५||",
    "transliteration": "kleśo.adhikatarasteṣāmavyaktāsaktacetasām ||\navyaktā hi gatirduḥkhaṃ dehavadbhiravāpyate ||12-5||",
    "english": "12.5 Greater is their trouble whose minds are set on the unmanifested; for the goal; the unmanifested, is very hard for the embodied to reach.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-089",
    "chapter": 12,
    "verse": 8,
    "reference": "12.8",
      "audioSrc": "/audio/12.8.mp3",
    "sanskrit": "मय्येव मन आधत्स्व मयि बुद्धिं निवेशय |\nनिवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः ||१२-८||",
    "transliteration": "mayyeva mana ādhatsva mayi buddhiṃ niveśaya .\nnivasiṣyasi mayyeva ata ūrdhvaṃ na saṃśayaḥ ||12-8||",
    "english": "12.8 Fix thy mind in Me only, thy intellect in Me, (then) thou shalt no doubt live in Me alone hereafter.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-090",
    "chapter": 12,
    "verse": 9,
    "reference": "12.9",
      "audioSrc": "/audio/12.9.mp3",
    "sanskrit": "अथ चित्तं समाधातुं न शक्नोषि मयि स्थिरम् |\nअभ्यासयोगेन ततो मामिच्छाप्तुं धनञ्जय ||१२-९||",
    "transliteration": "atha cittaṃ samādhātuṃ na śaknoṣi mayi sthiram .\nabhyāsayogena tato māmicchāptuṃ dhanañjaya ||12-9||",
    "english": "12.9 If thou art unable to fix thy mind steadily on Me, then by the Yoga of constant practice do thou seek to reach Me, O Arjuna.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-091",
    "chapter": 14,
    "verse": 4,
    "reference": "14.4",
      "audioSrc": "/audio/14.4.mp3",
    "sanskrit": "सर्वयोनिषु कौन्तेय मूर्तयः सम्भवन्ति याः |\nतासां ब्रह्म महद्योनिरहं बीजप्रदः पिता ||१४-४||",
    "transliteration": "sarvayoniṣu kaunteya mūrtayaḥ sambhavanti yāḥ .\ntāsāṃ brahma mahadyonirahaṃ bījapradaḥ pitā ||14-4||",
    "english": "14.4 Whatever forms are produced, O Arjuna, in any womb whatsoever, the great Brahma is their womb and I am the seed-giving father.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-092",
    "chapter": 14,
    "verse": 26,
    "reference": "14.26",
      "audioSrc": "/audio/14.26.mp3",
    "sanskrit": "मां च योऽव्यभिचारेण भक्तियोगेन सेवते |\nस गुणान्समतीत्यैतान्ब्रह्मभूयाय कल्पते ||१४-२६||",
    "transliteration": "māṃ ca yo.avyabhicāreṇa bhaktiyogena sevate .\nsa guṇānsamatītyaitānbrahmabhūyāya kalpate ||14-26||",
    "english": "14.26 And he who serves Me with unswerving devotion, he, crossing beyond the alities, is fit for becoming Brahman.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-093",
    "chapter": 14,
    "verse": 27,
    "reference": "14.27",
      "audioSrc": "/audio/14.27.mp3",
    "sanskrit": "ब्रह्मणो हि प्रतिष्ठाहममृतस्याव्ययस्य च |\nशाश्वतस्य च धर्मस्य सुखस्यैकान्तिकस्य च ||१४-२७||",
    "transliteration": "brahmaṇo hi pratiṣṭhāhamamṛtasyāvyayasya ca .\nśāśvatasya ca dharmasya sukhasyaikāntikasya ca ||14-27||",
    "english": "14.27 For I am the abode of Brahman, the immortal and the immutable, of everlasting Dharma and of absolute bliss.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-094",
    "chapter": 15,
    "verse": 5,
    "reference": "15.5",
      "audioSrc": "/audio/15.5.mp3",
    "sanskrit": "निर्मानमोहा जितसङ्गदोषा\nअध्यात्मनित्या विनिवृत्तकामाः |\nद्वन्द्वैर्विमुक्ताः सुखदुःखसंज्ञैर्-\nगच्छन्त्यमूढाः पदमव्ययं तत् ||१५-५||",
    "transliteration": "nirmānamohā jitasaṅgadoṣā adhyātmanityā vinivṛttakāmāḥ .\ndvandvairvimuktāḥ sukhaduḥkhasaṃjñaira- gacchantyamūḍhāḥ padamavyayaṃ tat ||15-5||",
    "english": "15.5 Free from pride and delusion, victorious over the evil of attachment, dwelling constantly in the Self, their desires having completely turned away, freed from the pairs of opposites known as pleasure and pain, the undeluded reach the eternal goal.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-095",
    "chapter": 15,
    "verse": 6,
    "reference": "15.6",
      "audioSrc": "/audio/15.6.mp3",
    "sanskrit": "न तद्भासयते सूर्यो न शशाङ्को न पावकः |\nयद्गत्वा न निवर्तन्ते तद्धाम परमं मम ||१५-६||",
    "transliteration": "na tadbhāsayate sūryo na śaśāṅko na pāvakaḥ .\nyadgatvā na nivartante taddhāma paramaṃ mama ||15-6||",
    "english": "15.6 Neither doth the sun illumine there nor the moon, nor the fire; having gone thither they return not; that is My supreme abode.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-096",
    "chapter": 15,
    "verse": 7,
    "reference": "15.7",
      "audioSrc": "/audio/15.7.mp3",
    "sanskrit": "ममैवांशो जीवलोके जीवभूतः सनातनः |\nमनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति ||१५-७||",
    "transliteration": "mamaivāṃśo jīvaloke jīvabhūtaḥ sanātanaḥ .\nmanaḥṣaṣṭhānīndriyāṇi prakṛtisthāni karṣati ||15-7||",
    "english": "15.7 An eternal portion of Myself having become a living soul in the world of life, draws to (itself) the (five) senses with the mind for the sixth, abiding in Nature.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-097",
    "chapter": 15,
    "verse": 15,
    "reference": "15.15",
    "sanskrit": "सर्वस्य चाहं हृदि सन्निविष्टो\nमत्तः स्मृतिर्ज्ञानमपोहनञ्च |\nवेदैश्च सर्वैरहमेव वेद्यो\nवेदान्तकृद्वेदविदेव चाहम् ||१५-१५||",
    "transliteration": "sarvasya cāhaṃ hṛdi sanniviṣṭo mattaḥ smṛtirjñānamapohanañca .\nvedaiśca sarvairahameva vedyo vedāntakṛdvedavideva cāham ||15-15||",
    "english": "15.15 And I am seated in the hearts of all; from Me are memory and knowledge, as well as their absence. I am verily That which has to be known by all the Vedas; I am indeed the author of the Vedanta and the knower of the Vedas am I.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-098",
    "chapter": 15,
    "verse": 19,
    "reference": "15.19",
      "audioSrc": "/audio/15.19.mp3",
    "sanskrit": "यो मामेवमसम्मूढो जानाति पुरुषोत्तमम् |\nस सर्वविद्भजति मां सर्वभावेन भारत ||१५-१९||",
    "transliteration": "yo māmevamasammūḍho jānāti puruṣottamam .\nsa sarvavidbhajati māṃ sarvabhāvena bhārata ||15-19||",
    "english": "15.19 He who, undeluded, knows Me thus as the highest Purusha, he, knowing all, worships Me with his whole being (heart), O Arjuna.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-099",
    "chapter": 18,
    "verse": 42,
    "reference": "18.42",
      "audioSrc": "/audio/18.42.mp3",
    "sanskrit": "शमो दमस्तपः शौचं क्षान्तिरार्जवमेव च |\nज्ञानं विज्ञानमास्तिक्यं ब्रह्मकर्म स्वभावजम् ||१८-४२||",
    "transliteration": "śamo damastapaḥ śaucaṃ kṣāntirārjavameva ca .\njñānaṃ vijñānamāstikyaṃ brahmakarma svabhāvajam ||18-42||",
    "english": "18.42 Serenity, self-restraint, austerity, purity, forgiveness and also uprightness, knowledge, realisation and belief in God are the duties of the Brahmanas, born of (their own) nature.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-100",
    "chapter": 18,
    "verse": 54,
    "reference": "18.54",
      "audioSrc": "/audio/18.54.mp3",
    "sanskrit": "ब्रह्मभूतः प्रसन्नात्मा न शोचति न काङ्क्षति |\nसमः सर्वेषु भूतेषु मद्भक्तिं लभते पराम् ||१८-५४||",
    "transliteration": "brahmabhūtaḥ prasannātmā na śocati na kāṅkṣati .\nsamaḥ sarveṣu bhūteṣu madbhaktiṃ labhate parām ||18-54||",
    "english": "18.54 Becoming Brahman, serene in the Self, he neither grieves nor desires, the same to all beings, he obtains supreme devotion to Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-101",
    "chapter": 18,
    "verse": 55,
    "reference": "18.55",
      "audioSrc": "/audio/18.55.mp3",
    "sanskrit": "भक्त्या मामभिजानाति यावान्यश्चास्मि तत्त्वतः |\nततो मां तत्त्वतो ज्ञात्वा विशते तदनन्तरम् ||१८-५५||",
    "transliteration": "bhaktyā māmabhijānāti yāvānyaścāsmi tattvataḥ .\ntato māṃ tattvato jñātvā viśate tadanantaram ||18-55||",
    "english": "18.55 By devotion he knows Me in truth, what and who I am; then having known Me in truth, he forthwith enters into the Supreme.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-102",
    "chapter": 18,
    "verse": 58,
    "reference": "18.58",
      "audioSrc": "/audio/18.58.mp3",
    "sanskrit": "मच्चित्तः सर्वदुर्गाणि मत्प्रसादात्तरिष्यसि |\nअथ चेत्त्वमहंकारान्न श्रोष्यसि विनङ्क्ष्यसि ||१८-५८||",
    "transliteration": "maccittaḥ sarvadurgāṇi matprasādāttariṣyasi .\natha cettvamahaṃkārānna śroṣyasi vinaṅkṣyasi ||18-58||",
    "english": "18.58 Fixing thy mind on Me, thou shalt by My grace overcome all obstacles; but if from egoism thou wilt not hear Me, thou shalt perish.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-103",
    "chapter": 18,
    "verse": 61,
    "reference": "18.61",
      "audioSrc": "/audio/18.61.mp3",
    "sanskrit": "ईश्वरः सर्वभूतानां हृद्देशेऽर्जुन तिष्ठति |\nभ्रामयन्सर्वभूतानि यन्त्रारूढानि मायया ||१८-६१||",
    "transliteration": "īśvaraḥ sarvabhūtānāṃ hṛddeśe.arjuna tiṣṭhati .\nbhrāmayansarvabhūtāni yantrārūḍhāni māyayā ||18-61||",
    "english": "18.61 The Lord dwells in the hearts of all beings, O Arjuna, causing all beings, by His illusive power, to revolve as if mounted on a machine.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-104",
    "chapter": 18,
    "verse": 65,
    "reference": "18.65",
      "audioSrc": "/audio/18.65.mp3",
    "sanskrit": "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु |\nमामेवैष्यसि सत्यं ते प्रतिजाने प्रियोऽसि मे ||१८-६५||",
    "transliteration": "manmanā bhava madbhakto madyājī māṃ namaskuru .\nmāmevaiṣyasi satyaṃ te pratijāne priyo.asi me ||18-65||",
    "english": "18.65 Fix thy mind on Me, by devoted to Me, sacrifice to Me, bow down to Me. Thou shalt come even to Me; truly do I promise unto thee, (for) thou art dear to Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-105",
    "chapter": 18,
    "verse": 66,
    "reference": "18.66",
      "audioSrc": "/audio/18.66.mp3",
    "sanskrit": "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज |\nअहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः ||१८-६६||",
    "transliteration": "sarvadharmānparityajya māmekaṃ śaraṇaṃ vraja .\nahaṃ tvāṃ sarvapāpebhyo mokṣyayiṣyāmi mā śucaḥ ||18-66||",
    "english": "18.66 Abandoning all duties, take refuge in Me alone: I will liberate thee from all sins; grieve not.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-106",
    "chapter": 18,
    "verse": 68,
    "reference": "18.68",
      "audioSrc": "/audio/18.68.mp3",
    "sanskrit": "य इदं परमं गुह्यं मद्भक्तेष्वभिधास्यति |\nभक्तिं मयि परां कृत्वा मामेवैष्यत्यसंशयः ||१८-६८||",
    "transliteration": "ya idaṃ paramaṃ guhyaṃ madbhakteṣvabhidhāsyati .\nbhaktiṃ mayi parāṃ kṛtvā māmevaiṣyatyasaṃśayaḥ ||18-68||",
    "english": "18.68 He who with supreme devotion to Me will teach this supreme secret to My devotees, shall doubtlessly come to Me.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-107",
    "chapter": 18,
    "verse": 69,
    "reference": "18.69",
      "audioSrc": "/audio/18.69.mp3",
    "sanskrit": "न च तस्मान्मनुष्येषु कश्चिन्मे प्रियकृत्तमः |\nभविता न च मे तस्मादन्यः प्रियतरो भुवि ||१८-६९||",
    "transliteration": "na ca tasmānmanuṣyeṣu kaścinme priyakṛttamaḥ .\nbhavitā na ca me tasmādanyaḥ priyataro bhuvi ||18-69||",
    "english": "18.69 Nor is there any among men who does dearer service to Me, nor shall there be another on earth dearer to Me than he.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  },
  {
    "id": "GS-108",
    "chapter": 18,
    "verse": 78,
    "reference": "18.78",
      "audioSrc": "/audio/18.78.mp3",
    "sanskrit": "यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः |\nतत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम ||१८-७८||",
    "transliteration": "yatra yogeśvaraḥ kṛṣṇo yatra pārtho dhanurdharaḥ .\ntatra śrīrvijayo bhūtirdhruvā nītirmatirmama ||18-78||",
    "english": "18.78 Wherever is Krishna, the Lord of Yoga; wherever is Arjuna, the wielder of the bow; there are prosperity, victory, happiness and firm policy; such is my conviction.",
    "translationAuthor": "Swami Sivananda",
    "reflectionPrompt": "Summarize this teaching in your own words and apply it once today."
  }
];

export const TOTAL_SHLOKAS = SHLOKAS.length;
export const DAILY_TARGET = 2;
export const JOURNEY_DAYS = TOTAL_SHLOKAS / DAILY_TARGET;
